### ISSUE TITLE
Create option to specify github protocol

### ISSUE THREAD

**Issue by jedahan** [hexpm/hex#100]
so, with mix.exs, you can have a dep spec like the following:
```
{:httpotion, github: "kemonomachi/httpotion", branch: "master" }
```

I am behind a restrictive network, that only supports http/https traffic. By default, the github identifier tries `git://...`. Could we add an option to hex or mix to specify downloading via https?

I am new to elixir and mix and hex, so if this is in the wrong repo, I'd appreciate showing me the correct one.

**Comment by ericmj** [comment]
You can configure git to rewrite URLs: https://stackoverflow.com/questions/1722807/git-convert-git-urls-to-http-urls

**Comment by jedahan** [comment]
thanks, that worked well!
