### ISSUE TITLE
Release canditate version resolution incorrect after two digits

### ISSUE THREAD

**Issue by eliasdarruda** [hexpm/hex#1002]
## How to reproduce

If i have the following dependency:

`{:my_dependency, "~> 1.0.0-rc9"}`

and I upgrade to:

`{:my_dependency, "~> 1.0.0-rc10"}`

It will resolve to rc9 instead of rc10.

## Expected output
Resolve to rc10 instead of rc9

## Context

I haven't tested for other versions other than release canditates.

**Comment by wojtekmach** [comment]
Can you change rcN to rc.N (ie separated by dot) and see if it works? Per spec the former should be compared lexically but the latter numerically.

**Comment by wojtekmach** [comment]
Great, thanks for checking. I believe we can close this.
