### ISSUE TITLE
Full remove a package from hex.pm

### ISSUE THREAD

**Issue by epinault** [hexpm/hex#1004]
So we have a private package and moved it to OSS.  
to avoid confusion we want to remove our private package fully so it s not even visible in the UI and complete gone from hex.pm

how do we do that? I see we can retire specific version but we want no versions at all and be done with it

I cannot seem to find doc for that

**Comment by wojtekmach** [comment]
https://hex.pm/docs/faq#can-packages-be-removed-from-the-repository

Please remove your releases with `mix hex.publish —revert`. Once you revert last release, your private package will be gone.

**Comment by epinault** [comment]
ah thanks!
