### ISSUE TITLE
hex remote API?

### ISSUE THREAD

**Issue by benoitc** [hexpm/hex#102]
Is the API to fetch/submit/browse/... packages documented somewhere?

**Comment by ericmj** [comment]
Package tarballs, the registry format and their endpoints is documented: https://github.com/hexpm/hex_web/issues/74. We are working on structuring it better and documenting the HTTP API, today the best way is to read the source: https://github.com/hexpm/hex_web/blob/master/lib/hex_web/api/router.ex

**Comment by benoitc** [comment]
thanks for the answer :) Closing the issue now.
