### ISSUE TITLE
Error installing Hex

### ISSUE THREAD

**Issue by ZacBridge** [hexpm/hex#1023]
Within the past hour or 2, Hex is no longer available to be installed, both locally and in our CI pipeline (CircleCI - Docker machine).

<img width="849" alt="image" src="https://github.com/hexpm/hex/assets/34629184/134a46f7-cb6f-476c-83c2-769a9568edca">

This issue also persists with hex rebar. This is occurring over multiple project and Elixir/Erlang versions.

Commands being used are `mix local.hex --force` and `mix local.rebar --force`

**Comment by rodrigocaldeirasumup** [comment]
One thing I noticed is that the url `https://repo.hex.pm/installs/hex1.x.csv` is redirecting to `https://builds.hex.pm//installs/hex-1.x.csv` and this url returns error 404.

By accessing the url `https://builds.hex.pm/installs/hex-1.x.csv`, the CSV file is downloaded without problems.

Perhaps it is a redirection problem only.

**Comment by ZacBridge** [comment]
Good point - I missed that. There's an additional `/` at the end of the BASE_URL.

**Comment by rodrigocaldeirasumup** [comment]
It seems to be OK now!

**Comment by ZacBridge** [comment]
Yes - working for me too. Unit tests successfully failing once more!

I'll close this.
