### ISSUE TITLE
 description in the site search

### ISSUE THREAD

**Issue by williamgueiros** [hexpm/hex#103]
You believe to be possible, search by description on the website?

for example: try found WSDL or WSDL/SOAP projects, and you will receive "No Results Found".

but using, https://github.com/h4cc/awesome-elixir#rest-and-api and you will find detergentex

![hex](https://cloud.githubusercontent.com/assets/19972/8359966/167174d0-1b40-11e5-9dbf-667dc9584ff8.png)

if you saw the description, have the information i want to find.

**Comment by ericmj** [comment]
We do search by description but it seems like the word stemmer doesn't split words on `/`. Please open an issue on https://github.com/hexpm/hex_web.
