### ISSUE TITLE
Add option to disable confirmation in local.hex and archive.install tasks

### ISSUE THREAD

**Issue by mspanc** [hexpm/hex#104]
At the moment the only way to automate installation of hex and some archive.install tasks while e.g. provisioning a server through ansible is to use such hack:

`yes | mix hex.local`

which causes to type "y" character at mix's stdin.

Otherwise it will get stuck on confirmation.

It's rather nasty solution, I suggest adding environment variable that disables confirmation, similar in functionality to DEBIAN_NONINTERACTIVE in apt-get.

**Comment by josevalim** [comment]
We have it already:

    mix local.hex --force

It is also listed in `mix help local.hex`.

**Comment by Olshansk** [comment]
For anyone else that stumbles on this issue, `--force` works for other mix commands as well. For example:

> mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez
