### ISSUE TITLE
 Fail to load function 'Elixir.Hex.Netrc.Cache':fetch/1 with Elixir 1.17.0 and OTP 27

### ISSUE THREAD

**Issue by oliviasculley** [hexpm/hex#1046]
OTP 27 has landed and Elixir 1.17.0 was just released and it seems that `release.sh` needs to be updated in order to support these, similarly to #1014

Please let me know if there's any additional information that you need!

**Comment by ericmj** [comment]
I don't think we need to build for Elixir 1.17.0 since we have had no other reports of this issue and there's already many users on Elixir 1.17.0.

How did you install OTP, Elixir, and Hex and can you show the full output of the command you are running?

**Comment by oliviasculley** [comment]
Sorry about this, my `~/.mix/archives` seemed to be causing it to load Hex 2.0.4 in the `elixir:1.17.0-otp-27-alpine` image which was causing this issue, which was probably possible because of `mix local.hex --force && mix local.rebar --force` in the build steps where I think local.rebar should be first. Please let me know if there's another issue here, but otherwise I'll close this issue for now
