### ISSUE TITLE
Poor error message for dependency resolution

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#107]
in a project with a top level dependency of `{:foo, "1.2.3", override: true}` if there exists another dependency that also has `:foo` as a dependency like: `{:foo, "1.2.4", override: true}` or `{:foo, "1.2.2", override: true}` then dependency resolution fails with the following error message:

```elixir
Running dependency resolution
** (ArgumentError) could not put/update key :deps. Expected map/struct, got: nil
    (elixir) lib/access.ex:121: Access.Map.get_and_update!/3
    lib/hex/resolver.ex:190: Hex.Resolver.attach_dep_and_children/3
    lib/hex/resolver.ex:150: Hex.Resolver.get_deps/4
    lib/hex/resolver.ex:109: Hex.Resolver.activate/5
    lib/hex/resolver.ex:31: Hex.Resolver.resolve/3
    lib/hex/remote_converger.ex:33: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:79: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4

```

it doesn't seem to matter whether dependencies are hex deps or github deps, or whether the transitive dependency specifies a higher or lower version of the dependency

**Comment by ericmj** [comment]
From https://github.com/elixir-lang/elixir/issues/3459.
/cc @talentdeficit

**Comment by enulex** [comment]
got the same error，

    * Updating exjsx (git://github.com/talentdeficit/exjsx.git)
    * Updating poolboy (git://github.com/devinus/poolboy.git)
    * Updating amqp_client (git://github.com/pma/amqp_client.git)
    * Updating exrm (git://github.com/bitwalker/exrm.git)
    * Updating rabbit_common (git://github.com/jbrisbin/rabbit_common.git)
    Running dependency resolution
    ** (ArgumentError) could not put/update key :deps. Expected map/struct, got: nil
        (elixir) lib/access.ex:121: Access.Map.get_and_update!/3
        lib/hex/resolver.ex:190: Hex.Resolver.attach_dep_and_children/3
        lib/hex/resolver.ex:150: Hex.Resolver.get_deps/5
        lib/hex/resolver.ex:109: Hex.Resolver.activate/5
        lib/hex/resolver.ex:31: Hex.Resolver.resolve/3
        lib/hex/remote_converger.ex:33: Hex.RemoteConverger.converge/2
        (mix) lib/mix/dep/converger.ex:79: Mix.Dep.Converger.all/4
        (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4

**Comment by eproxus** [comment]
I can reproduce this with a slightly different dependency specification in `mix.exs`:

```elixir
  defp deps do
    [
      {:mock, github: "jjh42/mock", tag: "v0.1.1"},
      {:meck, github: "eproxus/meck"},
    ]
  end
```

Note the absence of `override: true`.

**Comment by eproxus** [comment]
A quick question, if I want to test this, how would I go about getting the latest Hex/Mix version?

**Comment by ericmj** [comment]
You don't need latest Mix since Hex is supposed to work with Elixir 1.0.0+. You can get the development version of Hex by cloning the github repo and then running `mix install` in the project directory. To revert back to stable run `mix local.hex`.

**Comment by eproxus** [comment]
Thanks!
