### ISSUE TITLE
Resolution clash when version is ">= 0.0.0"

### ISSUE THREAD

**Issue by HashNuke** [hexpm/hex#112]
This is from a newly generated Phoenix app with the latest version of hex (worked fine with an older version).

```
~/projects/hello-phoenix:master★ mix deps.get
Running dependency resolution
Looking up alternatives for conflicting requirements on postgrex
  Activated version: 0.9.1
  From ecto v0.13.1: ~> 0.8.3
  From mix.exs: >= 0.0.0
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
```

* mix.exs - https://github.com/HashNuke/hello-phoenix/blob/8249e3ae3d665e7448b38e309a251cae000754a7/mix.exs
* mix.lock - https://github.com/HashNuke/hello-phoenix/blob/8249e3ae3d665e7448b38e309a251cae000754a7/mix.lock

**Comment by josevalim** [comment]
Are we activating 0.9.1 prematurely?

**Comment by ericmj** [comment]
The activated version is from the lock, see: https://github.com/hexpm/hex/issues/109

You probably run `deps.get` with the broken version of Hex and then updated Hex. The broken version put postgrex 0.9.1 even though it shouldn't. Run `mix deps.unlock postgrex`.

**Comment by HashNuke** [comment]
@ericmj Thanks. That worked ~!
