### ISSUE TITLE
Getting an error when did not provide :build_tools opt

### ISSUE THREAD

**Issue by gjaldon** [hexpm/hex#117]
Running `mix hex.publish` returns the following error:
```shell
Pushing ecto_enum v0.2.2 failed
Validation failed
  meta:
    build_tools: expected type array(string)
```

Reading the docs, it looks like `:build_tools` is automatically detected when not explicitly set so it should've worked fine. It worked ok in the past. My workaround for this was to add `build_tools: ~w(mix)` option to the package.

**Comment by josevalim** [comment]
What is your hex version? Run mix hex.info. also, does it happen with
latest Hex?



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by gjaldon** [comment]
I was using Hex v0.8.1. Just updated to v0.8.3 and will try to publish again in about an hour

**Comment by ericmj** [comment]
There was a bug for build_tools in 0.8.1, it is supposed to be fixed now. Please reopen if you still have the issue on latest.

**Comment by gjaldon** [comment]
Ok thank you. Will update here if I still encounter any issues. :)
