### ISSUE TITLE
Provide "mix hex.registry"

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#119]
The idea of `hex.cache` is to dump a copy of the registry and packages into a directory so they can be loaded. It should work offline too as long as the packages are already in my machine. Something like this:

    # Locally
    mix hex.cache dump vendor/packages
    git add vendor/packages
    git push

    # In production
    mix hex.cache load vendor/packages
    mix deps.get --no-remote # Do we have a flag like this?
    mix run # It works

Thoughts?

**Comment by ericmj** [comment]
This will only work for packages, git dependencies will not be vendored, will the be unexpected?

`mix hex.cache load vendor/packages ` would have to write to the config file so we will load from `/.../my_project/vendor/packages` forever until someone changes the config.

We can't pass flags from `mix deps.get` to Hex unless Hex reads from `System.argv` directly.

**Comment by josevalim** [comment]
Actually, do we really need this? Isn't this just a matter of checking "deps" into version control?

**Comment by josevalim** [comment]
I think the only limitation is the registry?

**Comment by ericmj** [comment]
That should be enough but we need to verify it first. Should we make hex look for the registry in the local directory before checking `HEX_HOME` or should it be a configuration?

**Comment by josevalim** [comment]
@ericmj I am not sure. Maybe we should get this proposal and just do:

    mix hex.registry fetch # explicit fetch
    mix hex.registry dump path
    mix hex.registry load path

And add a HEX_OFFLINE flag.

**Comment by ericmj** [comment]
`dump` would copy from `$HEX_HOME/registry.ets.gz` to `path` and `load` would do the reverse? :+1:

**Comment by josevalim** [comment]
Yes.

**Comment by ericmj** [comment]
To further clarify for contributors: if the environment variable `HEX_OFFLINE` is set then we shouldn't fetch the registry or packages, instead only use the cached files.

**Comment by lexmag** [comment]
:+1:

**Comment by lexmag** [comment]
I'll handle it.
