### ISSUE TITLE
Add task to build a package without publishing it

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#120]
Will be useful for building private packages.

**Comment by jcspencer** [comment]
In other words, would this task simply generate the tarball that would usually be pushed to Hex, but instead of uploading it, it would write it to the filesystem?

**Comment by ericmj** [comment]
Yes

**Comment by jcspencer** [comment]
Could this be achieved by adding something along the lines of a `--no-upload` argument to `mix hex.publish`, or would it be wiser to seperate the generalised tarball generation code from the code that uploads the tarball to hex.pm?

**Comment by ericmj** [comment]
I think it should be a separate task because `--no-upload` doesn't compose with other options. What does `mix hex.publish --no-upload --revert` mean?

**Comment by montague** [comment]
@jcspencer are you working on this? if not, i'd be happy to
