### ISSUE TITLE
How to access packages programmatically from an Elixir based platform?

### ISSUE THREAD

**Issue by n1rvana** [hexpm/hex#121]
Greetings.

Working on something with its own build environment. I'd like to be able to parse the mix file and pull hex packages into my environment, without running hex on the local machine.  

So, you could say this is a request for access to the package URL within the Hex.pm API.

Or maybe there's already a way to do it.

Since Elixir's make process does this, did go looking thru the Elixir source code and hex source code that I could find trying to figure out how the notation in mix deps is turned into a package that is installed in reps.

A pointer to the actual code that does this (does the downloading) might be all I need.

I have had two other people look to try and answer this question as well without finding it, maybe we're just a bit blind to something obvious.

Thanks!

**Comment by ericmj** [comment]
Why do you need this? You will need Hex later when compiling the project anyway.

**Comment by n1rvana** [comment]
Here's the situation: The project that we're compiling is a platform that will be running other code in the future.  We don't know what that code is, in advance, and we can't know what its dependancies will be.   Imagine an online service that lets people build web apps, where we spin up a container with an elixir vm running our project, and then we compile the code they entered in the browser and load it as a module in the running VM.  If that code is going to have dependencies on things from Hex.pm, how would we best load them?  

Currently we can compile their code within elixir ourselves, without using the elixir build system. 

Possibly a better solution would be to make a temp directory and run the elixir build process from there and then load the output of that into the running VM?

I'm aware of there being many reasons why this might be thought to be a bad idea- given certain assumptions, but there's a reason for doing this. I can't know in advance what packages will be dependencies and I do need to load them into a running system.

If you've got advice on the best way to do that, I'm all ears.

**Comment by ericmj** [comment]
Why aren't you using Mix to compile and download dependencies? It's not as easy as just downloading a few dependencies and compiling them. Mix and Hex has lots of code for handling all of this correctly. You will basically have to reimplement Mix's and Hex's dependency and compilation pipeline.

Some things that Hex and Mix does that you would have to implement yourself: dependency resolution, converging and sorting, compilation of mix, make and rebar dependencies, loading configs and starting dependencies in the right order.

This is several hundreds lines of code and the dependency resolution and converging is some of the most complicated code in Elixir.
