### ISSUE TITLE
Make sure resolution errors from resolver are unique

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#131]
The same package can be backtracked multiple times for the same reason so make sure printed errors are unique.

**Comment by ericmj** [comment]
We can also skip errors where one has a subset of requirements of another.

**Comment by arthurcolle** [comment]
How do you determine the levels? ;)

**Comment by ericmj** [comment]
I just make a guess. Starter means anyone with elixir experience can grab it. Intermediate means you need experience with the project or will need some time to understand the issue and find the proper fix. Advanced means it's a complicated task that requires more knowledge of the project code and the fix is likely not very obvious.

**Comment by montague** [comment]
> We can also skip errors where one has a subset of requirements of another.

So if we had an error message like the following: 
```
Looking up alternatives for conflicting requirements on b
    Activated version: 0.0.3
    From c v0.0.4: ~> 0.1.0
    From f v0.0.1: ~> 0.0.3
    From d v0.0.1: ~> 0.0.2
```

We don't want to display the last line because `~> 0.0.2` is a subset of `~> 0.0.3` (the line above). Is that right?

**Comment by ericmj** [comment]
No, that information is still useful when fixing the resolution error.

If we have

```
Looking up alternatives for conflicting requirements on b
    Activated version: 0.0.3
    From c v0.0.4: ~> 0.1.0
    From d v0.0.1: ~> 0.0.2
```

and

```
Looking up alternatives for conflicting requirements on b
    Activated version: 0.0.3
    From c v0.0.4: ~> 0.1.0
    From f v0.0.1: ~> 0.0.3
    From d v0.0.1: ~> 0.0.2
```

then we will only show the latter because the first one is a strict subset and doesn't add any information more than the latter.

**Comment by montague** [comment]
gotcha. i reread and realized i reversed the versions-- ~> 0.0.3 is subset of ~> 0.0.2. how would you test this?

**Comment by ericmj** [comment]
I'm not testing this because it's very complicated to set up a test case that can reliably produce resolution errors like this.
