### ISSUE TITLE
Cancelling `hex publish` will still create package

### ISSUE THREAD

**Issue by remiq** [hexpm/hex#132]
I did following:

    $ rebar3 hex publish
    Publishing jsonrpc2 0.9.2
      Dependencies:
        
      Excluded dependencies (not part of the Hex package):
        
      Included files:
        src/jsonrpc2.app.src
        src/jsonrpc2.erl
        src/jsonrpc2_client.erl
        rebar.config
        README.md
        LICENSE
    Proceed? ("Y")> n
    Goodbye...

Empty package was created: https://hex.pm/packages/jsonrpc2

**Comment by josevalim** [comment]
You should report this to rebar3. :)

**Comment by ericmj** [comment]
Please report to https://github.com/hexpm/rebar3_hex
