### ISSUE TITLE
Missing Hex registry file has incorrect warning

### ISSUE THREAD

**Issue by eproxus** [hexpm/hex#133]
https://github.com/hexpm/hex/blob/master/lib/hex/remote_converger.ex#L64

The `if` should probably have it's `do` and `else` blocks switched. Also, it would be nice if the error from `open()` would be printed in the "Failed to open..." case.

**Comment by ericmj** [comment]
Thanks for the report. Please send a PR if possible, otherwise I will fix this towards the weekend.

**Comment by eproxus** [comment]
Haven't had time to do that yet, so I thought I'd fire of an issue first. I can do it next week, if you want.

**Comment by andreaazzini** [comment]
I can take this
