### ISSUE TITLE
Migrate from :contributors to :maintainers in metadata

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#138]
* [x] Update specification
* [x] Support `:maintainers` in API and translate from `:contributors`
* [x] Update website
* [x] Update Hex to new API (also update documentation)
* [x] Update rebar3 to new API (also update documentation)
* [ ] 1 month grace period
* [ ] Convert existing package tarballs and database metadata (also update API docs)

**Comment by ericmj** [comment]
We shouldn't convert existing packages since clients have started to add the package checksum to the lock.
