### ISSUE TITLE
mix  hex.info fails with Elixir 1.0.5 

### ISSUE THREAD

**Issue by sumudhar** [hexpm/hex#140]
Hi , 

I have installed elixir 1.0.5. Details are as follows. 

inentirupmm1:Desktop tirupm$ brew list elixir
/usr/local/Cellar/elixir/1.0.5/bin/elixir
/usr/local/Cellar/elixir/1.0.5/bin/elixirc
/usr/local/Cellar/elixir/1.0.5/bin/iex
/usr/local/Cellar/elixir/1.0.5/bin/mix
/usr/local/Cellar/elixir/1.0.5/lib/eex/ (7 files)
/usr/local/Cellar/elixir/1.0.5/lib/elixir/ (200 files)
/usr/local/Cellar/elixir/1.0.5/lib/ex_unit/ (21 files)
/usr/local/Cellar/elixir/1.0.5/lib/iex/ (13 files)
/usr/local/Cellar/elixir/1.0.5/lib/logger/ (10 files)
/usr/local/Cellar/elixir/1.0.5/lib/mix/ (71 files)

Hex details are like this :+1: 

inentirupmm1:Desktop tirupm$ mix hex.info
Hex v0.8.3

Registry update failed (http_error)

12:16:25.955 [error] SSL: :certify: ssl_handshake.erl:1401:Fatal error: unknown ca

{:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [:inet], {:tls_alert, 'unknown ca'}}]}
** (MatchError) no match of right hand side value: :error
    lib/hex/registry.ex:129: Hex.Registry.get_tid/0
    lib/hex/registry.ex:72: Hex.Registry.stat/0
    lib/mix/tasks/hex/info.ex:43: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2

**Comment by jcspencer** [comment]
@sumudha is your machine running behind a proxy that intercepts SSL? This has bee

Could you try upgrading to hex 0.9.0 by running `mix local.hex`, then attach the output of `HEX_UNSAFE_HTTPS=true mix hex.info`?

**Comment by ericmj** [comment]
Closing this until we get more information.
