### ISSUE TITLE
`mix hex.build` fails with `(FunctionClauseError) no function clause matching` on hex 0.9.0

### ISSUE THREAD

**Issue by parroty** [hexpm/hex#143]
Hi. I'm facing the following error when running `mix hex.build` or `mix hex.publish` after upgrading hex to v0.9.0. I could publish (`mix hex.publish`) the package if I downgraded the hex to v0.8.3, but I haven't been able to find out the root cause. Is there any idea?

```shell
% mix hex.info
Hex v0.9.0
...
% mix hex.build
Building excoveralls v0.4.0
  Dependencies:
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.Hex.Build.print_info/3
    (hex) lib/mix/hex/build.ex:30: anonymous fn({:exjsx, %{requirement: "~> 3.0", app: :exjsx, optional: false}}) in Mix.Hex.Build.print_info/3
    (elixir) lib/enum.ex:585: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1261: :lists.foldl/3
    (elixir) lib/enum.ex:584: Enum.each/2
    (hex) lib/mix/hex/build.ex:30: Mix.Hex.Build.print_info/3
    (hex) lib/mix/tasks/hex/build.ex:76: Mix.Tasks.Hex.Build.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```

- `mix.exs` is,
    - https://github.com/parroty/excoveralls/blob/master/mix.exs
- Elixir environment is,
```shell
% elixir -v
Elixir 1.1.1
% erl -v
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
```

**Comment by ericmj** [comment]
I can reproduce on OTP17 but not OTP18 so it may be an OTP bug. I will investigate more, but you can use OTP18 if you want to avoid the issue.

**Comment by parroty** [comment]
Thanks for checking. I could avoid the error by upgrading to `Erlang/OTP 18 [erts-7.1]` as you indicated.

**Comment by MonkeyIsNull** [comment]
Ouch, besides upgrading to 18, is there a work around?

**Comment by ericmj** [comment]
@MonkeyIsNull do you have the issue? It should be fixed.

**Comment by MonkeyIsNull** [comment]
Sure do, here's my system info:
$ mix hex.info                                                                                  
Hex v0.9.0

$ mix hex.publish                                                                       
publishing reddhl v0.0.2
  Dependencies:
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.Hex.Build.print_info/3
    (hex) lib/mix/hex/build.ex:30: anonymous fn({:httpoison, %{requirement: "~> 0.6", app: :httpoison, optional: false}}) in Mix.Hex.Build.print_info/3
    (elixir) lib/enum.ex:585: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1261: :lists.foldl/3
    (elixir) lib/enum.ex:584: Enum.each/2
    (hex) lib/mix/hex/build.ex:30: Mix.Hex.Build.print_info/3
    (hex) lib/mix/tasks/hex/publish.ex:94: Mix.Tasks.Hex.Publish.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
