### ISSUE TITLE
Hex 0.9.0 doesn't read http_proxy

### ISSUE THREAD

**Issue by wrachwal** [hexpm/hex#144]
When I am behind a firewall (at work) and have `http_proxy/https_proxy` set, `deps.get` hangs on downloading hex based apps.

```
$ mix deps.get
Registry update failed (http_error)
{:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [:inet], :etimedout}]}
Running dependency resolution
* Getting gproc (Hex package)
Checking package (https://s3.amazonaws.com/s3.hex.pm/tarballs/gproc-0.3.1.tar)
^C
```

Git https repos are fetched just fine. Similarly no problems with `curl -O https://s3.amazonaws.com/s3.hex.pm/tarballs/gproc-0.3.1.tar`

Recently I had to upgrade hex to v0.9.0

I cloned Hex and noticed in commits following 0.9.0 tag the additions related to proxies... so I did `mix install` and found it works.

If confirmed:
* Please release ASAP
* Consider to provide an option to install earlier releases (unless there is such)

**Comment by ericmj** [comment]
We are not planning to release right now. You can run `mix archive.install https://s3.amazonaws.com/s3.hex.pm/installs/1.0.0/hex-0.8.3.ez` to install older versions or clone and install with `mix install`. Keep in mind that those installations will not be signature verified.
