### ISSUE TITLE
Add hex.owner task for listing all packages current user own

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#147]

**Comment by fteem** [comment]
I'd like to take a try at this. Free to take?

**Comment by ericmj** [comment]
Go for it!

**Comment by fteem** [comment]
@ericmj I did a bit of reading in the codebase (and the API docs on Apiary) and it seems that there's no way to pull this off with the current endpoints. I think that we need a new endpoint in the API (something like ```GET /api/users/<username>/packages```), or am I mistaken?

**Comment by ericmj** [comment]
Ah. Didn't think of that. I think it would be easier to add a list of owned packages to the `GET /api/users/<username>` endpoint.

**Comment by fteem** [comment]
Sure, that will work too.

**Comment by ericmj** [comment]
This is ready on the server side now.

**Comment by fteem** [comment]
@ericmj I'll tackle the task as well.

**Comment by fteem** [comment]
This can be closed now. Thanks for the help/reviews @ericmj! :)
