### ISSUE TITLE
Cert stubs are expired (part/all?)

### ISSUE THREAD

**Issue by styx** [hexpm/hex#149]
```
1) test succeeds to validate with partial chain that is correct (Hex.API.ValidateCertTest)
     test/hex/api/validate_cert_test.exs:88
     match (=) failed
     code: {:ok, _} = run_validation([amazon_cert, verisign_g3, verisigng5], partial_chain_fun)
     rhs:  {:error, {:bad_cert, :cert_expired}}
     stacktrace:
       test/hex/api/validate_cert_test.exs:90
```

If someone can direct me and show where to get new certs and how to check the dates for current, then I'd be happy to fix this issue.

**Comment by ericmj** [comment]
I don't know how to fix this right now, looking into it. If you find anything out about how to fix it please let me know or send a PR.

**Comment by ericmj** [comment]
Closing because there is an open PR.
