### ISSUE TITLE
how to manage forked repositories using hex

### ISSUE THREAD

**Issue by benoitc** [hexpm/hex#150]
Using hex packages is very useful with rebar3, but sometimes you need to fork a repository and you may wait a long time to merge the changes upstream. 

Right now the package name is based on the application name. So if I ever wanted to add it to hex I also need to change the application name. You can of course use a branch for it but then once the changes have been merged upstream you need to change the application name in your releases later.

I propose to include an optional "package_name" metadata to override the default package_name instead. Which would make it easy later to reuse the upstream package and mark the old one as obsolete. Thoughts?

**Comment by josevalim** [comment]
This already works afaik. It just happens, as you said, that the application name is often the package name. In Mix, you can do:

    {:hackney, hex: :my_fork_hackney}

I remember discussing this with rebar3 folks, please ping them and see if it is supported in rebar3.

**Comment by benoitc** [comment]
closing the ticket. Opened a new one at hexpm/rebar3_hex#21since it's a feature to addd to rebar3_hex. Thanks for your answer anyway!
