### ISSUE TITLE
http_proxy not being applied

### ISSUE THREAD

**Issue by paulCarew** [hexpm/hex#151]
It doesn't look like hex is taking into account the system http proxy options.

    #env | grep http
    http_proxy=http://192.168.0.2:8080
    https_proxy=http://192.168.0.2:8080

    #mix hex.info
    Hex v0.9.0
    
    Registry update failed (http_error)
    {:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [:inet], :etimedout}]}
     ** (File.Error) could not read file stats /root/.hex/registry.ets: no such file or directory
    (elixir) lib/file.ex:288: File.stat!/2
    (hex) lib/mix/tasks/hex/info.ex:42: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

   `#elixir -e ":inets_trace.enable(:max, 'trace.txt', :httpc)" -S mix deps.get`

gives:

    [inets httpc trace 80 <0.88.0> 2015:11:04 21:06:54 4678] set options
       Content: [{module,httpc},
                 {line,234},
                 {options,[{max_sessions,4},
                           {max_keep_alive_length,4},
                           {keep_alive_timeout,120000},
                           {max_pipeline_length,4},
                           {pipeline_timeout,60000}]},
                 {profile,hex}]
    [inets httpc trace 40 <0.89.0> 2015:11:04 21:06:54 4678] set options
       Content: [{module,httpc_manager},
                 {line,542},
                 {options,[{max_sessions,4},
                           {max_keep_alive_length,4},
                           {keep_alive_timeout,120000},
                           {max_pipeline_length,4},
                           {pipeline_timeout,60000}]},
                 {old_options,{options,{undefined,[]},
                                       {undefined,[]},
                                       0,2,5,120000,2,disabled,false,inet,default,
                                       default,[]}}]

Ultimately the request fails with:

    [inets httpc trace 40 <0.95.0> 2015:11:04 21:09:02 4621] init error
        Content: [{module,httpc_handler},
             {line,655},
             {tag,error_connecting},
             {client_error,
                 {#Ref<0.0.1.112>,
                  {error,
                      {failed_connect,
                          [{to_address,{"s3.amazonaws.com",443}},
                           {inet,[inet],etimedout}]}}}}]

Any suggestions on how to resolve this would be appreciated. Setting HTTPS_PROXY and HTTP_PROXY doesn't seem to make any difference. Likewise `mix hex.config https_proxy http://192.168.0.2:8080` doesn't seem to work either.

Thanks.

**Comment by ericmj** [comment]
There have been some changes around proxies in master. Can you try master and check if you still have the issue? You can install master by cloning this repo and running `mix install` inside the cloned directory. Run `mix local.hex` to install stable again.

**Comment by paulCarew** [comment]
Confirmed fixed in 0.9.1-dev.

Thank you.
