### ISSUE TITLE
Suggest adding ex_doc if docs task is missing when running hex.docs

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#155]
If the user gets the error `** (Mix) The task "docs" could not be found` we should suggest adding ex_doc to the dependencies.

**Comment by fteem** [comment]
This seems quite small, I can do it quickly. What should the message look like?

**Comment by ericmj** [comment]
We should check with `Mix.Task.get/1` if the task is available otherwise we should raise something like: "The "docs" task is unavailable, add {:ex_doc, ">= 0.0.0", only: [:dev]} to your dependencies or if ex_doc already added make sure you run the task in the same environment it is available in." Does that sound good?

**Comment by fteem** [comment]
Yeah, looks good.

**Comment by fteem** [comment]
This can be closed, it was done in: https://github.com/hexpm/hex/pull/156
