### ISSUE TITLE
add icon or extensions to the package metadata

### ISSUE THREAD

**Issue by benoitc** [hexpm/hex#157]
Would be interesting to add an icon or having a way to extend the package metadata so it could be used in some packing facilities.

**Comment by ericmj** [comment]
Like a logo for the package?

**Comment by benoitc** [comment]
yes?

**Comment by ericmj** [comment]
It's low priority right now while we work on more important features. If someone really wants this functionality PRs to https://github.com/hexpm/hex_web would be appreciated.

**Comment by benoitc** [comment]
this was about having a way to extend the metadata not only having an icon.
ie it's about packaging metdata not about displaying something on a
centralized .

i would like to have this feature discussed. where the discussion should
happen if not there then?

**Comment by ericmj** [comment]
We can of course discuss it here if there is more to discuss :)

Why do you want to be able the package metadata, where should the metadata be accessible?

**Comment by benoitc** [comment]
Thanks! The main goal is to have something similar to https://www.python.org/dev/peps/pep-0426/#metadata-extensions

It would allow some distributions or even plugin in rebar/mix to have some additional published metadata for any purpose.

**Comment by ericmj** [comment]
Where should this metadata be available to access? Because if it's in the package tarball you can easily just add an extra file to the package which includes the metadata.

**Comment by ericmj** [comment]
Ping?

**Comment by benoitc** [comment]
hi r some reason i didn't get the first notification. mAybe via an API exposing them as a JSON in the API?

**Comment by ericmj** [comment]
If you want to support custom metadata it can easily be an extra file in the package that defines it. It feels wrong that Hex should support others metadata when Hex wont be using it.

**Comment by ericmj** [comment]
Closing because there has been no more updates.

**Comment by benoitc** [comment]
well i was speciically about metadata usable from the API so it can be used eventually by extra tools to provide some packages installation for example. But ok.

**Comment by ericmj** [comment]
What do you mean provide package installations?

I am okay with adding custom metadata, but I haven't seen a reasonable use case yet.

**Comment by benoitc** [comment]
I have such example in mind: for now the way dependencies are added are using an editor  adding the dependencies manually to the config (rebar or mix). But we could imagine that a tool could provide an UI to add dependencies by extracting them from the hex.pm repositories to build a custom release. 

Since we are speaking about user interface, the choice is not done yet at the user level so the program managing the user interface will have to fetch the informations needed to the user and the program without fetching the sources. Can be anything . I am thinking such metadata as public annotations to the source package exposed via the api. Can be then just a K/V + an attachement system for some (like a readme + images done in pypi).

**Comment by ericmj** [comment]
Keep in mind that the metadata would not be consistent across packages, package authors would have to add to the metadata themselves. I think in practice, because the metadata will be completely arbitrary, it would be of little use for the kind of tool you are describing.

But I am not opposed to the idea so it's up for grabs for anyone who wants to work on it but it's low priority for us currently.
