### ISSUE TITLE
suggestion: let mix hex.search return latest versions

### ISSUE THREAD

**Issue by smeevil** [hexpm/hex#158]
Hi,

It would be nice to let mix hex.search return the latest version numbers of packages.
for example:

mix hex.search https```
httpoison 0.8.0
httpotion 2.1.0
or optionally : 
```mix hex.search https --mix
{:httpoison, "~> 0.8.0"}
{:httpotion, "~> 2.1"}

and 
```mix hex.search https --rebar
{httpoison, "0.8.0"}
{httpotion, "2.1"}
Just a thought :)

**Comment by ericmj** [comment]
We are not going to support rebar definitions because this client is only used with mix. I also think the config should be added to `mix hex.info` instead.

**Comment by Baltazore** [comment]
@ericmj probably you could close this one with #160 ?

**Comment by ericmj** [comment]
@Baltazore The change to `mix hex.info` is still up for grabs.

**Comment by Baltazore** [comment]
@ericmj I could do it, how `mix hex.info` output should looks like?

**Comment by ericmj** [comment]
@Baltazore Like this: `{httpotion, "~> 2.1"}`. Example here on how to generate it: https://github.com/hexpm/hex_web/blob/86ec5b4a0878fe10b67faed7fc8ad8001dc674bd/lib/hex_web/web/html/helpers.ex#L70

**Comment by Baltazore** [comment]
@ericmj I tried to implement this in #165
