### ISSUE TITLE
can not finish mix deps.get 

### ISSUE THREAD

**Issue by hupahupa** [hexpm/hex#168]
Hi,

I ran into this issue that can not fetch dependencies via `mix deps.get`, look like it's stuck so long, and some time through out error like this

```
* Getting phoenix (Hex package)
Checking package (https://s3.amazonaws.com/s3.hex.pm/tarballs/phoenix-1.0.2.tar)
** (exit) exited in: GenServer.call(:hex_fetcher, {:await, {:phoenix, "1.0.2"}}, 60000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:544: GenServer.call/3
    (hex) lib/hex/scm.ex:86: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:163: Mix.Dep.Converger.all/8
    (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:23: Mix.Tasks.Deps.Get.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```
I don't know how to fix this, please help.

**Comment by josevalim** [comment]
If you are not in America, maybe configuring to a closer CDN would help? here is how you can do it:

Europe: `mix hex.config cdn_url https://s3-eu-west-1.amazonaws.com/s3-eu.hex.pm`
Asia: `mix hex.config cdn_url https://s3-ap-southeast-1.amazonaws.com/s3-asia.hex.pm`

**Comment by hupahupa** [comment]
Hi @josevalim, 
Thanks for replying me,

I tried to change cdn like you said, but no luck :D 

With `mix hex.config cdn_url https://s3-ap-southeast-1.amazonaws.com/s3-asia.hex.pm`

```
mix hex.config cdn_url https://s3-ap-southeast-1.amazonaws.com/s3-asia.hex.pm
mix deps.get                                                                                                                             
** (Mix) No package version in registry matches scrivener ~> 1.1 (from: mix.exs)
```

with `mix hex.config cdn_url https://s3-eu-west-1.amazonaws.com/s3-eu.hex.pm`
```
mix hex.config cdn_url https://s3-eu-west-1.amazonaws.com/s3-eu.hex.pm
cdn_url: "https://s3-eu-west-1.amazonaws.com/s3-eu.hex.pm"

mix deps.get
** (ErlangError) erlang error: :data_error
    :zlib.call/3
    :zlib.gunzip/1
    (hex) lib/hex/utils.ex:60: Hex.Utils.update_registry/1
    (hex) lib/hex/utils.ex:20: Hex.Utils.ensure_registry!/1
    (hex) lib/hex/remote_converger.ex:14: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:88: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
```

**Comment by ericmj** [comment]
@hupahupa We need some more information to be able to investigate this issue. What's your elixir and hex versions (please paste the output of `elixir -v` and `mix hex.info`)? Have you been able to download packages before, if so do you remember if anything changed on your system? Will the package download if you paste the URL into your browser?

SIDENOTE: It seems like the mirroring using AWS S3 cross-region replications is having some issues but we will be moving away from it shortly and instead use a proper CDN with region caching.

**Comment by hupahupa** [comment]
Hi All,

Sorry bother you guys, the problem because of Linode VPS can not download file from AWS :|

This was fixed. thanks

**Comment by simonh1000** [comment]
I'm getting the same sort errors quite often on my dev machine

```
mix deps.get
** (exit) exited in: GenServer.call(#PID<0.123.0>, {:versions, "jsx"}, 30000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:604: GenServer.call/3
    (hex) lib/hex/remote_converger.ex:194: Hex.RemoteConverger.check_dep/2
    (elixir) lib/enum.ex:657: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:656: Enum.each/2
    (hex) lib/hex/remote_converger.ex:39: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:89: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:50: Mix.Dep.Converger.converge/4
```

**Comment by ericmj** [comment]
@simonh1000 Check out https://github.com/hexpm/hex/issues/308.
