### ISSUE TITLE
Can't seem to revert docs

### ISSUE THREAD

**Issue by psfblair** [hexpm/hex#182]
Ran `mix hex.docs` on my exdn project and published docs for version 2.0.0 -- then found I needed to make some revisions.

Running `mix hex.docs` again did not overwrite the documentation online.

Then tried `mix hex.docs --revert 2.0.0` and `mix hex.docs --revert v2.0.0` (repeatedly). I would get the response `Reverted docs for exdn 2.0.0` but the docs were still accessible at http://hexdocs.pm/exdn/2.0.0/ .

**Comment by ericmj** [comment]
Docs are cached for a few hours at least. I get a 404 on http://hexdocs.pm/exdn/2.0.0/ so it seems the revert worked.

You can also publish a new version directly without reverting first.
