### ISSUE TITLE
Dependency resolution 

### ISSUE THREAD

**Issue by samcorcos** [hexpm/hex#186]
I can't seem to update my dependencies. I get the following message:

```
 __        _____________________________________________
/  \      /                                             \
|  |      | It looks like the dependency resolution is  |
@  @      | taking a long time to complete. You can try |
|| ||  <--| the experimental resolver by exiting with   |
|| ||     | CTRL-C + CTRL-C and running the mix task    |
|\_/|     | again with HEX_EXPERIMENTAL_RESOLVER=1 set. |
\___/     | Please report this at github.com/hexpm/hex. |
          \_____________________________________________/
```

I tried with the experimental resolver and that does not work either.

I am reporting as instructed by the error message.

Also, worth noting, beam is taking up nearly all my CPU while attempting to get the dependencies.

**Comment by josevalim** [comment]
Can you provide your `mix.exs` and how you are running `mix deps.get` with the experimental resolver?

**Comment by samcorcos** [comment]
@josevalim thank you for such a quick response!

I created the project with `mix phoenix.new --no-brunch project`, then fetched dependencies. It created the following `mix.exs` file:

```
defmodule Project.Mixfile do
  use Mix.Project

  def project do
    [app: :project,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {Project, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :postgrex]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.0.4"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"}]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"]]
  end
end
```

When I ran `mix deps.get`, it says `Running dependency resolution` then throws the error described above.

I then `^c ^c` and ran `HEX_EXPERIMENTAL_RESOLVER=1`, which after I run `echo $HEX_EXPERIMENTAL_RESOLVER` returns `1`. When I run `mix deps.get`, I get the same error.

**Comment by samcorcos** [comment]
I also tried updating hex, but that didn't solve it.

```
$ mix local.hex
Found existing archive(s): hex-0.10.2.ez.
Are you sure you want to replace them? [Yn] y
* creating /Users/username/.mix/archives/hex-0.10.2.ez
```

**Comment by josevalim** [comment]
Cool. We will investigate, thank you! Btw, you should update your phoenix.new package. You are using 1.0.4 and 1.1.2 is out.

**Comment by samcorcos** [comment]
Changing to `1.1.2` solved it :smile: I just changed it in the `mix.exs` file.

How do I ensure that `mix phoenix.new` is up to date? Is there a `brew upgrade` equivalent?

**Comment by josevalim** [comment]
No other option for now besides running `archive.install` again. I am reopening this so we can investigate the slow down still.

**Comment by josevalim** [comment]
Closing this as the command above is fast on elixir v1.2 and latest hex. :D

**Comment by samcorcos** [comment]
Sounds good :+1: 

Just to clarify, `mix archive.install` requires a path. Is there no default path set up?

**Comment by josevalim** [comment]
You need to use the latest path, yeah.

On Friday, January 22, 2016, Sam Corcos <notifications@github.com> wrote:

> Sounds good [image: :+1:]
>
> Just to clarify, mix archive.install requires a path. Is there no default
> path set up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex/issues/186#issuecomment-174065157>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
I am guessing that the environment variable was not correctly set because you should not get the clippy message when using the experimental resolver. Did you remember to export it? Thanks for reporting.

**Comment by samcorcos** [comment]
@ericmj Perhaps you are right. I just downgraded back to 1.0.4 to check it out. I ran:

```
$ export HEX_EXPERIMENTAL_RESOLVER=1
```
Then to make sure it worked...
```
$ echo $HEX_EXPERIMENTAL_RESOLVER 
1
```

And when I ran it with the experimental resolver, it worked. So it would appear I am no longer able to replicate the error :disappointed: Perhaps it was just a problem with the `export`.
