### ISSUE TITLE
mix deps.get hung

### ISSUE THREAD

**Issue by arvindhiman** [hexpm/hex#189]
I created a new app using mix phoenix.new myapp and it is hung at mix deps.get.

I cancelled it and tried with mix deps.get in myapp folder. It is suggesting to run with HEX_EXPERIMENTAL_RESOLVER=1. I am quite new to mix and not sure how to run it with this setting. 

Following are the versions that I have installed:

Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.2.0
hex-0.10.3.ez

I appreciate if you could point me to some resources that I can use to troubleshoot this issue.

Thank you.

**Comment by arvindhiman** [comment]
I tried it again and it is working now. All dependencies have been downloaded. 

I am not sure why it was not working earlier. Could it be some kind of network issue? Can you suggest what would be good next step in such situation to understand what is causing this issue?

thanks.

**Comment by nordbit** [comment]
I'm fighting for 5 hours with hanged mix after upgarde to newest version. Simply hangs and do nothing.
As arvindhiman says - only asciiart with " It looks like the dependency resolution is taking a long time to complete.."

**Comment by josevalim** [comment]
If the clippy appears, you should run it as:

    HEX_EXPERIMENTAL_RESOLVER=1 mix deps.get

Does it still hang? If so, can you please put your `mix.exs` in a file and paste it here?

**Comment by nordbit** [comment]
Still .No idea why?

```
  defmodule Felix.Mixfile do
  use Mix.Project

  def project do
    [app: :felix,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {Felix, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :arc, :arc_ecto]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.1.3"},
     {:phoenix_ecto, "~> 2.0"},
     {:postgrex, "0.10.0"},
     {:phoenix_html, "~> 2.3"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:arc, "~> 0.2.3"},
     {:arc_ecto, "~> 0.3.1"},
     {:addict, "~> 0.0.1"}]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"]]
  end
end
```
and yes, i tried HEX_EXPERIMENTAL_RESOLVER=1 mix deps.get with same effect

**Comment by josevalim** [comment]
What does `mix hex.info` return?

**Comment by nordbit** [comment]
Hex:    0.10.3
Elixir: 1.2.1
OTP:    18.2

Built with: Elixir 1.2.1 and OTP 18.2.2

**Comment by ericmj** [comment]
This seems to be fixed on master. You can try cloning this project and run `mix install` to install master, then run `HEX_EXPERIMENTAL_RESOLVER=1 mix deps.get`.

**Comment by josevalim** [comment]
@nordbit indeed this is not working as expected. You can follow @ericmj's suggestion or you can just copy the contents below into a `mix.lock` file and run `mix deps.get`:

```elixir
%{"addict": {:hex, :addict, "0.0.5"},
  "arc": {:hex, :arc, "0.2.3"},
  "arc_ecto": {:hex, :arc_ecto, "0.3.1"},
  "comeonin": {:hex, :comeonin, "0.11.3"},
  "connection": {:hex, :connection, "1.0.2"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "decimal": {:hex, :decimal, "1.1.1"},
  "ecto": {:hex, :ecto, "1.1.2"},
  "fs": {:hex, :fs, "0.9.2"},
  "gettext": {:hex, :gettext, "0.9.0"},
  "mailgun": {:hex, :mailgun, "0.0.2"},
  "phoenix": {:hex, :phoenix, "1.1.3"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "2.0.1"},
  "phoenix_html": {:hex, :phoenix_html, "2.4.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.3"},
  "plug": {:hex, :plug, "1.1.0"},
  "poison": {:hex, :poison, "1.5.2"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.10.0"},
  "ranch": {:hex, :ranch, "1.2.1"}}
```

Sorry that you ran into this :)

**Comment by nordbit** [comment]
It's working now.
Thx for help.
I have great expectations for Elixir and Phoenix.
