### ISSUE TITLE
Proposal: mix hex.outdated: return exit status 0 when all latest, 1 otherwise

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#208]
This is useful for tooling, e.g. CI can have a build step that fails when there're some outdated packages.

Let me know if this is something you'd consider and I'm happy to take a stab at implementing it.

**Comment by josevalim** [comment]
I am a :-1: only because I think this is a bad practice. Folks should not be concerned with running on the latest and making build fails because of this sounds a bit too much to me. :)

**Comment by ericmj** [comment]
I agree with José.
