### ISSUE TITLE
mix hex.outdated should restrict its results to compatible elixir versions

### ISSUE THREAD

**Issue by phanimahesh** [hexpm/hex#215]
Ref: https://github.com/hexpm/hex_web/issues/266

The title says it all. I want to know if there are updates to a package that I can pull in without having to migrate to a new elixir version. A short note at the end can indicate if there are more updates that have been filtered out due to incompatible elixir version, offering a command line flag to include them as well.

**Comment by ericmj** [comment]
Closing this until we have plan for this in the specification and hex_web. Feel free to reopen when we are ready to discuss and work on this. Thank you @phanimahesh!
