### ISSUE TITLE
Add package checksum to lock

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#216]

**Comment by ericmj** [comment]
This would stop the build if the locked checksum does not match the checksum of the package from the hex repository.

**Comment by enilsen16** [comment]
I plan to take a stab at this over the weekend. Is there any kind of checksum verification already in place for package integrity? If I understand correctly, you'd like to compare a locally-cached checksum in the .lock file with the corresponding checksum for the package on the server and terminate the build if they don't match. If that's correct, it would suggest the packages in the repository have checksums available, is this accurate?

**Comment by ericmj** [comment]
@enilsen16 That's awesome. The current check is here https://github.com/hexpm/hex/blob/master/lib/hex/tar.ex#L84-L103. It does the following comparision:

```
checksum reported from tarball <=> actual tarball checksum <=> checksum reported from registry
```

You should be able to pass the checksum from the lock https://github.com/hexpm/hex/blob/master/lib/hex/scm.ex#L79  into this function https://github.com/hexpm/hex/blob/master/lib/hex/scm.ex#L104 and add an extra checksum with a good error message.

**Comment by ericmj** [comment]
This is in master now.
