### ISSUE TITLE
Consider encypting the locally stored API key with user password

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#219]

**Comment by jcspencer** [comment]
I've created a basic implementation of this [here](https://gist.github.com/jcspencer/19935a4b07a7382cb4483415138bf24e). It creates a key hashing the password (sha256), and then encrypts the unpadded key using AES CBC-128 encryption.

Then, wherever we retrieve the key in Hex, we must decrypt it using the password first.

**Comment by ericmj** [comment]
Looks good, the code in the gist crashes for me though. I have an scrypt implementation [1] that can be used as hash function to guard against rainbow table attacks.

[1] https://github.com/ericmj/triple_sec

**Comment by jcspencer** [comment]
Currently the code will crashes because it does not pad each block into 16 bytes. However, because an API key has a length that is a factor of 16, it works correctly, surprisingly!

That's a great implementation! Can we bring it in as a dependency, or do we need to copy code?

**Comment by jcspencer** [comment]
Also, what would we use as an appropriate salt to pass to scrypt?

**Comment by ericmj** [comment]
Need to copy the code, the salt would need to be generated and stored.

**Comment by jcspencer** [comment]
Would it also need to be encrypted?

**Comment by ericmj** [comment]
No, that's not needed.

**Comment by jcspencer** [comment]
One more question: Are we able to bring in triple_sec as a mix dependency?

**Comment by ericmj** [comment]
No, the code we need should be copied.

**Comment by jcspencer** [comment]
Hi Eric,

I've got a working implementation working locally. Is it correct to rewrite Hex.Utils.auth_info to prompt for a password before returning they key?

**Comment by ericmj** [comment]
Yes, I think that should work. We should also prompt the user to chose a password if the key is not currently encrypted.

**Comment by jcspencer** [comment]
Could we use the password they supply when they generate a key to encrypt it, or use a different password? 

On 14 April 2016 10:46:25 AM AEST, "Eric Meadows-Jönsson" <notifications@github.com> wrote:
>Yes, I think that should work. We should also prompt the user to chose
>a password if the key is not currently encrypted.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex/issues/219#issuecomment-209702704

-- 
James Spencer

**Comment by ericmj** [comment]
We could, but that means we should invalidate the current (unencrypted) key and generate a new one. And of course notify the user that we are doing so.

**Comment by jcspencer** [comment]
But if the encryption occurs by default, the key will have been encrypted before it is persisted to disk

On 15 April 2016 2:04:54 AM AEST, "Eric Meadows-Jönsson" <notifications@github.com> wrote:
>We could, but that means we should invalidate the current (unencrypted)
>key and generate a new one. And of course notify the user that we are
>doing so.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex/issues/219#issuecomment-210020651

-- 
James Spencer

**Comment by ericmj** [comment]
Not sure what you mean? Currently keys are not encrypted, so until everyone migrates to the encryption, keys would still be unencrypted.

The only way to force users to use the same password they have for their Hex account is to have them generate a new key when we encrypt for the first time. Otherwise they can chose any random password.

**Comment by ericmj** [comment]
@jcspencer Ping? Do you have any code to share on this?

**Comment by ericmj** [comment]
Ping?

**Comment by jcspencer** [comment]
I'm really sorry, I completely forgot about this issue. I'll look at your PR now!

**Comment by ericmj** [comment]
No worries @jcspencer. Thanks for the review.
