### ISSUE TITLE
mix hex.info fails after upgrading to elixir 0.14.0

### ISSUE THREAD

**Issue by rambocoder** [hexpm/hex#22]
There was an initial issue even running: mix deps.get when pulling from hex.pm. So I decided to just look at hex...

```
$mix hex.info
Hex v0.2.4

Registry update failed (http_error)
:timeout
** (MatchError) no match of right hand side value: :undefined
    lib/hex/registry.ex:114: Hex.Registry.get_tid/0
    lib/hex/registry.ex:64: Hex.Registry.stat/0
    lib/mix/tasks/hex/info.ex:41: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/cli.ex:66: Mix.CLI.run_task/2
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) lib/code.ex:296: Code.require_file/2
```

And I fixed it by running:

```
mix local.hex
Found existing archives: hex.ez.
Are you sure you want to replace them? [Yn] 
* creating /home/alex/.mix/archives/hex.ez
```

And it works now:

```
mix hex.info
Hex v0.2.4

Registry file available (last updated: 2014-06-13 13:37:51)
Size: 15kB
Packages #: 66
Versions #: 182
```

Do you know what could of caused the problem?

**Comment by sumudhar** [comment]
Hi , 

I am new to Elixir. I tried to install the hex. I am getting this error with mix hex.info 

inentirupmm1:Desktop tirupm$ mix hex.info
Hex v0.8.3

Registry update failed (http_error)

12:05:41.613 [error] SSL: :certify: ssl_handshake.erl:1401:Fatal error: unknown ca

{:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [:inet], {:tls_alert, 'unknown ca'}}]}
** (MatchError) no match of right hand side value: :error
    lib/hex/registry.ex:129: Hex.Registry.get_tid/0
    lib/hex/registry.ex:72: Hex.Registry.stat/0
    lib/mix/tasks/hex/info.ex:43: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2

My elixir Information is like this:  
inentirupmm1:Desktop tirupm$ brew list elixir
/usr/local/Cellar/elixir/1.0.5/bin/elixir
/usr/local/Cellar/elixir/1.0.5/bin/elixirc
/usr/local/Cellar/elixir/1.0.5/bin/iex
/usr/local/Cellar/elixir/1.0.5/bin/mix
/usr/local/Cellar/elixir/1.0.5/lib/eex/ (7 files)
/usr/local/Cellar/elixir/1.0.5/lib/elixir/ (200 files)
/usr/local/Cellar/elixir/1.0.5/lib/ex_unit/ (21 files)
/usr/local/Cellar/elixir/1.0.5/lib/iex/ (13 files)
/usr/local/Cellar/elixir/1.0.5/lib/logger/ (10 files)
/usr/local/Cellar/elixir/1.0.5/lib/mix/ (71 files)


Please tell me how to fix this issue.

**Comment by ericmj** [comment]
Do you have a proxy that rewrites certificates or the connection?

**Comment by sumudhar** [comment]
I had connection.

**Comment by sumudhar** [comment]
inentirupmm1:hex-master tirupm$ mix hex.info 
Hex v0.9.0-dev

Registry update failed (http_error)

09:40:27.665 [error] SSL: :certify: ssl_handshake.erl:1401:Fatal error: unknown ca

{:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [:inet], {:tls_alert, 'unknown ca'}}]}
** (ArgumentError) argument error
    (stdlib) :ets.safe_fixtable(nil, true)
    (stdlib) ets.erl:526: :ets.foldl/3
    (hex) lib/mix/tasks/hex/info.ex:43: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2

**Comment by ericmj** [comment]
What is your elixir and OTP version?

You can see it by running `iex`.

**Comment by sumudhar** [comment]
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)

**Comment by ericmj** [comment]
Sorry, I don't know what's wrong. Seems like something is changing the certificate for s3.amazonaws.com.
