### ISSUE TITLE
error in lib/hex/version.ex when parsing custom requirement

### ISSUE THREAD

**Issue by kanatohodets** [hexpm/hex#231]
After chatting with Licenser about https://github.com/elixir-lang/elixir/issues/4619, he proposed pulling `riak_core_ng` from git, instead of the hex package (as that will not be updated until `riak_core` publishes a new version). When I tried this, I ran into (what looks like) an error in Hex (stack trace/details below).

### Environment
OS: Mac OSX Yosemite 10.10.5
Mix/Hex details:
```
$ mix --version
Mix 1.2.4
$ mix hex.info
Hex:    0.12.0
Elixir: 1.2.4
OTP:    18.3

Built with: Elixir 1.2.5 and OTP 18.3.3

Registry file available (last updated: 2016-05-20 14:57:37)
File size:   2058kB (compressed 672kb)
Memory size: 5524kB
Fetch time:  428ms
Load time:   35ms
Packages #:  2121
Versions #:  9425
$
```

### Current behavior
Given a `mix.exs` with a `deps` section like so: 
```
  defp deps do
    [
      {:riak_core, "~> 2.2", git: "https://github.com/project-fifo/riak_core.git", branch: "fifo-0.8.2"}
    ]
  end
```
Running `mix deps.get` gives the following output:

	$ mix deps.get
	* Getting riak_core (https://github.com/project-fifo/riak_core.git)
	Cloning into '/Users/btyler/personal/prog/elixir/repos/ricor_from_git/deps/riak_core'...
	remote: Counting objects: 16398, done.
	remote: Compressing objects: 100% (8/8), done.
	remote: Total 16398 (delta 3), reused 0 (delta 0), pack-reused 16390
	Receiving objects: 100% (16398/16398), 10.27 MiB | 5.95 MiB/s, done.
	Resolving deltas: 100% (10222/10222), done.
	Checking connectivity... done.
	** (FunctionClauseError) no function clause matching in String.split/3
		(elixir) lib/string.ex:334: String.split(~r/0.8.1-p3/, " ", [trim: true])
		(hex) lib/hex/version.ex:108: Hex.Version.custom_requirement/1
		(hex) lib/hex/version.ex:83: Hex.Version.cache/2
		(hex) lib/hex/remote_converger.ex:115: Hex.RemoteConverger.check_package_req/3
		(elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
		(elixir) lib/enum.ex:604: Enum.each/2
		(hex) lib/hex/remote_converger.ex:104: Hex.RemoteConverger.check_input/2
		(hex) lib/hex/remote_converger.ex:29: Hex.RemoteConverger.converge/2

This repo has an example mix.exs for reproduction: https://github.com/kanatohodets/riak_core_from_git_issue

### Expected behavior

Assuming I have correctly specified the dependency in `mix.exs`, I expect to be able to pull `riak_core_ng` from git.

### Other info

The line that breaks seems to have an invalid call of `String.split`, with the pattern as the first argument instead of the second.

The input that causes this behavior is the version specification for `basho_poolboy`, as seen in `riak_core_ng`'s `rebar.config`, here: https://github.com/project-fifo/riak_core/blob/fifo-0.8.2/rebar.config#L20

Thanks! Feel free to grab me on freenode if a conversation would be fruitful: I'm "btyler" there, usually lurking in #elixir-lang and #erlang.

**Comment by ericmj** [comment]
It should be fixed in this commit https://github.com/elixir-lang/elixir/commit/ecf419e19b4426d0e938d90241504061b5416871. Please check if elixir master works.

**Comment by kanatohodets** [comment]
Yes! I successfully fetched and compiled riak_core without any tinkering using Elixir master.
