### ISSUE TITLE
Doesn't know how to compare x.x.x-rc

### ISSUE THREAD

**Issue by kyledecot** [hexpm/hex#232]
When attempting to use `ja_serializer` and the `ecto` release candidate I ran into the following error:

```
Failed to use "ecto" because
  ja_serializer (version 0.9.0) requires > 1.0.0
  Locked to 2.0.0-rc.5 in your mix.lock

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)
```

Here is the output of `mix hex.info` for debug purposes:

```
mix hex.info  
Hex:    0.12.0
Elixir: 1.2.5
OTP:    18.3

Built with: Elixir 1.2.5 and OTP 18.3.3
```

My short term fix for this has simply been to override the version of ecto I'm using:

    {:ecto, "2.0.0-rc.5", override: true},

**Comment by josevalim** [comment]
You need to explicitly opt-in into release candidates. Please specify Exto
in your mix.exs and give the override flag.

Eric, should we improve the error message to mention overrides?

On Wednesday, May 25, 2016, Kyle Decot <notifications@github.com> wrote:

> When attempting to use ja_serializer and the ecto release candidate I ran
> into the following error:
>
> Failed to use "ecto" because
>   ja_serializer (version 0.9.0) requires > 1.0.0
>   Locked to 2.0.0-rc.5 in your mix.lock
>
> ** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)
>
> Here is the output of mix hex.info for debug purposes:
>
> mix hex.info
> Hex:    0.12.0
> Elixir: 1.2.5
> OTP:    18.3
>
> Built with: Elixir 1.2.5 and OTP 18.3.3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex/issues/232>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
Yes. We should also try to find a nice way to explain RC opt-in.

**Comment by ericmj** [comment]
@josevalim Do you want to grab this?
