### ISSUE TITLE
Can not authenticate user account

### ISSUE THREAD

**Issue by belaustegui** [hexpm/hex#235]
I was trying to create a user account to publish a package in Hex.pm. Unfortunately I received a `FunctionClauseError` while running `mix hex.user register`. Since I received the activation mail, I tried to authenticate myself by using `mix hex.user auth`, but I am getting the same error.

```
mix hex.user auth
Username: crbelaus
Password: 
Generating API key...
** (FunctionClauseError) no function clause matching in Access.fetch/2
    (elixir) lib/access.ex:118: Access.fetch(<<131, 116, 0, 0, 0, 5, 109, 0, 0, 0, 11, 105, 110, 115, 101, 114, 116, 101, 100, 95, 97, 116, 109, 0, 0, 0, 26, 50, 48, 49, 54, 45, 48, 54, 45, 48, 51, 84, 49, 57, 58, 53, 48, 58, 53, 56, 46, 48, 49, 50, ...>>, "secret")
    (elixir) lib/access.ex:150: Access.get/3
    (hex) lib/mix/hex/utils.ex:9: Mix.Hex.Utils.generate_key/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I am using the following versions of Erlang and Elixir:
```
cat .tool-versions 
erlang 18.3
elixir 1.2.5
```

**Comment by ericmj** [comment]
Thank you for letting us know. Fixed in https://github.com/hexpm/hex_web/commit/20fb066adf962bd5c18ec5a171e1e0a46836099a.

**Comment by belaustegui** [comment]
Wow, that was fast! Thanks!! :raised_hands:
