### ISSUE TITLE
Warn when hex may fail if fetching using SNI with a buggy `:ssl`

### ISSUE THREAD

**Issue by fishcakez** [hexpm/hex#240]

**Comment by ericmj** [comment]
The failures are for OTP 17.3 and some of the patch versions. We need to find the versions of the :ssl app where this is buggy and add an error message.

**Comment by josevalim** [comment]
Elixir v1.2 doesn't even support 17 anymore. But I guess both of you know that. :D

**Comment by ericmj** [comment]
Hex supports down to Elixir v1.0 and will continue to do that until the Hex specification is stable and Elixir v2.0 is out.

**Comment by fishcakez** [comment]
For reference here is what happens on Elixir v1.0/1.1 on 17.3: https://travis-ci.org/fishcakez/connection/jobs/138810648#L158.

**Comment by ericmj** [comment]
Currently peer verification is disabled on OTP <17.3 on the hex client. We can bump that to <17.3.3 to skip the versions with the broken SNI.

But given that 17.3 is quite old now I would rather error out on <17.3.3 with a nice error message unless users explicitly set `HEX_UNSAFE_HTTPS=1`.

WDYT? @fishcakez @josevalim

**Comment by josevalim** [comment]
Sounds OK to me!

On Tuesday, June 28, 2016, Eric Meadows-Jönsson <notifications@github.com>
wrote:

> Currently peer verification is disabled on OTP <17.3 on the hex client. We
> can bump that to <17.3.3 to skip the versions with the broken SNI.
>
> But given that 17.3 is quite old now I would rather error out on <17.3.3
> with a nice error message unless users explicitly set HEX_UNSAFE_HTTPS=1.
>
> WDYT? @fishcakez <https://github.com/fishcakez> @josevalim
> <https://github.com/josevalim>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hexpm/hex/issues/240#issuecomment-228917437>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAAlbku1S68QW7Ruapi-FB7YPfV5Q72Kks5qQG3dgaJpZM4I5yQi>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
