### ISSUE TITLE
Hex dependency resolution does not display conflicts on failure

### ISSUE THREAD

**Issue by britto** [hexpm/hex#241]
Given a blank application, when I add three conflicting dependencies, the command output does not display the conflicts to help the user with their resolution.

#### Steps to reproduce

1. Create a new application with `mix new sample_app`
2. Edit its mix file and include the following deps: `{:phoenix_html, "2.5.1"}`, `{:scrivener, "2.0.0"}` and `{:scrivener_html, "1.0.0"}`
3. Run `mix deps.get`

Command output:
```
$ mix deps.get
Running dependency resolution



** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)
```

#### Current environment

```
$ mix hex.info
Hex:    0.12.1
Elixir: 1.3.0
OTP:    18.3

Built with: Elixir 1.2.5 and OTP 18.3.3

Registry file available (last updated: 2016-06-22 14:21:45)
File size:   2246kB (compressed 734kb)
Memory size: 6024kB
Fetch time:  2130ms
Load time:   45ms
Packages #:  2269
Versions #:  10245
```

**Comment by ericmj** [comment]
Should be fixed on master. You can verify by cloning this repository and running `mix install` to install master.

**Comment by britto** [comment]
@ericmj Oh, that's great news! Yes, I can confirm it is fixed on master:

```
$ mix hex.info
Hex:    0.12.2-dev
Elixir: 1.3.0
OTP:    18.3

Built with: Elixir 1.3.0 and OTP 18.3
```
```
$ mix deps.get
Running dependency resolution

Failed to use "scrivener" (versions 1.0.0 to 1.2.1) because
  scrivener_html (version 1.0.0) requires ~> 1.0
  You specified 2.0.0 in your mix.exs

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)
```

Thank you very much ❤️
