### ISSUE TITLE
Add task for re-encrypting API key

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#249]
Thoughts on the name for this task? It should be under `mix hex.user`.  `mix hex.key` is for the server stored keys.

`mix hex.user reencrypt`
`mix hex.user secret`

/cc @josevalim

**Comment by potatosalad** [comment]
I think "passphrase" makes sense, but that might just be because I've seen it used before by ssh-keygen as mentioned in #250:

`mix hex.user passphrase`

**Comment by potatosalad** [comment]
Or, alternatively, if the locally stored api key was referred to as the "token", it might make it easier to separate what is being changed by using a different namespace:

`mix hex.token deauth`
`mix hex.token reset password`
`mix hex.token test`

**Comment by ericmj** [comment]
"passphrase" is great, lets go with that. I would like to avoid adding more global tasks so I am hesitant of adding `mix hex.token`, it can also be confused with `mix hex.key` also.
