### ISSUE TITLE
dependences base on github couldn't be extended

### ISSUE THREAD

**Issue by falood** [hexpm/hex#264]
My repo [exfswatch](https://github.com/falood/exfswatch/blob/v0.2.0/mix.exs#L22) depends [fs](https://github.com/synrc/fs) base on `github`.
But when I run `mix deps.get` for another repo depends `exfswatch`, `fs` wouldn't be downloaded.
Is this a bug? Or I did something stupid?

**Comment by josevalim** [comment]
@falood hex dependencies can only depend on  hex dependencies. When you publish the package there is even a warning that such dependencies won't be included. :)
