### ISSUE TITLE
Ugly error when ~/.mix/hex.config is wrong

### ISSUE THREAD

**Issue by sinetris** [hexpm/hex#279]
I had an old configuration line in `~/.mix/hex.config` and after a `mix local.hex` I was getting this error:

```
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"

12:24:16.865 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {1, :erl_parse, ['syntax error before: ', []]}}
            (hex) lib/hex/config.ex:5: Hex.Config.read/0
            (hex) lib/hex/state.ex:21: Hex.State.start_link/0
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

The error came from:
```elixir
{:ok, term} = decode_term(binary)
```
https://github.com/hexpm/hex/blob/v0.13.0/lib/hex/config.ex#L5

It would be nice to have a better error message, or a warning saying something like "Line N is not valid, will be ignored" 😄

**Comment by smeevil** [comment]
If anyone could paste their ```~/.mix/hex.config``` that generates the error, before throwing it away, that would help :)

**Comment by ericmj** [comment]
The issue is this commit: https://github.com/hexpm/hex/commit/d58850714bf8704bbdc54e997e5eb5cf234a863c.

It needs to be reverted and when we read an elixir config when to make sure to write an erlang config to ensure the configs are eventually updated to the new format.

**Comment by sinetris** [comment]
@smeevil I found the line with the error.
It was in `~/.hex/hex.config` and not `~/.mix/hex.config` (sorry)
```
[username: "myusername", key: "mykey"]
```
