### ISSUE TITLE
The behaviour of the HEX_UNSAFE_REGISTRY boolean seems backwards

### ISSUE THREAD

**Issue by mcoms** [hexpm/hex#285]
Setting `HEX_UNSAFE_REGISTRY=1` causes hex to *require* a signed registry. Setting `HEX_UNSAFE_REGISTRY=0` disables the signature check verification.

This is the opposite of what [the warning message returned by hex when accessing an unsigned registry](https://github.com/hexpm/hex/blob/master/lib/hex/utils.ex#L108) says.

The code here may need to be negated: https://github.com/hexpm/hex/blob/master/lib/hex/state.ex#L45

Hex: 0.13.0, Elixir: 1.3.2, OTP: 19.0.2

**Comment by ericmj** [comment]
Thanks  for the report, this is indeed incorrect. Would you mind sending a PR that adds the same Kernel.not as the line above and flips the default value?

**Comment by lexmag** [comment]
Closed in #287.
