### ISSUE TITLE
Application error publishing a package

### ISSUE THREAD

**Issue by kipcole9** [hexpm/hex#288]
## Situation
Attempting a first publishing on a package today and received the following.  No HTTP status code available but i'm guessing its a 500?  Upload took about 30 seconds, but its a reasonably large tarball at 46Mb though the gzipped version is only 13Mb.  Most of the files are static data in json format.  

## Source
https://github.com/kipcole9/cldr

## How to repeat?
mix hex.publish

## Errors received
```
Publishing package...
[#########################] 100%
Publishing failed
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
Publishing docs...
[#########################] 100%
Publishing docs failed due to the package not being published yet
```

**Comment by kipcole9** [comment]
Ah, tried again and this time got "payload too large".  Kind of stuff now I guess since the data is the CLDR repository in json format at its used at compile time to generate a ton of stuff so its intrinsic to the package.  Any suggestions?
```
Publishing package...
[#########################] 100%
Publishing failed
Payload too large
Publishing docs...
[#########################] 100%
Publishing docs failed due to the package not being published yet
```

**Comment by ericmj** [comment]
I don't see any errors in my logs, so I am guessing the first error you saw was a Heroku issue. At what time UTC did you get publish the package?

The maximum package size is 8mb, you need to find a way to make the package smaller. The data directory you include in the package is 600mb but produces only 4mb of beam files. Do you need everything in that directory?

**Comment by kipcole9** [comment]
Probably about 5am UTC and it does look like a Heroku error in the first instance.

Thanks for the clarity on the limits.  The data is the json version of the Unicode CLDR repository.  At compile time, based upon configuration, appropriate data is ingested and transformed to a  set of functions.  Given the data represents 511 locales (or cultures) I can't predict in advance what data is required for a given use case.  No clear to me how I can get the repository anywhere near 8Mb since the gzipped data is beyond that.

I suppose I could find some way for the data to be downloaded separately from the code but that would make for a pretty unpleasant user experience and a challenge to ensure dependencies are kept correctly up-to-date in dev/test/prod.  Is there a good practise for this kind of scenario?

May I suggest a note in the docs somewhere about the maximum package size? (I did look but couldn't see any).

(since its not a bug please close the issue).

**Comment by kipcole9** [comment]
Probably about 5am UTC and it does look like a Heroku error in the first instance.

Thanks for the clarity on the limits.  The data is the json version of the Unicode CLDR repository.  At compile time, based upon configuration, appropriate data is ingested and transformed to a  set of functions.  Given the data represents 511 locales (or cultures) I can't predict in advance what data is required for a given use case.  No clear to me how I can get the repository anywhere near 8Mb since the gzipped data is beyond that.

I suppose I could find some way for the data to be downloaded separately from the code but that would make for a pretty unpleasant user experience and a challenge to ensure dependencies are kept correctly up-to-date in dev/test/prod.  Is there a good practise for this kind of scenario?

May I suggest a note in the docs somewhere about the maximum package size? (I did look but couldn't see any).

(since its not a bug please close the issue).

**Comment by ericmj** [comment]
I'm sorry that I don't have a good solution for you on this issue. We currently have no plans to increase the 8mb size limit, I actually don't think having a package unzip to 600mb+ is a good thing.

You have a few options though, you can split the data directory into multiple packages, splitting on locale is probably not great since that would create 511 packages, but maybe there are some other boundaries to split on?

You can also have a task (or something automatic on compilation) that downloads the locales or data that the user needs. @lau does something like that to update timezone data: https://github.com/lau/tzdata.

https://github.com/lau/tzdata
