### ISSUE TITLE
0.12.1 -> 0.13.0 update causes error with old configuration file

### ISSUE THREAD

**Issue by okeuday** [hexpm/hex#289]
For those stuck with this, the commands help:

    mix archive.uninstall hex-0.13.0
    mix archive.install https://repo.hex.pm/installs/1.2.0/hex-0.12.1.ez

The output is below, using Erlang/OTP 19.0 with Elixir 1.3.2 (same error with Elixir 1.3.0)

    $ mix hex.info

    16:55:34.596 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, {1, :erl_parse, ['syntax error before: ', []]}}
                (hex) lib/hex/config.ex:5: Hex.Config.read/0
                (hex) lib/hex/state.ex:21: Hex.State.start_link/0
                (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:348: :supervisor.start_children/3
                (stdlib) supervisor.erl:314: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

    16:55:34.597 [info]  Application inets exited: :stopped

    16:55:34.597 [info]  Application ssl exited: :stopped

    16:55:34.597 [info]  Application public_key exited: :stopped

    16:55:34.598 [info]  Application asn1 exited: :stopped

    16:55:34.598 [info]  Application crypto exited: :stopped
    ** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {{:badmatch, {:error, {1, :erl_parse, ['syntax error before: ', []]}}}, [{Hex.Config, :read, 0, [file: 'lib/hex/config.ex', line: 5]}, {Hex.State, :start_link, 0, [file: 'lib/hex/state.ex', line: 21]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 365]}, {:supervisor, :start_children, 3, [file: 'supervisor.erl', line: 348]}, {:supervisor, :init_children, 2, [file: 'supervisor.erl', line: 314]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}, {Hex, :start, [:normal, []]}}}}
        (hex) lib/hex.ex:5: Hex.start/0
        (hex) lib/mix/tasks/hex/info.ex:22: Mix.Tasks.Hex.Info.run/1
        (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
        (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
        (elixir) lib/code.ex:363: Code.require_file/2

**Comment by okeuday** [comment]
it required a new login after I found where my password was, to rely on only erlang syntax in the hex.config file, so, I did get 0.13.0 work with a new login

**Comment by ericmj** [comment]
This has been fixed on master. A new release will be made when I am back home from conferences.
