### ISSUE TITLE
'mix hex.docs open' should go online to hexdocs.pm by default

### ISSUE THREAD

**Issue by whatyouhide** [hexpm/hex#291]
Add --offline for the offline option.

**Comment by josevalim** [comment]
Hrm, I have a different understanding of this issue then. I was expecting
open to always open the local version and automatically fetch one if one is
not available locally. But after you mentioned the --offline flag, it seems
it was meant to always open the remote one? Maybe we should have two
different verbs? Open and visit or something of sorts?


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
@josevalim me and @ericmj just discussed this at the Elixir Addicts meetup and I was mentioning that most of the time I want to just browse the docs on hexdocs.pm because I don't care about having them locally. The times that I want offline docs, I can do `mix hex.docs open --offline`, which will check if it's already downloaded and if it's not it will automatically fetch as you said (or error out if there's no internet connection). Wdyt? (also we couldn't think of any other verb other than "open" that would fit 😄)

**Comment by josevalim** [comment]
That makes sense, thanks for explaining. +1 to the --offline flag.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ottolin** [comment]
I like this feature a lot. Usually I only care about the online version. :smile:
