### ISSUE TITLE
Missing xyz.app.src causes badmatch

### ISSUE THREAD

**Issue by ksallberg** [hexpm/hex#295]
Thinking this issue might be due to the hex plugin not checking that there is actually a .app.src file in /src? I was using the old-school ebin/xyz.app and this caused a badmatch...

kristian@signhild:~/Documents/erlang/brunhilde$ DEBUG=1 rebar3 hex publish
===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {default,install_deps},
                                                  {default,lock},
                                                  {hex,publish}]
===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl/src/erlydtl.app.src.script"
===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl/rebar.config.script"
===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/jsx/rebar.config.script"
===> Not adding provider hex user from module rebar3_hex_user because it already exists from module rebar3_hex_user
===> Not adding provider hex cut from module rebar3_hex_cut because it already exists from module rebar3_hex_cut
===> Not adding provider hex config from module rebar3_hex_config because it already exists from module rebar3_hex_config
===> Not adding provider hex key from module rebar3_hex_key because it already exists from module rebar3_hex_key
===> Not adding provider hex info from module rebar3_hex_info because it already exists from module rebar3_hex_info
===> Not adding provider hex owner from module rebar3_hex_owner because it already exists from module rebar3_hex_owner
===> Not adding provider hex docs from module rebar3_hex_docs because it already exists from module rebar3_hex_docs
===> Not adding provider hex search from module rebar3_hex_search because it already exists from module rebar3_hex_search
===> Not adding provider hex publish from module rebar3_hex_pkg because it already exists from module rebar3_hex_pkg
===> Not adding provider hex user from module rebar3_hex_user because it already exists from module rebar3_hex_user
===> Not adding provider hex cut from module rebar3_hex_cut because it already exists from module rebar3_hex_cut
===> Not adding provider hex config from module rebar3_hex_config because it already exists from module rebar3_hex_config
===> Not adding provider hex key from module rebar3_hex_key because it already exists from module rebar3_hex_key
===> Not adding provider hex info from module rebar3_hex_info because it already exists from module rebar3_hex_info
===> Not adding provider hex owner from module rebar3_hex_owner because it already exists from module rebar3_hex_owner
===> Not adding provider hex docs from module rebar3_hex_docs because it already exists from module rebar3_hex_docs
===> Not adding provider hex search from module rebar3_hex_search because it already exists from module rebar3_hex_search
===> Not adding provider hex publish from module rebar3_hex_pkg because it already exists from module rebar3_hex_pkg
===> Verifying dependencies...
===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl/src/erlydtl.app.src.script"
===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl/src/erlydtl.app.src.script"
===> Upgrading erlydtl ({pkg,<<"erlydtl">>,<<"0.12.1">>})
===> Successfully downloaded https://repo.hex.pm:443/tarballs/erlydtl-0.12.1.tar?
===> Downloaded package, caching at /home/kristian/.cache/rebar3/hex/default/packages/erlydtl-0.12.1.tar
===> Writing {pkg,<<"erlydtl">>,<<"0.12.1">>} to cache at /home/kristian/.cache/rebar3/hex/default/packages/erlydtl-0.12.1.tar
===> Moving checkout "/tmp/.tmp_dir321294108200" to "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl"
===> sh info:
        cwd: "/home/kristian/Documents/erlang/brunhilde"
        cmd: mv /tmp/.tmp_dir321294108200 /home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl

===>    opts: [{use_stdout,false},abort_on_error]

===> Port Cmd: mv /tmp/.tmp_dir321294108200 /home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl/src/erlydtl.app.src.script"
===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/erlydtl/rebar.config.script"
===> Evaluating config script "/home/kristian/Documents/erlang/brunhilde/_build/default/lib/jsx/rebar.config.script"
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: {badmatch,[]}
===> Stack trace to the error location: [{rebar3_hex_utils,
                                                 update_app_src,2,
                                                 [{file,
                                                   "/home/kristian/Documents/erlang/brunhilde/_build/default/plugins/rebar3_hex/src/rebar3_hex_utils.erl"},
                                                  {line,14}]},
                                                {rebar3_hex_pkg,publish,2,
                                                 [{file,
                                                   "/home/kristian/Documents/erlang/brunhilde/_build/default/plugins/rebar3_hex/src/rebar3_hex_pkg.erl"},
                                                  {line,104}]},
                                                {rebar3_hex_pkg,do_,2,
                                                 [{file,
                                                   "/home/kristian/Documents/erlang/brunhilde/_build/default/plugins/rebar3_hex/src/rebar3_hex_pkg.erl"},
                                                  {line,79}]},
                                                {lists,foldl,3,
                                                 [{file,"lists.erl"},
                                                  {line,1263}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/kristian/Documents/erlang/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar_prv_do,do_tasks,2,
                                                 [{file,
                                                   "/home/kristian/Documents/erlang/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                                                  {line,68}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/kristian/Documents/erlang/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar3,main,1,
                                                 [{file,
                                                   "/home/kristian/Documents/erlang/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
                                                  {line,56}]}]

**Comment by ericmj** [comment]
Please post this issue over at https://github.com/hexpm/rebar3_hex so that the right people see it :)
