### ISSUE TITLE
mix hex.outdated in umbrella root doesn't list top-level packages

### ISSUE THREAD

**Issue by enilsen16** [hexpm/hex#296]
elixir/erlang:

```
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.0-dev (470b2ee)
```

expected:

```
~ umbrella_example $ mix hex.outdated
plug         1.2.2       1.2.2       ~> 1.2
poison       3.0.0       3.0.0       ~> 3.0
postgrex     0.12.1      0.12.1      >= 0.0.0
```

actual:

```
~ umbrella_example $ mix hex.outdated
No hex dependencies
```

It's worth noting that `mix hex.outdated --all` does return all packages though.

**Comment by enilsen16** [comment]
I've included a better example here -- https://github.com/enilsen16/umbrella_test

```
~/Projects/umbrella_test(master ✔) mix hex.outdated
No hex dependencies
~/Projects/umbrella_test(master ✔) mix hex.outdated --all
Dependency  Current  Latest  Requirement
cowboy      1.0.4    1.0.4   ~> 1.0
cowlib      1.0.2    1.3.0   ~> 1.0.0
poison      3.0.0    3.0.0   ~> 3.0
ranch       1.2.1    1.2.1   ~> 1.0
```

**Comment by josevalim** [comment]
@enilsen16 this is tricky because the umbrella project could contain hex dependencies exclusive to it but I can also see most people would like it to show the child apps deps.

**Comment by ericmj** [comment]
Should we change the default to list from umbrella children and add a flag that does the current behaviour, if so what should the flag be?

**Comment by josevalim** [comment]
@ericmj I am unsure. Maybe it is just a matter of changing the error message to say "No hex dependencies for the current project. (if umbrella)To include your child applications, use the --all flag.(end)"

**Comment by enilsen16** [comment]
I would expect to see both the root and child top-level packages when running `mix hex.outdated`. I tend to use `mix hex.outdated` as a way to list all the packages and versions an Elixir project is using. 

While `--all` does return all packages, it can be hard to visually grep what top-level packages are outdated.

**Comment by pikeas** [comment]
Recently switched to an umbrella app and noticed this as well. It feels counterintuitive to only see my root-level dependencies, because most of the important deps are inside the apps!

How about `mix hex.outdated --include-umbrella-apps`, with a default value of `false` now, switching to default `true` with Elixir 2.0?

**Comment by ericmj** [comment]
I think `mix hex.outdated` can just return all umbrella dependencies right now. We don't need a deprecation period.
