### ISSUE TITLE
Document system env vars in hex.config

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#299]
Configuration is currently split between `mix hex` and `mix hex.config`. It should be moved completely to `mix hex.config` and `mix hex` should only show general help about the hex tasks.

**Comment by khusnetdinov** [comment]
This task is completed? https://monosnap.com/file/Y8WU3SITRbwlE5ON6a72xgbgpkVRgX or is required some thing other?

**Comment by wojtekmach** [comment]
I think this issue refers to docs, typing `mix help hex` currently shows this configuration stuff:

https://github.com/hexpm/hex/blob/v0.14.0/lib/mix/tasks/hex.ex#L6:L28

**Comment by khusnetdinov** [comment]
Please, correct me if something wrong.
