### ISSUE TITLE
Credo broken after Hex update

### ISSUE THREAD

**Issue by roehst** [hexpm/hex#302]
Just updated with mix local.hex and Credo threw this at me.

** (UndefinedFunctionError) function Hex.Utils.ensure_registry!/0 is undefined or private
   (hex) Hex.Utils.ensure_registry!()
   lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
   lib/credo/cli.ex:92: Credo.CLI.run/1
   lib/credo/cli.ex:58: Credo.CLI.main/1
   (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
   (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

**Comment by ericmj** [comment]
You should open an issue at credo. Credo is calling undocumented, private functions that changed in the last release.

**Comment by omidbachari** [comment]
Have this same problem. Thank you for the explanation @ericmj CC @rrrene

**Comment by dukeluke16** [comment]
Here's the Credo issue for those of you looking for resolution.  https://github.com/rrrene/credo/issues/210

to revert your mix version back to 13.2, simply use this in your build scripts:
`mix archive.install https://repo.hex.pm/installs/1.3.0/hex-0.13.2.ez --force`

**Comment by josevalim** [comment]
I believe we can close this as it is not a Hex bug.

Folks, please don't use private APIs. It is not nice.

**Comment by rrrene** [comment]
@ericmj Sorry. Completely my fault!

@josevalim I guess the right way to do this (checking available versions of a package) would be through the JSON API then? Would there be a third way (if I don't want to depend on a JSON encoder)?

**Comment by josevalim** [comment]
@rrrene that may be the proper way today but it doesn't have to be in the long term. In those situations, I think the best would be to open up an issue in the project, explain you need certain APIs, and discuss how to move forward.

**Comment by josevalim** [comment]
Btw, I believe Hex already calculates the outdated information. So maybe it could support an API that returns that as data?

**Comment by wojtekmach** [comment]
@josevalim exactly, I was just gonna mention outdated. I think it would be nice to provide more programatic access to outdated information than through the mix task :+1:

As far as using JSON API, this is also possible right now:

```elixir
Hex.API.Package.get("credo") 
```

but it may not be considered a public API, so don't depend on it yet. Long-term it would be better to go through registry for this data anyway.

**Comment by rrrene** [comment]
@josevalim I will open an issue discussing the potential need for this. Thx!
@wojtekmach I more-or-less took the approach from the `mix hex.outdated` task. ;-)

**Comment by ericmj** [comment]
The HTTP API supports multiple media types: http://docs.hexpm.apiary.io/#introduction/media-types. I would recommend using `application/vnd.hex+erlang` that can be decoded with `:erlang.binary_to_term/1`.

**Comment by ericmj** [comment]
All modules under the `Hex` namespace should currently be considered private.

**Comment by rrrene** [comment]
@ericmj Ah, thx for poiting out the media types. Will look into it over the weekend!

**Comment by rrrene** [comment]
@ericmj @josevalim Credo `0.4.14` and `v0.5.1` now implement the Hex API lookup using the Erlang term media type. :+1: Thx for all the pointers!

**Comment by josevalim** [comment]
:tada:
