### ISSUE TITLE
Move hex.key to hex.user keys

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#305]
Given those commands require user authentication and are associated to the logged in user, it seems clearer to move them there. It would also reduce the amount of tasks. `remove` could become remove `--remove NAME` and `--remove all` could become `--remove-all`.

**Comment by milmazz** [comment]
I think this issue is already fixed

**Comment by ericmj** [comment]
Closing in favor of PR https://github.com/hexpm/hex/pull/334.
