### ISSUE TITLE
mix.lock contains duplicate build tools

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#306]
On elixir 1.3.4 and hex 0.14.0 I created a new mix project and installed comeonin:

```
$ cat mix.lock
%{"comeonin": {:hex, :comeonin, "2.6.0", "74c288338b33205f9ce97e2117bb9a2aaab103a1811d243443d76fdb62f904ac", [:make, :make, :mix], []}}
```

**Comment by ericmj** [comment]
I think we need to add Enum.uniq here https://github.com/hexpm/hex/blob/master/lib/hex/scm.ex#L112. We already have it here https://github.com/hexpm/hex/blob/master/lib/hex/mix.ex#L183.
