### ISSUE TITLE
Getting non-deterministic mix.lock files on hex 0.14

### ISSUE THREAD

**Issue by myronmarston** [hexpm/hex#309]
After upgrading to hex 0.14, running `mix deps.get` sometimes produces a change in my `mix.lock` file like this:

```
-  "ssl_verify_fun": {:hex, :ssl_verify_fun, "1.1.0", "edee20847c42e379bf91261db474ffbe373f8acb56e9079acb6038d4e0bf414f", [:rebar, :make], []},
+  "ssl_verify_fun": {:hex, :ssl_verify_fun, "1.1.0", "edee20847c42e379bf91261db474ffbe373f8acb56e9079acb6038d4e0bf414f", [:make, :rebar], []},
```

Other times it does not.  I've seen it happen for more than one package, too.  Would be nice if hex ordered the `[:rebar, :make]` list consistently so it doesn't make for a change in the file.

**Comment by ericmj** [comment]
Does it change back to the other ordering? Otherwise you are seeing this because we fixed the ordering.

**Comment by myronmarston** [comment]
> Does it change back to the other ordering?

I guess not.  I hadn't actually committed any of the re-orderings yet, but now that I know that it's intentional and an improvement, I will :).
