### ISSUE TITLE
Can't open fetched documentation on linux

### ISSUE THREAD

**Issue by vasspilka** [hexpm/hex#310]
I get `** (Mix) Command not found: open` when I try to open documentation, 
with `mix hex.docs open xxx`

I was thinking that maybe I am just missing some `open` linux command for opening in a browser, does that make sense?

System:
  Arch, Linux 4.4.24-1-lts
  Hex v0.14.0
  Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
  Mix 1.3.4

**Comment by ericmj** [comment]
I think we should use `xdg-open` for linux. Do you have that command?

**Comment by vasspilka** [comment]
Yes, what I ended up doing for now is
`sudo cp /usr/bin/xdg-open /usr/bin/open` 
kind of hacky solution but it seems to work,

**Comment by wojtekmach** [comment]
for anyone picking this up, we'd need to change this: https://github.com/hexpm/hex/blob/d70d99bb44c2be9a8eb1110ca5d63d8c6fcae282/lib/mix/tasks/hex/docs.ex#L150:L154

**Comment by ericmj** [comment]
I believe we should only use `open` when `:os.type` returns `{:unix, :darwin}`. Otherwise `xdg-open` should be used.

**Comment by vasspilka** [comment]
ok I'm on it :)

**Comment by wojtekmach** [comment]
Fixed by #311

**Comment by wojtekmach** [comment]
Thanks @vasspilka!
