### ISSUE TITLE
Hex doesn't update right on rc requirements or doesn't color right on mix hex.outdated

### ISSUE THREAD

**Issue by TBK145** [hexpm/hex#312]
Basicly, the issue is with db_connection, the newest release being 1.1.0, and the requirement is 1.0-rc4.
The requirement is shown in green (and latest obviously red), which should mean that if I update the dependency, it will become the latest version. However, that's not the case, as seen below:

```
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix hex.outdated --all
Dependency           Current  Latest  Requirement         
[...]            
db_connection        1.0.0    1.1.0   ~> 1.0-rc.4         
[...]           

A green version in latest means you have the latest version of a given package. A green requirement means your current requirement matches the latest version.
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix deps.unlock db_connection
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix deps.update db_connection
Running dependency resolution
Dependency resolution completed
  db_connection: 1.0.0
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix deps.clean db_connection
* Cleaning db_connection
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix deps.get db_connection
Running dependency resolution
* Getting db_connection (Hex package)
  Checking package (https://repo.hex.pm/tarballs/db_connection-1.0.0.tar)
  Using locally cached package
```

**Comment by ericmj** [comment]
Do you have any other dependencies that might constrain the db_connection version?

**Comment by TBK145** [comment]
The only dependencies that depend on db_connections are ecto (1.0-rc4), postgres (1.0-rc4) and mariaex (1.0.0-rc).

```
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix deps.tree | grep db_connection -B 2
├── postgrex ~> 0.9 (Hex package)
│   ├── connection ~> 1.0 (Hex package)
│   ├── db_connection ~> 1.0-rc.4 (Hex package)
--
│   └── decimal ~> 1.0 (Hex package)
└── ecto ~> 2.0 (Hex package)
    ├── db_connection ~> 1.0-rc.4 (Hex package)
--
├── poolboy ~> 1.4 (Hex package)
├── mariaex ~> 0.7 (Hex package)
│   ├── db_connection ~> 1.0.0-rc (Hex package)
```

So it looks like mariaex (version 0.7.9) is constraining, but is not shown in the output of `mix hex.outdated --all`.

**Comment by ericmj** [comment]
The mariaex dependency "~> 1.0.0-rc" constrains the version to ">= 1.0.0-rc and < 1.1.0". Take a look here for documentation on the `~>` operator: http://elixir-lang.org/docs/master/elixir/Version.html#module-requirements.

**Comment by TBK145** [comment]
I understand, but the output of `mix hex.outdated --all` is not showing the strictest constraint:
```
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix hex.outdated --all
Dependency           Current  Latest  Requirement         
[...]            
db_connection        1.0.0    1.1.0   ~> 1.0-rc.4         
[...]    
```
Because 1.0-rc.4 should be 1.0.0-rc in this case.

**Comment by ericmj** [comment]
It shows your constraint on the dependency. If you run `mix hex.outdated db_connection` it will show all.

**Comment by TBK145** [comment]
But it's not my constraint, db_connection is a dependency managed by other dependencies:
```
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix hex.outdated db_connection
There is newer version of the dependency available 1.1.0 > 1.0.0!

Parent    Requirement  
ecto      ~> 1.0-rc.4  
mariaex   ~> 1.0.0-rc  
postgrex  ~> 1.0-rc.4 
```

**Comment by ericmj** [comment]
I think that may be bug. We should not show the requirement for dependencies that are only available when passing `--all`.

**Comment by TBK145** [comment]
I don't think that's the correct solution, because I have to pass `--all` to see the dependencies of my child applications, and I do want to see their requirements, eg: one of my child applications has ecto, and I want to know if my version and requirement is up-to-date. So IMO it would be best to show the strictest constraint as requirement.

Also, maybe not completely related, my child applications aren't listed as parent:
```
thijs@WERKBEEST:~/Documents/voiceover_umbrella (master)$ mix hex.outdated ecto
Current version 2.0.5 of dependency is up to date!

Parent        Requirement  
phoenix_ecto  ~> 2.0 
```
Here my child applications should be listed as well.

**Comment by josevalim** [comment]
Maybe we should show all requirements and where they come from?

**Comment by ericmj** [comment]
> So IMO it would be best to show the strictest constraint as requirement.

There may not be a clear strictest constraint. Out of these two constraints which one would you say is stricter "~> 1.1.0" or "~> 1.2.0".

> Also, maybe not completely related, my child applications aren't listed as parent:

What child applications are not listed? If you shared your mix.exs and mix.lock files it would be easier to see what's happening.

**Comment by ericmj** [comment]
> Maybe we should show all requirements and where they come from?

We do that when you call you `mix hex.outdated APP`.  `mix hex.outdated` is already packed with information, I am afraid it would be unwieldy to show all requirements also. It's also not clear how it would fit inside the current table structure.

**Comment by TBK145** [comment]
> There may not be a clear strictest constraint. Out of these two constraints which one would you say is stricter "~> 1.1.0" or "~> 1.2.0".

"~> 1.2.0", because that one won't allow 1.1.x.
> What child applications are not listed? If you shared your mix.exs and mix.lock files it would be easier to see what's happening.

This is the umbrella mix.exs:
```elixir
defmodule Voiceover.Mixfile do
  use Mix.Project

  def project do
    [apps_path: "apps",
     app: :voiceover,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  defp deps do
    [
      {:credo, "~> 0.5", only: :dev},
      {:mex, "~> 0.0.1", only: :dev}
    ]
  end
end
```

One of my child applications has this mix.exs:
```elixir
defmodule Voiceover.Core.Mixfile do
  use Mix.Project

  def project do
    [app: :voiceover_core,
     version: "0.0.1",
     build_path: Path.join(umbrella_path?(), "_build"),
     config_path: Path.join(umbrella_path?(), "config/config.exs"),
     deps_path: Path.join(umbrella_path?(), "deps"),
     lockfile: Path.join(umbrella_path?(), "mix.lock"),
     elixir: "~> 1.3",
     elixirc_paths: elixirc_paths(Mix.env),
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps(),
     name: "Voiceover Core"
    ]
  end

  def umbrella_path? do
    case Mix.Project.umbrella? do
      true -> Path.join "..", ".."
      _    -> ""
    end
  end

  def application do
    [mod: {Voiceover.Core.Application, []},
     applications: [
       :logger,
       :ecto,
       :postgrex,
       :poolboy,
       :erlcloud,
       :timex,
       :poison,
       :phoenix_pubsub,
       :uuid,
       :apex,
       :exometer_influxdb,
       :exometer_zabbix,
       :erlang_gearman,
       :connection
     ] ++ if(Mix.env == :dev, do: [:ex_doc], else: [])
    ]
  end

  defp elixirc_paths(_), do: ["lib", "priv/repo/migrations"]

  defp deps do
    [
      # Database model
      {:ecto, "~> 2.0"},
      {:postgrex, "~> 0.9"},

      # Messages
      {:timex, "~> 3.0"},
      {:uuid, "~> 1.0"},
      {:poison, "~> 2.0"},
      {:apex, "~> 0.3"},

      # PubSub
      {:phoenix_pubsub, "~> 1.0"},
     
      # Docs
      {:ex_doc, "~> 0.11", only: :dev},

      # Ceph
      {:erlcloud, "~> 0.13.5"},
      {:poolboy, "~> 1.5"},

      # Gearman
      {:erlang_gearman, github: "TBK145/erlang-gearman"},

      # Xmpp
      {:connection, "~> 1.0"},

      # Monitoring & Statistics
      {:exometer_influxdb, github: "travelping/exometer_influxdb", tag: "0.5.1"},
      {:exometer_zabbix, "~> 0.0.3"},

      # overrides because of conflicts
      {:lager, "~> 3.2", override: true},
      {:edown, "~> 0.7", override: true},
      {:meck, "~> 0.8.2", override: true},
      {:hackney, "~> 1.0", override: true},
    ]
  end
end
```
So voiceover_core has a dependency on ecto, but if you run `mix hex.outdated ecto` from the umbrella, it's not shown as parent, as seen above.

**Comment by ericmj** [comment]
> "~> 1.2.0", because that one won't allow 1.1.x.

But "~> 1.1.0" does not allow 1.2.x.

I did not consider umbrellas when creating `hex.outdated` so it's likely we can improve things for umbrellas.

**Comment by TBK145** [comment]
> But "~> 1.1.0" does not allow 1.2.x.

Ah of course, I was a bit too quick drawing a conclusion there.

Anyway, I just think that showing a green 1.0-rc4 is confusing when in fact you cannot update.

**Comment by ericmj** [comment]
> Anyway, I just think that showing a green 1.0-rc4 is confusing when in fact you cannot update.

Yes, I think we should not show the requirement for non-direct dependencies.

**Comment by TBK145** [comment]
But that would also mean that you cannot see the requirements for dependencies of child applications from the umbrella root, right?

**Comment by ericmj** [comment]
Correct, you would have to call `mix hex.outdated APP` to see those requirements.
