### ISSUE TITLE
Dependency conflict in child app of umbrella app when using `app: false`

### ISSUE THREAD

**Issue by facto** [hexpm/hex#313]
```
Dependencies have diverged:
* espec_phoenix (Hex package)
  the dependency espec_phoenix in mix.exs is overriding a child dependency:

  > In mix.exs:
    {:espec_phoenix, ">= 0.3.0 and < 1.0.0", [env: :prod, hex: :espec_phoenix, only: :test, app: false, manager: :mix]}

  > In ...deps/espec_phoenix_helpers/mix.exs:
    {:espec_phoenix, ">= 0.3.0 and < 1.0.0", [only: :test, env: :prod, hex: :espec_phoenix, optional: false]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

Steps I took to encounter this error:

1. Added dependency on espec_phoenix_helpers 0.2.0, of which I am the author.
2. Ran `mix deps.get`. Encountered conflict because I did not include `app: false` for espec_phoenix within espec_phoenix_helpers.
3. Added `app: false` to espec_phoenix_helpers. Bumped version to 0.3.0. Pushed to hex.pm.
4. Changed dependency version for espec_phoenix_helpers to 0.3.0 in my child app.
5. Ran `mix deps.get` again. Encountered same conflict.
6. Tried `mix deps.clean`, deleting deps dir, manually downloading 0.3.0 from hex.pm and replacing in ~/.hex. Same issue.
7. Replaced dependency version with the link directly to github, and it worked.

Hex version: 0.14.0
Elixir version: 1.3.0

**Comment by ericmj** [comment]
Thanks for the report!

The issue seems to be that we do not pass along the `:app` correctly from the registry when building the `Mix.Dep` struct. I will investigate.

**Comment by ericmj** [comment]
I don't think we can support the `:app` option unfortunately so we should raise when publishing. We don't support any other options such as override, compile and manager. I am also not sure how `:app` would work for other build tools such as rebar3.

/cc @josevalim

**Comment by josevalim** [comment]
@ericmj this can put us in an uncomfortable situation where a package without an app is published to Hex but we cannot depend on it.

**Comment by ericmj** [comment]
@josevalim I would argue that they are using Hex wrong in that case. A Hex package should be some form of OTP application, unfortunately we have no way of enforcing it since the clients accept any source content.

**Comment by josevalim** [comment]
Sounds good. +1 for forbidding it then!
