### ISSUE TITLE
Improve error when package doesn't exist

### ISSUE THREAD

**Issue by scrogson** [hexpm/hex#314]
This is super minor, but might be nice to clean up the output in this scenario:

I accidentally added `:distiller` instead of `:distillery` to my deps. When I ran `mix deps.get` this was the output:

```
λ mix deps.get
Failed to fetch record for 'distiller' from registry (using cache)
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>47488A054A7CE7E6</RequestId><HostId>I0gOR+Hx/sELtPfJdVRMuQEyz64CqIxANoAFnMcJHbnKEAUmafkZhYwEMDoI5ai/NAg7NTif9/E=</HostId></Error>
** (Mix) No package with name distiller (from: mix.exs) in registry
```

**Comment by ericmj** [comment]
I think we can check for 404 and 403 and not print any output in those cases. But that means if the repository has useful information for us in the body we are ignoring it.

**Comment by wojtekmach** [comment]
> But that means if the repository has useful information for us in the body we are ignoring it.

for that case, perhaps having `debug`/`HEX_DEBUG` config option would solve it? E.g. in error message we could say: "run with HEX_DEBUG=1 to see more info" or something like that.

**Comment by ericmj** [comment]
HEX_DEBUG sounds like a good solution.
