### ISSUE TITLE
hex.docs open package Package.Some.Module

### ISSUE THREAD

**Issue by Mehonoshin** [hexpm/hex#315]
Hello!

I wonder, if we could add ability to open docs for specified module in package.
We can even skip the package name and pass module name directly, e.g:

```elixir
  mix hex.docs open Coherence.Authentication.Basic
```
should open `https://hexdocs.pm/coherence/Coherence.Authentication.Basic.html`

Thoughts?
If the idea is fine - I could implement it.

**Comment by ericmj** [comment]
We could do it if you called it as `mix hex.docs open coherence --module Coherence.Authentication.Basic`, otherwise we don't know what package the module belongs to.

**Comment by Mehonoshin** [comment]
Why don't we take package from the module name?
I thought that it is strictly conventional in elixir, that modules start from package name.

**Comment by ericmj** [comment]
It is a convention but not one that you have to strictly to follow. It also needs to work with erlang packages.

**Comment by Mehonoshin** [comment]
ok, I got it.
Then could implement it, as you proposed, with --module option
