### ISSUE TITLE
Improve error message when package-version does not exist

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#318]
If someone depends on a version of a package that does not exist, we should say so in the error message. Today it says:

```
Running dependency resolution

Failed to use "postgrex" because
  mix.exs specifies ~> 1.0
```

We should probably say:

```
Failed to use "postgrex" because there are no packages that matches the requirement
  mix.exs specifies ~> 1.0
```

Notice this is about a single requirement that does not match any version. If multiple requirements lead to no match, that's another problem.

Related to #314.

**Comment by sotojuan** [comment]
Is the place to fix this [here](https://github.com/hexpm/hex/blob/master/lib/hex/resolver/backtracks.ex#L161)?
