### ISSUE TITLE
Mix deps.get should fail if cyclic deps found

### ISSUE THREAD

**Issue by ardhitama** [hexpm/hex#321]
Running `mix` invokes
`** (Mix) Could not sort dependencies. There are cycles in the dependency graph`

While running `mix deps.get` stalled the console.

The behavior should be similar.

**Comment by ericmj** [comment]
Can you show a mix project that reproduces this?

**Comment by ardhitama** [comment]
It's an private umbrella project.

`App1`'s `mix.exs`

```
defp deps do
    [
...
     {:app2, in_umbrella: true},
...
   ]
  end
```

`App2`'s `mix.exs`

```
defp deps do
    [
...
     {:app1, in_umbrella: true},
...
   ]
  end
```

**Comment by josevalim** [comment]
That's an Elixir bug. Can you please report it on elixir-lang/elixir? Thank you.
