### ISSUE TITLE
Feature Request: Show 'exact match' of search query on top

### ISSUE THREAD

**Issue by Qqwy** [hexpm/hex#325]
Right now, search results on Hex.pm are sorted by the amount of downloads. This is of course one of the least subjective way to sort search results.

However, when someone looks for a package that is relatively new, such as e.g. the [Numbers](https://hex.pm/packages/numbers) package that I released yesterday, it is all the way at the end of the search results, [even if you search exactly for the string `"numbers"`](https://hex.pm/packages?search=numbers&sort=downloads).

Some other package managers, notably RubyGems, show an `exact match` on top, if a package exists with exactly the name you typed in. 
I think this would be a great addition to Hex.pm, as it would make new packages easier to find.

**Comment by ericmj** [comment]
I agree. Please reopen at hexpm/hex_web.
