### ISSUE TITLE
Improve error message (and possibly handling) for not-modified but not-found packages

### ISSUE THREAD

**Issue by karlseguin** [hexpm/hex#328]
I'm not exactly sure what happened, but I started to get: "Unable to find package X in registry". The short version is that the request being sent to the registry included an `if-none-match` header, which the server replied with a Not Modified response and everything fell apart from that point on. Removing the header solved the problem.

It seems like the messaging could be improved, and possibly the error handling. I mean, if the server returns "not modified" and the package isn't found, something identifiable inconsistent is happening.

**Comment by ericmj** [comment]
This is a bug where the etag is cached but the tarball is somehow not. We have changed on master to include a `File.exists?` check so this should not happen anymore in the next release. A temporary workaround is to delete the `~/.hex/cache.ets` file.
