### ISSUE TITLE
Unable to find package in registry

### ISSUE THREAD

**Issue by vic** [hexpm/hex#329]
Hi, 

I'm getting the following error when doing `mix deps.get` after creating a fresh mix project and adding a single dependency:

```shell
mix deps.get
Running dependency resolution
** (Mix) Unable to find package db_connection in registry
```

Here's the mix.exs file:

```elixir
defmodule Foo.Mixfile do
  use Mix.Project

  def project do
    [app: :foo,
     version: "0.1.0",
     elixir: "~> 1.4-rc",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:my_dep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:my_dep, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:postgrex, "~> 1.0.0-rc.1"}
    ]
  end
end
```

Also happens for other deps like ` {:dialyxir, "~> 0.4.1"}`

```
** (Mix) Unable to find package dialyxir in registry
```

even when that is the dependency as reported by `mix hex.info dialyxir`. Does not happen with others like `{:ecto, "~> 2.1"}` any idea on what is wrong?

**Comment by wojtekmach** [comment]
it's probably not gonna solve your issue, but please don't use `postgrex 1.0.0-rc.1` - that release got retired (see: https://hex.pm/packages/postgrex/1.0.0-rc.1)

**Comment by vic** [comment]
Yep, just used postgrex as an example of a much more used package, after actually trying to install dialyxir and other packages.

The dialyxir version I'm trying to use does not look like being retired:
https://hex.pm/packages/dialyxir/0.4.1

Anyways still don't have a clue what's wrong. 

As a side note, I normally tend to use `mix hex.info postgrex` to quickly copy and paste the dependency config I need for some package, that's what I did when trying out postgrex, shouldn't `hex.info` output only the latest non-retired and thus _actually-installable_ version?

**Comment by vic** [comment]
Possibly some hex service is down :(

```
$ mix phoenix.new bar
$ cd bar
$ mix deps.get
Running dependency resolution
** (Mix) Unable to find package db_connection in registry
```

**Comment by josevalim** [comment]
That may be a cache issue. Try nuking "~/.hex/cache.ets" and see how it goes.

**Comment by vic** [comment]
Great, that was it, thanks @josevalim ^^ ❤️

**Comment by Frost** [comment]
Hi,

I'm having this exact issue now, but with the `amqp` package, which at least [seems to exist](https://hex.pm/packages/amqp/0.1.5:

```
$ mix deps.get
Failed to fetch record for 'amqp' from registry (using cache)
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5FD09CD0ECB5A175</RequestId><HostId>UmKsU/FqwBNS8FwSroNwkSUVS/K0OlMMZBP8QEQMKWuRIV2+rL2D6kHa7UrVJboB3unLWB6mpQo=</HostId></Error>
** (Mix) Unknown package amqp in lockfile
```

I cannot find any `~/.hex/cache.ets` file locally. In fact, I have tried to nuke the entire `~/.hex` directory but I still get the same error.

All other packages seem to work fine, so I am not sure if that's an issue with hex or the amqp package. 

Minimal reproduction case (creates a new elixir app, adds `amqp` dependency, and tries to `mix deps.get`):

```
bash -c "mix new does_amqp_work && cd does_amqp_work && sed -e 's/\[\]/[{:amqp, \"0.1.5\"}]/' -i mix.exs && mix deps.get"
```

**Comment by Frost** [comment]
@twinn narrowed this down to something breaking between hex 0.12 and 0.15: https://twitter.com/tony_winn/status/829814144736051202

@ericmj Is there any way to downgrade my local version of hex?

**Comment by ericmj** [comment]
@Frost You seem to have been hit by a separate issue on the backend. I have fixed it manually.

**Comment by twinn** [comment]
@ericmj @Frost works now, thanks!

**Comment by ericmj** [comment]
Fixed on the backend: https://github.com/hexpm/hex_web/commit/73760debbc4d4cd96b39cee8a55da0789ce690d9.

**Comment by Frost** [comment]
Yep, it works now. Thanks! :)

**Comment by cedrico2016** [comment]
```That may be a cache issue. Try nuking "~/.hex/cache.ets" and see how it goes.```
How can i nuke "~/.hex/cache.ets"? what is the command for that? I am facing the same issue.

**Comment by josevalim** [comment]
@cedrico2016 just remove the file. Like `rm "~/.hex/cache.ets"`.

**Comment by cedrico2016** [comment]
@josevalim 
i've tried it several times, but it is always impossible for me to install exmagic. 
I get the same error: ```Failed to fetch record for 'exmagic' from registry (using cache)
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>A3F2A7B332AA4036</RequestId><HostId>WCIUUiFhkuRXZTJLdu6ZJGI/3PQOlvV+IeTAIfEf8r9MLPqH5JrMlP3QOJcX2B/iFEatx/ZhJP0=</HostId></Error>
** (Mix) No package with name exmagic (from: mix.exs) in registry
```

In the mix.exs i added: ```{:exmagic, "~> 0.0.5"},```

**Comment by Frost** [comment]
@cedrico2016 Did you mean [exmagick](https://hex.pm/packages/exmagick) (with a k at the end)?

**Comment by Frost** [comment]
It does seem a bit weird that a "No package with name ..." error prints out a bunch of XML containing `<Code>AccessDenied</Code>`. That might be confusing since that's not really the error. Speaking in HTTP status codes, it feels like a non-existing package should rather result in a 404 than a 403.

**Comment by ericmj** [comment]
@Frost This is how S3 works, it doesn't know if there is an object on that url or if you don't have access to it. We track this issue here: https://github.com/hexpm/hex/issues/314. Contributions would be appreciated.

**Comment by cedrico2016** [comment]
ohh  @Frost   Thank you a lot... i was writing it the whole time without "k" at the end. Now it's ok.. The dep has been correctly installed.
