### ISSUE TITLE
Fetch cached packages less often

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#33]
Fetch every time the first hour. After that fetch once every 24h(?).

Keep using conditional GETs.

Requires adding creation time of releases to the registry.

**Comment by josevalim** [comment]
@ericmj maybe a simpler idea is to simply store a counter per version in the registry. Every time a new package of the same version is re-published, you increment the counter. Check the counter in the registry with the one local to know if you need to fetch it again. The counter uses less space than a date and it seems to solve the problem equally?

**Comment by ericmj** [comment]
I like the counter but it doesn't save us much over a unix timestamp. Space isn't the big issue, the reason I haven't implemented this yet is because I want to figure out a way to still have somewhat reliable download stats.

**Comment by josevalim** [comment]
Good point.

One option is to put the information in the lock file and download based on that. I would argue today the download is skewed because we shouldn't count a download every time we run deps.get in a project if a dependency was already fetched.

**Comment by JamesS237** [comment]
The issue of skewed download counts (as mentioned my @josevalim) is addressed in hexpm/hex_web#51. If deemed necessary, I'd be happy to address it.

**Comment by josevalim** [comment]
Good point @JamesS237. We probably need to address that anyway because of build servers and what not. Honestly, we shouldn't worry about the stats and just do what is more efficient to users. If the user has already downloaded the package once, why download it again even if it is for another project?
