### ISSUE TITLE
Strict Semver for Hex Deps

### ISSUE THREAD

**Issue by mobileoverlord** [hexpm/hex#331]
## The Problem
Take the following scenario:

The application `:my_app` has a hex dependency on `:nerves ~> 0.4.2` and hex dependency `:nerves_system_qemu_arm ~> 0.9.0`
```elixir
defmodule MyApp.Mixfile do
  use Mix.Project
  # ...
  defp deps do
    [{:nerves, "~> 0.4.2"},
     {:nerves_system_qemu_arm, "~> 0.9.0"}]
  end
end
```

`:nerves_system_qemu_arm` also has a hex dependency on `:nerves ~> 0.4.0` 
```elixir
defmodule NervesSystemQemuArm.Mixfile do
  use Mix.Project
  # ...
  defp deps do
    [{:nerves, "~> 0.4.0"}]
  end
end
```

when running `mix deps.get` from within `:my_app` the following error is produced:
```sh
Running dependency resolution

Failed to use "nerves" (version 0.4.2) because
  nerves_system_qemu_arm (version 0.9.0) requires 0.4.0
  mix.lock specifies 0.4.2

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
``` 

## What I expected
This scenario exposes what I see to be an inconsistency in sem ver dependency resolution. The real example is when `:my_app` and its hex dep `nerves_system_qemu_arm` both declare `{:nerves, "~> 0.4.0"}` but the latest version in hex is `0.4.2` 

In this case I would expect that `mix deps.update nerves` should resolve to `:nerves 0.4.2` since all of the deps declare that scope of semver

## Example of it working this way elsewhere
An example of my reasoning towards inconsistency is illustrated in the following scenario:

The application `:a` has a path dependency on `:app_b ~> 0.4.2` and hex dependency `:nerves_system_qemu_arm ~> 0.9.0`
```elixir
defmodule A.Mixfile do
  use Mix.Project
  # ...
  defp deps do
    [{:nerves, "~> 0.4.0"},
     {:b, path: "../b"}]
  end
end
```

`:b` also has a hex dependency on `:nerves ~> 0.4.0` 
```elixir
defmodule B.Mixfile do
  use Mix.Project
  # ...
  defp deps do
    [{:nerves, "~> 0.4.0"}]
  end
end
```

when running `mix deps.get` from within `:a` it resolves `:nerves 0.4.2`
```
➜  a mix deps.get
Running dependency resolution
Dependency resolution completed
  distillery: 1.0.0
  nerves: 0.4.2
```

**Comment by ericmj** [comment]
It looks like nerves_system_qemu_arm declares its nerves dependency as "0.4.0" without "~>". See https://hex.pm/packages/nerves_system_qemu_arm/0.9.0.

**Comment by mobileoverlord** [comment]
wow, this is the second time I've embarrassed myself today. Thanks eric
