### ISSUE TITLE
Invalid `Unknown package` error

### ISSUE THREAD

**Issue by hzamani** [hexpm/hex#335]
While `prometheus` package exists on the [registry](https://hex.pm/api/packages/prometheus), running `mix deps.get` on a project with prometheus as dependency prints this message:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7429EFC7FC9509FB</RequestId><HostId>n5N5gLonrY7TxI7nZKn0TYxiEZ27sPSDxvjnp3KQ+6F8oaHQ4IIHe/RHpyAWO0+qdmglMzsqJsY=</HostId></Error>
Failed to fetch record for 'prometheus' from registry (using cache)
** (Mix) Unknown package prometheus in lockfile
```

**Comment by wojtekmach** [comment]
Might be caching issue, could you try this solution: https://github.com/hexpm/hex/issues/329#issuecomment-268071488

**Comment by hzamani** [comment]
That was it, thanks.

**Comment by hzamani** [comment]
Isn't it better to remove hex cache in `mix local.hex` command?

**Comment by josevalim** [comment]
It may be better to version the cache. Add an entry such as `{version, 1}` to the ets table and, after opening it, consult the version. If a different version, close the table and erase the cache file.

**Comment by ericmj** [comment]
We can start versioning when we need to do backwards incompatible changes :).

This could have been caused by a bug in earlier Hex versions where the VM could exit while writing the ets file. If this keeps happening we need to add some additional consistency checks to the file.
