### ISSUE TITLE
A task to clean cache?

### ISSUE THREAD

**Issue by bcat-eu** [hexpm/hex#344]
I've had an issue with the hex registry, it appeared not to know any of the packages. Something like that:

    mix deps.get
    ** (Mix) Unknown package gettext in lockfile

and that (without lock file)

    mix deps.get
    ** (Mix) No package with name phoenix_pubsub (from: mix.exs) in registry

turns out it was a cache problem, `rm ~/.hex/cache.ets` solved it for me, but before I got to it I had to do all kinds of googling, tracing, debugging etc. 

It would be nice to have something discoverable with e.g. `mix help | grep hex` or `mix help | grep deps`, like `mix hex.purge` that deletes the cache file.

**Comment by ericmj** [comment]
There shouldn't be any reason to clean the cache. We need to fix the bug that causes the cache to go into a bad state instead.

Did you recently upgrade to the latest hex version?

**Comment by bcat-eu** [comment]
I did upgrade today, but only as part of figuring out what the problem is, yesterday it all worked and as far as I can tell nothing changed. Also this is the very first time I had to clean the cache as well (and I get deps pretty often).

If I knew that it's about the cache file I'd save it and post here, but at the time I didn't know it, so I'm afraid it will be hard to reproduce unless someone else has the same problem.

I happen to still have the trace file though, not sure if it helps.
[trace.txt](https://github.com/hexpm/hex/files/713739/trace.txt)

**Comment by ericmj** [comment]
We don't need the cache file, the issue happens when the cache is corrupted. There is not much we can do after it has been corrupted.

Hopefully this issue has been fixed in the latest version of Hex. Please open a new issue if it happens again.
