### ISSUE TITLE
Manually Building a Cache

### ISSUE THREAD

**Issue by mbgardner** [hexpm/hex#345]
Hello, I work in an environment with limited internet access, so I've been building a Docker image with the entirety of hex.pm repository, along with the registry.ets file, and using it in offline mode. With the change to use the local cache file, this is no longer working and I get: ** (Mix) Hex is running in offline mode and the registry entry for package xxx is not cached locally. I've seen some references to new mix tasks that I think would address what I'm trying to do, but none of them look to be in the latest version. Is there any guidance for this use case?

**Comment by ericmj** [comment]
You can no longer cache the entire registry on your local machine. The dependencies you fetch will be cached, both the tarballs and the registry entries, but no other packages than your dependencies.

What you can do is run `mix deps.get` on all the projects you use to make sure the dependencies are cached and then copy the `~/.hex` directory to the Docker image.
