### ISSUE TITLE
Feature: Allow version to be specified when installing hex

### ISSUE THREAD

**Issue by dpehrson** [hexpm/hex#350]
## Situation

The way I handle development environments is to ship code with a Dockerfile and docker-compose configurations that allow a new developer to simply clone the repo and do `docker-compose up` to get started.

## Problem

Depending on when a developer clones the repo and builds the local images, there is no guarantee they will end up with images running the same version of hex. While this has not yet caused a problem, indeterminate builds are always a potential landmine.

## Solution?

Allow a hex version to be specified to `mix hex.local` to allow for repeatable builds.

**Comment by ericmj** [comment]
This will be added to Elixir when Hex hits 1.0.0. For now it's better to install the latest version rather than a specific version because an older version is more likely to be broken than latest since we are making changes to APIs.

**Comment by dpehrson** [comment]
@ericmj Great news, thanks for the quick reply. I understand the rapid development and look forward to things settling. In the meantime I will work around this on my end somehow.

Thanks again for all your hard work.
