### ISSUE TITLE
Check update is running too often

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#351]
Checked on `v0.15.0` and `master`.

```
~/baz% # disable wifi
~/baz% mix run -e ":timer.sleep(1000)"
Failed to check for new Hex version
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}
~/baz% mix run -e ":timer.sleep(1000)"
Failed to check for new Hex version
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}

~/baz% # enable wifi
~/baz% mix run -e ":timer.sleep(1000)"

~/baz% # disable wifi
~/baz% mix run -e ":timer.sleep(1000)"
Failed to check for new Hex version
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}
```

when I run `mix hex.info` on good connection it fetches the info and next time I call `mix` on no connection it does not check for updates anymore.

**Comment by ericmj** [comment]
We should only check version once a day. But it seems like the timer is not reset when the update check fails. The timer should always reset, regardless if the check was successful or not.

**Comment by elpikel** [comment]
Can I take care of this one?

**Comment by ericmj** [comment]
@elpikel Go ahead.

**Comment by elpikel** [comment]
@ericmj To make hex check version once a day we should just open Hex.Registry.Server and close in Mix.Tasks.Hex.Info. This will check for new version without force flag - which is probably what we need. Right now there is check_update used which checks for updates with force flag. Could you explain me the part with timer?

**Comment by ericmj** [comment]
@elpikel We run the check every time we start `Hex.Registry.Server` - not only for `hex.info`.

**Comment by elpikel** [comment]
@ericmj that's right.

**Comment by ericmj** [comment]
This should be fixed now. Please reopen if that isn't the case.
