### ISSUE TITLE
`mix deps.get` is painfully slow even if it is a no-op

### ISSUE THREAD

**Issue by myronmarston** [hexpm/hex#352]
In our umbrella application (which is probably larger than most Elixir apps; it's been under continuous development for 18+ months, has 47 child apps, and 74 external dependencies), `mix deps.get` has been getting slower and slower as the application has grown.  At this point, it takes about 3 minutes to run, even if no dependencies need to be installed or updated.  Our travis builds are dominated by the time they take to run `mix deps.get`, even though we are caching the `deps` directory in the hopes of having faster builds.  95% of our travis builds don't involve any dependency updates so it winds up being a no-op, but it still takes 3 minutes (out of about 5 total) to run `mix deps.get`.

It would be a big improvement for our productivity if `mix deps.get` was not so slow.  Is this something the hex team has plans on improving?  In particular, I'd love to see improvements around the performance of `mix deps.get` when there's nothing to do.  Our travis builds always need to include a call to `mix deps.get` in case there are new or updated dependencies but most of the time there's nothing to do.  Maybe hex could store some checksums in the `deps` directory from the last run of `mix deps.get`, and use that to quickly short circuit if there's nothing to do, instead of a doing a full dependency resolution?  Of course, we'd love to see dependency resolution get faster, too, if possible.  From my experience with Ruby's bundler I know that small tweaks to do things like pin more dependencies to exact versions can make a difference.   Would such a thing make a difference for `mix deps.get`, too?  Or are there other things we can try to make it faster?

Also, is there any info we can provide to help identify the source of the slowness?

Thanks!

**Comment by ericmj** [comment]
> From my experience with Ruby's bundler I know that small tweaks to do things like pin more dependencies to exact versions can make a difference. Would such a thing make a difference for mix deps.get, too?

There should be no need to pin dependencies in `mix.exs` if you keep your `mix.lock` file around.

> It would be a big improvement for our productivity if mix deps.get was not so slow. Is this something the hex team has plans on improving?

If there's anything we can do to make resolution more performant we would love to do it, but we need something to work with. This is the first report we have received in a long time about resolution being slow. If you can share anything that reproduces the slowness that would help out a lot, without that it would be mostly guess work unless you can investigate what is slow.

**Comment by josevalim** [comment]
Yes, I would recommend [measuring the times different parts of this file is executed](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep/converger.ex#L49-L116) to give us an estimate of where it is actually being slow. Especially those blocks:

1. https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep/converger.ex#L49-L116
2. https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep/converger.ex#L94
3. https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep/converger.ex#L100-L110

I would actually suspect Mix rather than Hex.

**Comment by wojtekmach** [comment]
Also, does the ~3min `deps.get` run happens only on Travis or for developer's builds it's slow as well? If the latter, perhaps the slowness is caused by the network and we should investigate that?

> Maybe hex could store some checksums in the deps directory from the last run of mix deps.get

If you haven't done that already, as a temporary workaround you might want to consider writing a `fast_deps.sh` script that essentially does what you're suggesting (with `if [ ... ]; then mix deps.get`)

**Comment by myronmarston** [comment]
> If you can share anything that reproduces the slowness that would help out a lot, without that it would be mostly guess work unless you can investigate what is slow.

I'll try putting together an example project demonstrating the project.

> Yes, I would recommend measuring the times different parts of this file is executed to give us an estimate of where it is actually being slow. Especially those blocks:

Thanks, I'll give that a shot.

> Also, does the ~3min deps.get run happens only on Travis or for developer's builds it's slow as well? 

It happens locally for developers as well.

> If you haven't done that already, as a temporary workaround you might want to consider writing a fast_deps.sh script that essentially does what you're suggesting (with if [ ... ]; then mix deps.get)

Yep, it's something we were already considering.  It would be nice if it wasn't necessary, though, so I'd rather spend my effort providing info to hopefully get this fixed in hex and/or mix.

**Comment by myronmarston** [comment]
@josevalim you were right about the mix operations you pointed out -- the vast majority of the time is there.  I applied [this patch](https://gist.github.com/myronmarston/8f42794daca161d97f3359e14ace3e86) to mix, which is easier to visualize with `git diff -w`:

``` diff
commit ff210553f1a66db745a32224ff69b57073f953c6
Author: Myron Marston <myron.marston@gmail.com>
Date:   Mon Feb 27 15:01:27 2017 -0800

    WIP: add monitor statements.

diff --git a/lib/mix/lib/mix/dep/converger.ex b/lib/mix/lib/mix/dep/converger.ex
index c90f38a..aef8146 100644
--- a/lib/mix/lib/mix/dep/converger.ex
+++ b/lib/mix/lib/mix/dep/converger.ex
@@ -47,12 +47,21 @@ defmodule Mix.Dep.Converger do
   See `Mix.Dep.Loader.children/1` for options.
   """
   def converge(acc, lock, opts, callback) do
+    monitor "converge/4", fn ->
       {deps, acc, lock} = all(acc, lock, opts, callback)
-    if remote = Mix.RemoteConverger.get, do: remote.post_converge()
+      if remote = Mix.RemoteConverger.get, do: monitor("remote.post_converge()", fn -> remote.post_converge() end)
       {topsort(deps), acc, lock}
     end
+  end
+
+  defp monitor(label, action) do
+    {micro_secs, value} = :timer.tc(action)
+    Mix.Shell.IO.info("#{label} took #{micro_secs / 1000} ms")
+    value
+  end
 
   defp all(acc, lock, opts, callback) do
+    monitor "all/4", fn ->
       main = Mix.Dep.Loader.children()
       main = Enum.map(main, &(%{&1 | top_level: true}))
       apps = Enum.map(main, &(&1.app))
@@ -88,7 +97,9 @@ defmodule Mix.Dep.Converger do
         # and we need to hit the remote converger which do external
         # requests and what not. In case of deps.loadpaths, deps and so
         # on, there is no lock, so we won't hit this branch.
-      lock = if lock_given?, do: remote.converge(deps, lock), else: lock
+        lock = monitor "lock_given?/remote.converge", fn ->
+          if lock_given?, do: remote.converge(deps, lock), else: lock
+        end
 
         deps = deps
                |> Enum.reject(&remote.remote?(&1))
@@ -98,6 +109,7 @@ defmodule Mix.Dep.Converger do
         # which is potentially stale. So remote.deps/2 needs to always
         # check if the data it finds in the lock is actually valid.
         {deps, rest, lock} =
+          monitor "get {deps, rest, lock} from all/7", fn ->
             all(main, apps, callback, rest, lock, env, fn dep ->
               if cached = deps[dep.app] do
                 {:loaded, cached}
@@ -105,12 +117,14 @@ defmodule Mix.Dep.Converger do
                 {:unloaded, dep, remote.deps(dep, lock)}
               end
             end)
+          end
 
         {reject_non_fulfilled_optional(deps), rest, lock}
       else
         {reject_non_fulfilled_optional(deps), rest, lock}
       end
     end
+  end
 
   defp all(main, apps, callback, rest, lock, env, cache) do
     {deps, rest, lock} = all(main, [], [], apps, callback, rest, lock, env, cache)
```

Making that change resulted in this output:

```
$ time mix deps.get
Running dependency resolution...
lock_given?/remote.converge took 202733.338 ms
get {deps, rest, lock} from all/7 took 157.304 ms
all/4 took 204108.866 ms
remote.post_converge() took 0.009 ms
converge/4 took 204113.692 ms
mix deps.get  176.07s user 21.15s system 96% cpu 3:24.83 total
```

At this point, should we close this issue and move it to elixir-lang/elixir?  What would be most helpful for me to provide to continue troubleshooting this?

**Comment by josevalim** [comment]
From your results it seems that remote.converge is the slowest one... so it
seems to be a Hex issue after all.

The next step then is to provide a group of dependencies that reproduce the
slow down. One way to do this is to get all deps before you call
remote.converge, getting all dependencies that belong to Hex.SCM (please
double check if this is the module name) and then print the app and
requirement. Something like this:

    for %{scm: Hex.SCM, app: app, requirement: req} <- deps, do: IO.inspect
{app, req}

I am not sure the fields are exactly that but it should get you moving.
This should list all of your Hex dependencies, you can put them in a brand
new mix.exs file as deps and see if it is also slow. If so, then please
post the mix.exs.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by myronmarston** [comment]
Thanks.  That snippet worked fine (you guessed the fields right!), and produced a list of 33 dependencies.  Here's the `mix.exs` for a fresh project I came up with to test it:

``` elixir
defmodule SlowHex.Mixfile do
  use Mix.Project

  def project do
    [app: :slow_hex,
     version: "0.1.0",
     elixir: "~> 1.4",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:my_dep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:my_dep, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:dialyxir, "~> 0.4"},
      {:ex_doc, "~> 0.11"},
      {:earmark, "~> 0.1"},
      {:process_tree_dictionary, ">= 1.0.0"},
      {:ex_json_schema, "~> 0.3"},
      {:quantum, ">= 1.6.1"},
      {:ex_statsd, ">= 0.5.3"},
      {:exvcr, ">= 0.8.4"},
      {:ex_aws, ">= 1.1.0"},
      {:httpoison, "~> 0.10"},
      {:poison, "~> 2.0"},
      {:sweet_xml, "~> 0.5"},
      {:ecto, ">= 2.1.0"},
      {:mariaex, ">= 0.7.7"},
      {:timex, ">= 3.1.5"},
      {:benchfella, "~> 0.2"},
      {:csv, "~> 1.2"},
      {:corsica, "~> 0.4"},
      {:plug, "~> 1.0"},
      {:public_suffix, ">= 0.2.0"},
      {:ex_syslogger, "~> 1.2"},
      {:relx, "~> 3.5"},
      {:gen_stage, "~> 0.11"},
      {:sentry, "~> 2.1"},
      {:recon_ex, ">= 0.9.1"},
      {:cowboy, "~> 1.0"},
      {:hackney, ">= 1.6.3"},
      {:phoenix, "~> 1.1"},
      {:phoenix_html, "~> 2.3"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_live_reload, "~> 1.0"},
      {:quixir, ">= 0.9.1"},
      {:tesla, "~> 0.5"},
    ]
  end
end
```

...but when I ran `mix deps.get`, it was very fast:

```
➜  slow_hex git:(master) ✗ time mix deps.get
{:dialyxir, "~> 0.4"}
{:ex_doc, "~> 0.11"}
{:earmark, "~> 0.1"}
{:process_tree_dictionary, ">= 1.0.0"}
{:ex_json_schema, "~> 0.3"}
{:quantum, ">= 1.6.1"}
{:ex_statsd, ">= 0.5.3"}
{:exvcr, ">= 0.8.4"}
{:ex_aws, ">= 1.1.0"}
{:httpoison, "~> 0.10"}
{:poison, "~> 2.0"}
{:sweet_xml, "~> 0.5"}
{:ecto, ">= 2.1.0"}
{:mariaex, ">= 0.7.7"}
{:timex, ">= 3.1.5"}
{:benchfella, "~> 0.2"}
{:csv, "~> 1.2"}
{:corsica, "~> 0.4"}
{:plug, "~> 1.0"}
{:public_suffix, ">= 0.2.0"}
{:ex_syslogger, "~> 1.2"}
{:relx, "~> 3.5"}
{:gen_stage, "~> 0.11"}
{:sentry, "~> 2.1"}
{:recon_ex, ">= 0.9.1"}
{:cowboy, "~> 1.0"}
{:hackney, ">= 1.6.3"}
{:phoenix, "~> 1.1"}
{:phoenix_html, "~> 2.3"}
{:phoenix_pubsub, "~> 1.0"}
{:phoenix_live_reload, "~> 1.0"}
{:quixir, ">= 0.9.1"}
{:tesla, "~> 0.5"}
Running dependency resolution...
lock_given?/remote.converge took 777.338 ms
get {deps, rest, lock} from all/7 took 63.04 ms
all/4 took 937.742 ms
remote.post_converge() took 0.014 ms
converge/4 took 940.857 ms
All dependencies up to date
mix deps.get  1.20s user 0.45s system 123% cpu 1.338 total
```

I'm heading home for the day but tomorrow I can try trimming our project down so we have all the umbrella context, since that appears to matter.  (Unless you have some other ideas for a simpler way to create a reproducible example?)

**Comment by josevalim** [comment]
@myronmarston if you copy the mix.lock file and put it alongside the new mix.exs, is it also fast or slow? If it is still fast, maybe the extra dependencies we send to Hex is slowing it down for some reason.

**Comment by myronmarston** [comment]
I extracted a stand-alone example project from our project.  It's basically our code base with everything but the `mix.exs` files deleted.  Here it is:

https://github.com/seomoz/slow-mix-deps-get

It's not taking quite as long (~ 2 minutes instead of 3 minutes) but it still demonstrates the problem, I think:

```
{:dialyxir, "~> 0.4"}
{:ex_doc, "~> 0.11"}
{:earmark, "~> 0.1"}
{:exvcr, ">= 0.8.4"}
{:process_tree_dictionary, ">= 1.0.0"}
{:httpoison, "~> 0.10"}
{:cowboy, "~> 1.0"}
{:csv, "~> 1.2"}
{:recon_ex, ">= 0.9.1"}
{:ex_syslogger, "~> 1.2"}
{:hackney, ">= 1.6.3"}
{:phoenix, "~> 1.1"}
{:phoenix_html, "~> 2.3"}
{:phoenix_pubsub, "~> 1.0"}
{:plug, "~> 1.0"}
{:phoenix_live_reload, "~> 1.0"}
{:relx, "~> 3.5"}
{:ecto, ">= 2.1.0"}
{:mariaex, ">= 0.7.7"}
{:ex_json_schema, "~> 0.3"}
{:gen_stage, "~> 0.11"}
{:timex, ">= 3.1.5"}
{:ex_statsd, ">= 0.5.3"}
{:poison, "~> 2.0"}
{:sentry, "~> 2.1"}
{:public_suffix, ">= 0.2.0"}
{:benchfella, "~> 0.2"}
{:quantum, ">= 1.6.1"}
{:corsica, "~> 0.4"}
{:quixir, ">= 0.9.1"}
{:ex_aws, ">= 1.1.0"}
{:sweet_xml, "~> 0.5"}
Running dependency resolution...
lock_given?/remote.converge took 124483.041 ms
get {deps, rest, lock} from all/7 took 47.899 ms
all/4 took 125637.61 ms
remote.post_converge() took 0.015 ms
converge/4 took 125641.667 ms
```

**Comment by ericmj** [comment]
Hex is slow because you add the same set of ~30 packages to each of your 44 applications. You should only add dependencies to the applications that need them.

When the resolver starts Mix passes 102 dependency requests to Hex. During the resolvers run each dependency is checked X times. To be honest, the resolver wasn't really built to handle this scenario. I will try to see what we can improve, we should be able to improve the resolution time when most dependencies are already locked.

As a workaround you can remove dependencies from apps that don't need them, that should give you a big improvement.

**Comment by ericmj** [comment]
I investigated more closely and it's in the override check [1] we are getting slow. An override check can take upwards up to 3 secs at the end of the resolver run. If we can optimize it should fix most of the performance issues.

[1] https://github.com/hexpm/hex/blob/master/lib/hex/resolver.ex#L183

**Comment by josevalim** [comment]
@myronmarston if you have deps that are shared across all apps, then I would recommend creating a base app that includes all of the shared dependencies and have all other apps depend on the base app exclusively instead of duplicating the same deps over and over again.

**Comment by myronmarston** [comment]
> Hex is slow because you add the same set of ~30 packages to each of your 44 applications.

What do you mean?  While we have a [global list of 30 packages](https://github.com/seomoz/slow-mix-deps-get/blob/6f4442523d747efea617afa891e0fb8a0887a9ce/mix_common.exs#L93-L160), that's just for purposes of keeping a centralized place where the version or other options are specified once--that way, when we want to upgrade a dependency that multiple sub-apps use, we do not have to update the version specifier in multiple `mix.exs` file.  I don't believe that list of 30 packages it being added as dependencies for all 44 sub-applications.  For example, our `s3` application [depends upon](https://github.com/seomoz/slow-mix-deps-get/blob/6f4442523d747efea617afa891e0fb8a0887a9ce/apps/s3/mix.exs#L18-L29) 2 of the in-umbrella applications and 6 external hex packages.  Each sub-application similarly names the in-umbrella apps it depends upon and the hex packages it depends upon, and the version info is looked up in the global list as needed.

Here's the expanded mix `project` keyword list for the `s3` application:

```
[elixir: "~> 1.2", build_embedded: false, start_permanent: false,
 preferred_cli_env: [test_all: :test, vcr: :test, "vcr.delete": :test,
  "vcr.check": :test, "vcr.show": :test],
 docs: [extras: ["README.md"], source_url: "https://github.com/seomoz/delorean",
  source_root: "/Users/myron/moz/slow-mix-deps-get"], version: "0.0.1",
 deps_path: "../../deps", lockfile: "../../mix.lock",
 build_path: "../../_build", config_path: "../../config/config.exs",
 elixirc_paths: [],
 deps: [{:test_util, [in_umbrella: true, only: :test]},
  {:runtime_config, [in_umbrella: true]}, {:util, [in_umbrella: true]},
  {:ex_aws, ">= 1.1.0", []},
  {:exvcr, ">= 0.8.4", [only: :test, runtime: false]},
  {:httpoison, "~> 0.10", []}, {:poison, "~> 2.0", []},
  {:process_tree_dictionary, ">= 1.0.0", [only: :test]},
  {:sweet_xml, "~> 0.5", []}], app: :s3]
```

The `deps` looks correct to me.

> As a workaround you can remove dependencies from apps that don't need them, that should give you a big improvement.

I'd love to apply such a work around if I could figure out how...

> @myronmarston if you have deps that are shared across all apps, then I would recommend creating a base app that includes all of the shared dependencies and have all other apps depend on the base app exclusively instead of duplicating the same deps over and over again.

I think our only dependency shared across all apps is our in-umbrella `util` app.  So I'm not sure how this approach could help us.

**Comment by josevalim** [comment]
@myronmarston what I meant is that you could move all shared dependencies to a project called "base". Then instead of depending on all 30 dependencies over and over, each project in the umbrella depends only on "base".

In any case, we have a fix that reduces the time from 3 minutes to 3 seconds. :)

**Comment by myronmarston** [comment]
> @myronmarston what I meant is that you could move all shared dependencies to a project called "base". Then instead of depending on all 30 dependencies over and over, each project in the umbrella depends only on "base".

I get that, but each app has a different subset of the full set of dependencies.  Having each app depend on all dependencies isn't something we want to do.

**Comment by myronmarston** [comment]
> In any case, we have a fix that reduces the time from 3 minutes to 3 seconds. :)

Awesome!  I'm looking forward to seeing that change :).

**Comment by josevalim** [comment]
@myronmarston to be clear, I am only talking about those dependencies: https://github.com/seomoz/slow-mix-deps-get/blob/master/mix_common.exs#L93-L160

Unless you are also talking about those dependencies as well. If so, then we are good. :D

**Comment by ericmj** [comment]
We have a fix https://github.com/hexpm/hex/commit/935e5f9eefc425ccb09af915d3546f308f918d7b in place on master. You can use master by cloning this repo and install it with `mix install`.

**Comment by myronmarston** [comment]
Thanks, @ericmj!  I can confirm it's much, much faster.

Any idea when a new hex release might drop with this included?

**Comment by ericmj** [comment]
> Any idea when a new hex release might drop with this included?

Hopefully within a week or two.

**Comment by myronmarston** [comment]
Any chance we could get a release this week?
