### ISSUE TITLE
RETIRED information may be lost on output

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#358]
The output of `mix deps.get` with Hex is quite verbose and that will unfortunately make it that users miss important warnings such as the new RETIRED checks. Here is a sample run from ExDoc:

```
Dependency resolution completed:
  certifi 1.0.0
  cmark 0.7.0
  earmark 1.1.1
  excoveralls 0.6.2
  exjsx 3.2.1
  hackney 1.6.6 RETIRED!
    (invalid)
  idna 4.0.0
  jsx 2.8.2
  metrics 1.0.1
  mimerl 1.0.2
  ssl_verify_fun 1.1.1
* Updating cmark (Hex package)
  Checking package (https://repo.hex.pm/tarballs/cmark-0.7.0.tar)
  Fetched package
* Updating excoveralls (Hex package)
  Checking package (https://repo.hex.pm/tarballs/excoveralls-0.6.2.tar)
  Fetched package
* Updating exjsx (Hex package)
  Checking package (https://repo.hex.pm/tarballs/exjsx-3.2.1.tar)
  Fetched package
* Updating hackney (Hex package)
  Checking package (https://repo.hex.pm/tarballs/hackney-1.6.6.tar)
  Fetched package
* Getting certifi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/certifi-1.0.0.tar)
  Using locally cached package
* Updating idna (Hex package)
  Checking package (https://repo.hex.pm/tarballs/idna-4.0.0.tar)
  Using locally cached package
* Getting metrics (Hex package)
  Checking package (https://repo.hex.pm/tarballs/metrics-1.0.1.tar)
  Using locally cached package
* Getting mimerl (Hex package)
  Checking package (https://repo.hex.pm/tarballs/mimerl-1.0.2.tar)
  Using locally cached package
* Getting ssl_verify_fun (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ssl_verify_fun-1.1.1.tar)
  Using locally cached package
* Updating jsx (Hex package)
  Checking package (https://repo.hex.pm/tarballs/jsx-2.8.2.tar)
  Fetched package
```

Unless I am looking at the screen and using colored output, it is likely that I will miss the retired warning. I would suggest for making the output less verbose. Such as:

```
Dependency resolution completed:
  certifi 1.0.0
  cmark 0.7.0
  earmark 1.1.1
  excoveralls 0.6.2
  exjsx 3.2.1
  hackney 1.6.6
   RETIRED! (invalid)
  idna 4.0.0
  jsx 2.8.2
  metrics 1.0.1
  mimerl 1.0.2
  ssl_verify_fun 1.1.1
* Updating cmark (Hex package)
* Updating excoveralls (Hex package)
* Updating exjsx (Hex package)
* Updating hackney (Hex package)
   RETIRED! (invalid)
* Getting certifi (Hex package)
  Using locally cached package
* Updating idna (Hex package)
  Using locally cached package
* Getting metrics (Hex package)
  Using locally cached package
* Getting mimerl (Hex package)
* Getting ssl_verify_fun (Hex package)
  Using locally cached package
* Updating jsx (Hex package)
```

**Comment by josevalim** [comment]
The `mix deps` also shows somewhat duplicated information:

```elixir
* excoveralls (Hex package) (mix)
  locked at 0.6.2 (excoveralls) 0e993d09
```

I believe the second `excoveralls` is only in case the application and package name are different. If that's the case... then we should only show it in such cases.

**Comment by michalmuskala** [comment]
How about showing additional summary of retired packages at the very end?

**Comment by josevalim** [comment]
@michalmuskala unfortunately not possible right now. We would need to first extend Mix.

**Comment by josevalim** [comment]
Actually @ericmj pointed we could use the post converge callback. So we should use that instead and also show it or after resolution OR during getting/updating.

**Comment by ericmj** [comment]
I think we should only print something for each checkout/update if there was an error or if running with `MIX_DEBUG=1` or some other debug flag (I think the output is really useful because it tells me if caching is working, but I am guessing most people don't care :)).

Remove the second line here:
```
* Updating idna (Hex package)
  Using locally cached package
```

The only downside with post_converge is that we need to track which packages we checked out in global state. Another alternative is to print the retired messages for everything in the lock, but maybe that can be annoying?

@josevalim Was it also intentional to move the retired message to its own line, because I think that's a good idea?

**Comment by josevalim** [comment]
It was intentional but I am indifferent. Maybe in the lock you only need to store that the package is retired and then you can lookup for the retirement message elsewhere. Is it stored in the registry or only on the web API? If it is in the registry, then you may want to include a limit as well so people do not spam the registry with large messages.

**Comment by michalmuskala** [comment]
I think printing the retirement messages for everything in lock file every time you run `mix deps.*` is perfectly fine.

**Comment by ericmj** [comment]
> Maybe in the lock you only need to store that the package is retired and then you can lookup for the retirement message elsewhere. [...] Is it stored in the registry or only on the web API?

I would really like to avoid adding more things to the lock but it's stored in the registry which is cached so it should be fine.

> If it is in the registry, then you may want to include a limit as well so people do not spam the registry with large messages.

There is 140 character limit on the message.

**Comment by josevalim** [comment]
@ericmj yes, so I think looking up in the registry on post_converge should be OK. It will be cheap compared to the cost of everything else.

**Comment by wojtekmach** [comment]
Should we still look into using post_converge hook, or what we merged in https://github.com/hexpm/hex/pull/461 is enough? Personally I think it's good enough right now: much less output in the usual case and so the warning at the top should be much more visible.

**Comment by ericmj** [comment]
Let's go with what @wojtekmach added in #461 for now. We can reevaluate later if we need to print in post converge but I would like to avoid it unless necessary because it brings additional global state we need to manage.
