### ISSUE TITLE
How do you use the `extra:` key?

### ISSUE THREAD

**Issue by pragdave** [hexpm/hex#360]
I'm trying to add metadata to a project using `extra:`.

In my `mix.exs`:

~~~elixir
  defp package do
    [
      name:        @name,
      files:       ["lib", "mix.exs", "README.md", "LICENSE.md", "template"],
      maintainers: @maintainers,
      licenses:    ["Apache 2.0"],
      links:       %{
        "GitHub" => @github,
      },
      extra:       %{ "type" => "a_template_for_mix_gen" },
    ]
  end
~~~

But when I `mix hex.publish` I get:

~~~
Publishing package...
[#########################] 100%
Validation error(s)
Publishing failed
  meta:
    extra: expected type map
~~~

Am I doing something wrong?

Dave

~~~
$  mix hex.info
warning: the archive nerves_bootstrap requires Elixir "~> 1.4.0" but you are running 
on v1.5.0-dev                                                                       
Hex:    0.15.0
Elixir: 1.5.0-dev
OTP:    19.2

Built with: Elixir 1.3.4 and OTP 18.3.4.4
~~~

**Comment by ericmj** [comment]
No, everything looks correct so this is a bug on the client or the server. We should have tests that cover this: https://github.com/hexpm/hex/blob/4be19ea6edd88dbad3f66f4c195643ed8d0820a3/test/support/release_samples.ex#L28.

@mobileoverlord Are you using this? If so, can you show us an example that works for you?

**Comment by pragdave** [comment]
is it an apiary error?

**Comment by mobileoverlord** [comment]
I have not had a chance to leverage this yet. We were going to use it in Nerves to expose some of the package contents to the search api.

**Comment by ericmj** [comment]
Thanks for the report.

The bug was that we didn't correctly convert the proplist back to a map on the server when parsing the package metadata for validation.

The package metadata stores maps as erlang proplists in the package tarball because we need to support clients using OTP versions where maps are not introduced yet.

**Comment by pragdave** [comment]
Ouch—the things you have to think about  :)

Thanks for looking into it.
