### ISSUE TITLE
Improve 'Publishing a Package' page to include ExDoc's :source_url

### ISSUE THREAD

**Issue by Qqwy** [hexpm/hex#361]
Because of a topic with an unrelated subject on the Elixir Forum, I started looking into how Mix and ExDoc ensure that the links in the documentation point to the source code that is hosted on GitHub.

It turns out that this is [part of the settings you can configure for ExDoc](https://github.com/elixir-lang/ex_doc#using-exdoc-with-mix), which are read out of the mix.exs file. More specifically, you can add the `:source_url` key to the `project` function in the `mix.exs` file, and it will do it properly.

I think that it is useful if more developers know about this, because it makes the documentation better. What would help in this, is if [the example `mix.exs` that is on the Publishing a Package](https://hex.pm/docs/publish#example-mix-exs-file) page on Hex.PM included this setting, and also an explanation with a link to ExDoc in the section about adding metadata.

ExDoc also consumes `:name` and `:homepage_url` in a similar fashion. Maybe, these can be added as well.

**Comment by ericmj** [comment]
That's a good idea, please open a PR on https://github.com/hexpm/hexpm.
