### ISSUE TITLE
Compilation using HEX_OFFLINE mode

### ISSUE THREAD

**Issue by umatomba** [hexpm/hex#367]
Hi @ericmj, @josevalim 

For some security reasons we should be sure that rebuilding of the application is reproducible.
Trying to compile the previously fetched code in the build mashine in `HEX_OFFLINE` mode i see the effect, that new hex needs to communicate with hex.pm to build his cache.

The compilation of the some source code and the fetching process are two different tasks, that should be splitted i think. 
I know i can take the cache.ets into the package, but this way is not declarative and clear.

After the mix hex processing was made one time, every dependency contains hex marker ./deps/gen_smtp/.hex: 
`gen_smtp,0.11.0,d90ff2f021fc86cb2a4259b1f2b177ab6e506676265e26454bf5755855adc956
rebar3`

is it not all what hex needs?

**Comment by ericmj** [comment]
If the dependencies have been fetched I think the hex manifest (deps/*/.hex) and the lockfile (mix.lock) should be enough to use dependencies.

Dependency fetching and compilation are already two separate tasks. When you run `mix compile` Hex should not even be started so I'm not sure why Hex is running. Can you show what commands you run and when you see that Hex makes HTTP calls and how you check it?

**Comment by umatomba** [comment]
> when you see that Hex makes HTTP calls and how you check it

hex don't make requests. I see the error from https://github.com/hexpm/hex/blob/master/lib/hex/registry/server.ex#L326

What i made:

```
[user@ubuntu]$ export HEX_OFFLINE=false

[user@ubuntu]$ mix deps.get

[user@ubuntu]$ ll ~/.hex
total 280K
-rw-rw-r-- 1 user user 280K Apr 25 08:16 cache.ets

[user@ubuntu]$ ll deps/gen_smtp/.hex
-rw-rw-r-- 1 user user 87 Apr 20 13:32 deps/gen_smtp/.hex

[user@ubuntu]$ cat deps/gen_smtp/.hex 
gen_smtp,0.11.0,d90ff2f021fc86cb2a4259b1f2b177ab6e506676265e26454bf5755855adc956
rebar3

[user@ubuntu]$ export HEX_OFFLINE=true
[user@ubuntu]$ rm ~/.hex -rf
[user@ubuntu]$ rm _build/ -rf


[user@ubuntu]$ mix compile
** (Mix) Hex is running in offline mode and the registry entry for package {"hexpm", "gen_smtp"} is not cached locally

[user@ubuntu]$ cat mix.lock |grep gen_smtp
  "gen_smtp": {:hex, :gen_smtp, "0.11.0", "d90ff2f021fc86cb2a4259b1f2b177ab6e506676265e26454bf5755855adc956", [:rebar3], [], "hexpm"},


RM gen_smtp ...

[user@ubuntu]$ cat deps/plug/.hex 
plug,1.3.4,b4ef3a383f991bfa594552ded44934f2a9853407899d47ecc0481777fb1906f6

[user@ubuntu]$ mix compile

** (Mix) Hex is running in offline mode and the registry entry for package {"hexpm", "plug"} is not cached locally
```

**'Hex/0.16.0 (Elixir/1.4.1) (OTP/19.2)'**

**Comment by ericmj** [comment]
@umatomba This looks like a regression indeed. I will investigate.

**Comment by ericmj** [comment]
I can not reproduce this. Can you confirm that it's still an issue on the latest Hex version? If you can still reproduce please provide a sample project.
