### ISSUE TITLE
Timeouts when publishing

### ISSUE THREAD

**Issue by fhunleth** [hexpm/hex#370]
At times, `mix hex.publish` will fail with `:timeout` errors for both the package and documentation uploads. The failure can be repeated for minutes at a time and then a half hour or a couple hours later everything works. No other internet connection issues appear to be happening. The hex.pm website and hex dependency downloads/updates appear to work fine.

Watching Wireshark, it looks like an SSL connection is established but very little or no data is uploaded. 

If/when then happens again, I'll try to gather more data.

**Comment by fhunleth** [comment]
It's happening again. A log is attached below. Each time it says 100% below there was a long delay.

```
$ mix hex.publish
Passphrase: 
Publishing elixir_ale 1.0.0
  Dependencies:
    elixir_make ~> 0.4 (app: elixir_make)
  Files:
    lib/elixir_ale.ex
    lib/elixir_ale/gpio.ex
    lib/elixir_ale/i2c.ex
    lib/elixir_ale/spi.ex
    src/ale_main.c
    src/erlcmd.c
    src/erlcmd.h
    src/gpio_port.c
    src/i2c_port.c
    src/spi_port.c
    src/linux/i2c-dev.h
    mix.exs
    README.md
    LICENSE
    Makefile
  App: elixir_ale
  Name: elixir_ale
  Description: Elixir access to hardware GPIO, I2C, and SPI interfaces.
  Version: 1.0.0
  Build tools: mix, make
  Licenses: Apache-2.0
  Maintainers: Frank Hunleth
  Links: 
    GitHub: https://github.com/fhunleth/elixir_ale
  Elixir: ~> 1.2
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct
Proceed? [Yn] 
Building docs...
make: Nothing to be done for 'all'.
Docs successfully generated.
View them at "doc/index.html".
Publishing package...
[#########################] 100%
Publishing failed
:timeout
Publishing docs...
[#########################] 100%
Publishing docs failed
:timeout
```

**Comment by ericmj** [comment]
It's possible it is related to this bug: https://bugs.erlang.org/browse/ERL-420. If you are on OTP 19.3.1 can you try an earlier version?

**Comment by fhunleth** [comment]
I think that you're right about it being related to ERL-420:
```
$ mix hex.info
Hex:    0.16.0
Elixir: 1.4.2
OTP:    19.3
```
Believe it or not, hex is working for me again. I'll leave 19.3.1 installed and as soon as it fails, I'll try an earlier version.

Thanks!!!

**Comment by fhunleth** [comment]
Hmm. I'm having the same issue again. I reverted OTP versions. Now I've reproduced the issue with:
```
$ mix hex.info
Hex:    0.16.0
Elixir: 1.4.4
OTP:    19.0.7
```
and
```
$ mix hex.info
Hex:    0.16.0
Elixir: 1.4.4
OTP:    19.2.3

Built with: Elixir 1.4.2 and OTP 18.3.4.4
```

**Comment by fhunleth** [comment]
One more clue: this appears to be Linux-specific (Ubuntu 16.04.2 LTS). The issue is reproducible for me right now and a Mac on the same network isn't affected.

**Comment by jessiahr** [comment]
I ran into this issue today and I found that the root cause for me was that the node_modules folder was being included in the mix package. It seems that this makes the upload step take too long and it then times out. Hopefully this helps someone in the future.

**Comment by ericmj** [comment]
@jessiahr Are you getting the same error as @fhunleth?

```
Publishing package...
[#########################] 100%
Publishing failed
:timeout
Publishing docs...
[#########################] 100%
Publishing docs failed
:timeout
```

**Comment by jessiahr** [comment]
Yes, the only difference was the first of the two progress bars would only make it halfway.

**Comment by edgurgel** [comment]
Can we have a configurable timeout or maybe just up the default for something longer?

**Comment by ericmj** [comment]
I increased the default timeout to 60s when pushing tarballs and added the HEX_HTTP_TIMEOUT environment variable for configuring it.

**Comment by edgurgel** [comment]
Wow that's awesome! Thanks, @ericmj <3
