### ISSUE TITLE
timeouts with mix deps.get

### ISSUE THREAD

**Issue by ngw** [hexpm/hex#374]
Hi, I'm having a very weird issue when trying to get the dependencies of a project. Weird because none of my collegues have the same problem, and the file that hex claims to return a timeout downloads just fine.

ngw@blackstar ~/ uname -a
Linux blackstar 4.9.24-1-MANJARO #1 SMP PREEMPT Fri Apr 21 08:32:28 UTC 2017 x86_64 GNU/Linux

ngw@blackstar ~/hedging-ledger mix hex.info
Hex:    0.16.0
Elixir: 1.4.2
OTP:    19.3

Built with: Elixir 1.4.2 and OTP 18.3.4.4

* Getting conform (Hex package)
  Checking package (https://repo.hex.pm/tarballs/conform-2.1.1.tar)
Request failed (:timeout)
** (Mix) Package fetch failed and no cached copy available

https://repo.hex.pm/tarballs/conform-2.1.1.tar doesn't appear to have any timeout problem, changing version of conform doesn't make any difference.

mix.exs: https://gist.github.com/ngw/f16ef4460ce5ee75740f565f3d494957

**Comment by ericmj** [comment]
How long does it take until you get the timeout? Please run `time mix deps.get`.

**Comment by ngw** [comment]
Appears to be a real timeout:

mix deps.get  2.77s user 0.54s system 17% cpu 18.457 total

**Comment by ericmj** [comment]
The package is ~2mb which is bigger than most packages, so if you have slower than usual internet connection this can cause timeouts.

We should raise the default timeout and make the value configurable.

**Comment by ngw** [comment]
So, the timeout is not if a server doesn't answer in 15 seconds, but if the operation takes 15 seconds to complete? Can I say it seems a very bad idea?

**Comment by ericmj** [comment]
Closing this since there hasn't been any more feedback.

**Comment by sstine** [comment]
Would be great if this timeout was configurable

**Comment by ericmj** [comment]
It's not possible without creating a new http client.

**Comment by mjbaig** [comment]
Why is this closed. It seems like this should be an issue, right?

**Comment by ricoz** [comment]
Downlaod the .tar package manually and mv to ~/.hex/packages. Repeat for other timed out packages.

**Comment by michaelstalker** [comment]
Although I could download `.tar` packages to cache them, raising the timeout would be helpful. Would you consider re-opening this issue?

**Comment by ericmj** [comment]
We have raised the timeout to 60 seconds and you can configure your own timeout value. Check out `mix help hex.config`.

**Comment by michaelstalker** [comment]
Thanks! I don't think this change made it into the `0.17.1` tag, which is the most recent one. Would you be willing to bump the minor or patch version, and include the timeout code?

**Comment by ericmj** [comment]
We are going to release a new version within the coming days. In the mean time you can use master by cloning this repo and running `mix install`.
