### ISSUE TITLE
`mix test` executes hex'es integration tests by default

### ISSUE THREAD

**Issue by ysukhoverkhov** [hexpm/hex#379]
Hi, I cloned the `hex` repo, run `mix test` and it tried to run integration tests which should not be the case according to readme. 

Could be fixed like this: https://github.com/ysukhoverkhov/hex/pull/1

The first time I write something in elixir, could violate code conventions or something since I basically have no idea what am I doing.

**Comment by ericmj** [comment]
I think the current behaviour is correct so we should rather update the readme to mention `--exclude integration` instead of `--include integration`.

**Comment by whatyouhide** [comment]
I think this can be closed since #380?
