### ISSUE TITLE
Hex not available for elixir version < 1.4.4

### ISSUE THREAD

**Issue by skylerparr** [hexpm/hex#385]
’m getting `(Protocol.UndefinedError) protocol Enumerable not implemented for nil` when running `$ mix local.hex` for elixir version `1.4.0`

When attempting to pull any version from Hex I'm getting permission denied. Is hex no longer available for elixir version 1.4.0?

**Comment by josevalim** [comment]
Do you have a full stacktrace?

**Comment by skylerparr** [comment]
# mix local.hex
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1776: Enum.reduce/3
    (elixir) lib/uri.ex:434: URI.nillify/1
    (elixir) lib/uri.ex:405: URI.parse/1
    (mix) lib/mix/utils.ex:467: Mix.Utils.url?/1
    (mix) lib/mix/utils.ex:375: Mix.Utils.read_path/2
    (mix) lib/mix/local.ex:139: Mix.Local.read_path!/2

**Comment by wojtekmach** [comment]
could you provide some more information? what OS? are you using docker etc? Do you have any Mix/Hex-related environment variables set (like HEX_MIRROR)? Could you paste the stacktrace of permission denied error?

Hex supports all Elixir 1.0+ versions.

**Comment by skylerparr** [comment]
I'm running Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-92-generic x86_64) on aws. Installing elixir via: 
`apt-get install -y elixir=1.4.0-1`
`apt-get install -y elixir=1.4.1-1`
`apt-get install -y elixir=1.4.2-1`

They all produce the same error.

`apt-get install -y elixir=1.4.4-1`

does not produce the error.

No environment variables being set. This is a base installation of Ubuntu.

**Comment by skylerparr** [comment]
Not using docker. Getting permission denied xml from hex.pm when running curl.

**Comment by ericmj** [comment]
It could be that you have `HEX_MIRROR` set or maybe you are using elixir with OTP 20.

> Not using docker. Getting permission denied xml from hex.pm when running curl.

That's expected.

**Comment by skylerparr** [comment]
I think it's related to OTP 20 RC. I downgraded all of erlang to OTP 19 and it appears to be working.

**Comment by ericmj** [comment]
> I think it's related to OTP 20 RC. I downgraded all of erlang to OTP 19 and it appears to be working.

Yeah, that's it. Regexs are broken on OTP 20 and Elixir 1.4.
