### ISSUE TITLE
mix test --exclude integration not working.

### ISSUE THREAD

**Issue by 6aKa** [hexpm/hex#386]
I add IO.inspect.ExUnit.configuration in test_helper.exs.
Run mix test without exclude
> user@home:~/Projects/hex> mix test
> [exclude: [:skip], assert_receive_timeout: 100, autorun: false, trace: false,
> timeout: 60000, capture_log: false, formatters: [ExUnit.CLIFormatter],
> colors: [], stacktrace_depth: 20, included_applications: [],
> case_load_timeout: 60000, include: [], refute_receive_timeout: 100]
>Unable to find ../hexpm, make sure to clone the hexpm repository into it to run integration tests or set
> HEXPM_PATH to its location

Run mix test with exclude
> user@home:~/Projects/hex> mix test --exclude integration
> [exclude: [:skip], assert_receive_timeout: 100, autorun: false, trace: false,
> timeout: 60000, capture_log: false, formatters: [ExUnit.CLIFormatter],
> colors: [], stacktrace_depth: 20, included_applications: [],
> case_load_timeout: 60000, include: [], refute_receive_timeout: 100]
> Unable to find ../hexpm, make sure to clone the hexpm repository into it to run integration tests or set
> HEXPM_PATH to its location

Info
> user@home:~/Projects/hex> mix hex.info
> Hex:    0.16.0
> Elixir: 1.4.4
> OTP:    18.3.4.4
>
>Built with: Elixir 1.4.2 and OTP 18.3.4.4

**Comment by wojtekmach** [comment]
Thanks for the report, the fix is on master.
