### ISSUE TITLE
Include metadata.config in deps

### ISSUE THREAD

**Issue by fishcakez** [hexpm/hex#395]

**Comment by ericmj** [comment]
What should we call the file we put in `deps/mydep` and what should the behaviour be if a file with that name already exists?

I propose `hex_metadata.config` and we should not write file if a conflicting file exists and instead print a warning. Maybe also print a warning (later error) if a file with that name is included when publishing?

**Comment by milmazz** [comment]
@ericmj Is someone working on this?

**Comment by ericmj** [comment]
@milmazz No, it's up for grabs.

**Comment by milmazz** [comment]
@ericmj ok, I'll work on this issue.
