### ISSUE TITLE
execute permissions are being stripped

### ISSUE THREAD

**Issue by mobileoverlord** [hexpm/hex#404]
Nerves leverages several shell scripts and files that are included as part of the hex package that require execute permissions to be set. Hex used to store the permissions for these files but no longer does.

Here is an example of the difference between the `create-build.sh` file that is part of `nerves_system_br`

`nerves_system_br` 0.13.3
`-rwxr-xr-x   1 jschneck  staff   4.5K Aug  6 15:40 create-build.sh`
`nerves_system_br` 0.13.4
`-rw-r--r--   1 jschneck  staff   4.5K Aug  7 11:27 create-build.sh`

This issue seems to be happening across the board as we are hitting against it in our network stack too.

**Comment by ericmj** [comment]
@mobileoverlord Sorry, this was a regression in the last release. It has been fixed on master, you can use master by cloning this repo and running `mix install`.

**Comment by mobileoverlord** [comment]
❤️  Thanks Eric
