### ISSUE TITLE
Problems with dependencies, only: :test and private hex packages

### ISSUE THREAD

**Issue by bitboxer** [hexpm/hex#416]
I am seeing a weird behaviour right now on our system when using private hex packages and I am not sure if this is a bug.

I have a phoenix app that includes 2 hex private hex packages. The deps looks kinda like this:

```elixir
defp deps do
   [
      {:phoenix, "~> 1.2"},
      {:package_a, "~>1.0.0", organization: "private"},
      {:package_b, "~>1.0.0", organization: "private", only: :test}
   ]
end
```

Both package_a and package_b have a dependency on the timex library. The phoenix app also needs the timex library, but doesn't declare it in its deps. And now to the weird part: If one of the 2 hex packages has the `only: :test` attribute, Timex will not be available even if the other hex package also declares it depends on it.

So is this a bug?

**Comment by ericmj** [comment]
It sounds like a bug when you describe but it is hard to understand the whole dependency tree. Please run `mix deps.tree` and include it in the issue?

When you say that timex is not available do you mean it's not available when you run the application with mix `mix phx.server` or when you run it as a release?

Generally, if you have a dependency on a package you should declare it on every level where you depend on it. So I would recommend adding timex to your phoenix app also.

**Comment by bitboxer** [comment]
Okay, I take it back. After looking at it again after 2 days it is a problem in how we defined the dependencies in the child packages. Sorry 👍 . And yes, I added timex to the parent app now, just to be on the safe side.
