### ISSUE TITLE
certificate unknown - failed_to_decode_certificate

### ISSUE THREAD

**Issue by maierru** [hexpm/hex#417]
$ mix local.hex                                                    

14:43:11.485 [error] SSL: :certify: ssl_handshake.erl:420:Fatal error: certificate unknown - failed_to_decode_certificate

** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:tls_alert, 'certificate unknown'}}]}

Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.

$ curl -I https://repo.hex.pm/installs/hex-1.x.csv
HTTP/1.1 200 OK
...

**Comment by ericmj** [comment]
What's your OTP and Elixir versions?

**Comment by maierru** [comment]
$ mix -v
Erlang/OTP 21 [DEVELOPMENT] [erts-9.0.2] [source-1308dd415] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe]

Mix 1.6.0-dev (78872181c) (compiled with OTP 21)

**Comment by ericmj** [comment]
Does it work if you use stable OTP 20? Are you using default settings so that you are connecting to hex.pm?

**Comment by ericmj** [comment]
Ping?

**Comment by maierru** [comment]
It's work with otp20, I think we can close the issue.
