### ISSUE TITLE
Is HEX_HOME env var mentioned somewhere in the documentation?

### ISSUE THREAD

**Issue by ivan-kolmychek** [hexpm/hex#420]
I wanted to change where hex keeps the cache but haven't found anything like `MIX_ARCHIVES` env var in documentation.

Closest thing I found to the list of supported env vars was [this section](https://hex.pm/docs/tasks#hex_config).

After a bit of searching in code, I found the `HEX_HOME` env var, which seems to be what I was looking for.

Should it be added to documentation somewhere?

(if not, feel free to close the issue; it may still be helpful to people this way 'cause it will be searchable)

**Comment by ericmj** [comment]
It seems like it was accidentally removed. It should be added to the documentation of `hex.config.

**Comment by wojtekmach** [comment]
Thanks for the report @ivan-kolmychek!
