### ISSUE TITLE
Improve display and warnings when publishing private packages

### ISSUE THREAD

**Issue by brweber2** [hexpm/hex#424]
In order to publish a private package you run:
```
mix hex.publish --organization <org-name>
```

If you forget to add the --organization flag it publishes your private code **publicly**. I think that it should publish to the private repo by default if :organization is in mix.exs. If someone wishes to publish a private package publicly then they could use a flag to indicate they they do not want the default behavior. As a (future) paying customer I do not want my private packages ending up on hex.pm and if the mistake happens I only have one hour to undo it. So if I don't notice immediately my code will remain public until an admin removes it.

My short term fix for this has been to add an alias, but it seems like the default behavior is not "safe".

**Comment by josevalim** [comment]
I agree that if you put an `:organization` under the `:package` key in the mix.exs then you should always publish under that organization.

**Comment by ericmj** [comment]
@brweber2 Can you show your mix.exs file? The `:organization` key should be added under the `:package` key. It will not work if you add it directly under `def project`.

**Comment by brweber2** [comment]
Ah, we have it directly in the keyword list in :project.  So that is where we went wrong, but I’m sure we won’t be the last group to do this. The docs are technically correct, but it is very subtle that the config shown is package and not project.

Thanks for clarifying this!

**Comment by josevalim** [comment]
@ericmj given this can be a very sensitive issue, maybe it is worth checking for an `:organization` key being misplaced?

**Comment by wojtekmach** [comment]
I think in this particular case it makes sense to raise an error if we detect misplaced organisation/organization (easy to make typo from different en speaking countries)

What we can also do is make it prominent to which repo we are publushing before hitting "Y", perhaps by using bold and/or colored text and putting the message in a separate line.

**Comment by josevalim** [comment]
Yes, maybe say "PUBLICLY" on the regular publishing messages or even have a separate workflow for publishing for orgs... although that wouldn't necessarily address the muscle memory issue.

**Comment by ericmj** [comment]
I agree with all points.

  * Check for British spelling `:organisation` and warn
  * Check if any options under `:package` are given under the root and warn
  * Make it more clear than it is today if you're pushing to the public repository or a private one

**Comment by brweber2** [comment]
Ah, we have it directly in the keyword list in :project.  So that is where we went wrong, but I’m sure we won’t be the last group to do this. The docs are technically correct, but it is very subtle that the config shown is package and not project.

Thanks for clarifying this!

**Comment by ericmj** [comment]
Also improved in https://github.com/hexpm/hex/pull/419. Thanks @wojtekmach.
