### ISSUE TITLE
Terrible error message caused by download failure

### ISSUE THREAD

**Issue by jjl** [hexpm/hex#427]
[error output](https://gist.github.com/jjl/4de29d6da95b5cda359b19a60b6a225c)

What I think is happening is that the file is failing to write (which should trigger an error, but not this one...)

**Comment by jjl** [comment]
Output of `mix hex.info`:

```
Hex:    0.17.1
Elixir: 1.5.1
OTP:    20.0

Built with: Elixir 1.5.1 and OTP 18.3
```

**Comment by ericmj** [comment]
Yep, we should handle this better.
