### ISSUE TITLE
API change?

### ISSUE THREAD

**Issue by pragdave** [hexpm/hex#430]
It looks like `Hex.API.Package.search` got changed from taking 1 parameter to taking two.

Any chance we could have the one parameter version back for a while, with deprecation warnings, so I can migrate code that uses it?

Cheers

Dave

**Comment by ericmj** [comment]
Unfortunately nothing in the Hex project is public API. If you need to access the HTTP API you need to make direct HTTP requests or use a library for it. You can find the documentation for the API here: https://github.com/hexpm/specifications/blob/master/http_api.md.

**Comment by pragdave** [comment]
Do you know of a library? Otherwise I'm going to copy hex/http and api/package source, which seems a little ugly.

**Comment by ericmj** [comment]
Sorry no. There might not be one yet.

**Comment by pragdave** [comment]
Cool.

Thanks for the quick response.


Dave

**Comment by wojtekmach** [comment]
@pragdave here's a minimal snippet that makes request to API and returns erlang terms:

```elixir
:inets.start()
:ssl.start()
url = 'https://hex.pm/api/packages?search=ecto'
headers = [
  {'user-agent', 'test'},
  {'accept', 'application/vnd.hex+erlang'},
]
{:ok, {{_, 200, _}, _, body}} =
  :httpc.request(:get, {url, headers}, [], [body_format: :binary])

IO.inspect :erlang.binary_to_term(body)
```

this is essentially what `Hex.API` is doing (minus workarounds aroung httpc, retrying logic etc).
If you're building an app, I'd consider _not_ using `:httpc` and instead use e.g. `hackney`, `httpoison` etc. `:httpc` was a big source of bugs in hex.

**Comment by pragdave** [comment]
Many thanks for that.
A suggestion: I’m currently using the API to search for templates in mix_generator. This always runs in the context of mix, and always has hex available and running.
So would it be possible to make API/ first class? I’d be happy to document it, and to help keep it up to date.
For example, the search change could just be
def search(term), do: search(nil, term)
Dave

On Thu, Oct 5, 2017 at 6:32 PM, Wojtek Mach <notifications@github.com> wrote:
@pragdave [https://github.com/pragdave] here's a minimal snippet that makes request to API and returns erlang terms:

:inets.start()
:ssl.start()
url ='https://hex.pm/api/packages?search=ecto'
headers = [
  {'user-agent', 'test'},
  {'accept', 'application/vnd.hex+erlang'},
]
{:ok, {{_, 200, _}, _, body}} =:httpc.request(:get, {url, headers}, [], [body_format::binary])

IO.inspect :erlang.binary_to_term(body)

this is essentially what Hex.API is doing (minus workarounds aroung httpc, retrying logic etc).
If you're building an app, I'd consider not using :httpc and instead use e.g. hackney , httpoison etc. :httpc was a big source of bugs in hex.
