### ISSUE TITLE
Forgetting to include files?

### ISSUE THREAD

**Issue by tmbb** [hexpm/hex#435]
There is a kind of bug that only shows up when a package is downloaded from Hex. This happens when the package owner forgets to include some files. Everything seems right when the package is tested, because it uses the local code, and bugs only appear when the package is downloaded by someone else. This is not a theoretical concern: https://github.com/elixir-lang/ex_doc/issues/792

I'd like to bring forward some suggestions to mitigate this problem:

1. Go from a whitelist of files to a blacklist. This makes sure everything is included by default (except for obvious things like `deps` and `build`, but I can see people uploading secret credentials to Hex this way. **I don't think this option is safe.**

2. When the user publishes the package for the first time, list the directories files that are *left out* and ask for confirmation. After the first version has been published, store the filenames somewhere and ask again if the user leaves out different files

3. Provide a `hex.test` that "publishes" the package to a dummy server, downloads it from the server and runs the test suite. This is the most robust option, but also the hardest one to implement I wonder if this should be left to an external package.

**Comment by ericmj** [comment]
Unfortunately none of the solutions you suggested would have helped for the ex_doc bug.

1. As you said a blacklist is not safe because of credentials and it's just as easy to accidentally include useless files as it is to forget to include necessary files.
2. This is not the first time the ex_doc package is published. The first time a package is published it usually doesn't matter if there are bugs in the package because no one is using yet. When the author notices the issue they can just publish a new version and no one was affected.
3. Test files are not included in the package so this is not possible. Just because the test suite passes doesn't mean the package would work for end users, for example tests run in the test env and dependencies in prod env. It would also mean we have to reimplement a full CI which is just not possible for us, this is a huge task and would likely require more work than has been put into Hex so far.

`hex.build` + #261 could be used to test this, but it requires users to manually test their package before publishing which I doubt many would do. Maybe we could help by automating it but it would still require maintainers to write special tests for when the package is used as a dependency since these tests would be different from the "in-project" tests.

**Comment by ericmj** [comment]
It looks like ex_doc embeds the formatter files, but it doesn't use `@external_resource` which is odd (does @josevalim know why?). If it did use `@external_resource` we could use it to help detect if files used for compilation are not included in the package. This would require compiling in `prod` first which could be annoying for publishing.

**Comment by tmbb** [comment]
> 2. This is not the first time the ex_doc package is published. The first time a package is published it usually doesn't matter if there are bugs in the package because no one is using yet. When the author notices the issue they can just publish a new version and no one was affected.

That's not exactly what I've said. The workflow I had in mind was the following:

1. First time the package is published, the author leaves out files `a.txt` and `b.txt`. Hex will ask: "Do you want to leave out files `a.txt` and `b.txt` from the package [yN]?" If the user answers "yes", those files are added to a `.hex_left_out_files`, and hex won't ask about them again.

2. Second version of the paclage: the author leaves out files `a.txt`, `b.txt` and `c.txt`. Hex will look at the file above and diff the file list. Only the `c.txt` file is new. It will ask: "You have added some new files to the repo. Do you want to leave out the file `c.txt` [yN]?"

Maybe this time I've made myself clear. This feature would have prevented the bug (assuming the owner doesn't just blindly answer yes, of course).

**Comment by tmbb** [comment]
> Test files are not included in the package so this is not possible.

You could add a new keyword, like `:text_files`, where the user could add the testing directory. Then you'd merge the package with the text directory and run the texts.

> Just because the test suite passes doesn't mean the package would work for end users, for example tests run in the test env and dependencies in prod env. It would also mean we have to reimplement a full CI which is just not possible for us

Of course, but it would probably help catch many bugs, right? The goal here is not to have a full CI pipeline, only detecting the lack of certain artifacts that might not have been included. If running the tests in `:dev` or `:test` is good enough to test the local code, it's probably good enough to test a package you've downloaded.

Actually, now that I think it though, you don't even need to upload and download the package. You can just copy the files to a local directory and run the tests from there.

**Comment by ericmj** [comment]
> Maybe this time I've made myself clear. This feature would have prevented the bug (assuming the owner doesn't just blindly answer yes, of course).

This could work but I am not a fan of introducing more dialogues to the publishing process or adding more files to source control that is only used to detect mistakes with package files.

> Of course, but it would probably help catch many bugs, right? The goal here is not to have a full CI pipeline, only detecting the lack of certain artifacts that might not have been included. If running the tests in :dev or :test is good enough to test the local code, it's probably good enough to test a package you've downloaded.

As long as you are running tests you need a full CI environment. How are we supposed to test packages such as ecto without providing multiple variants and versions of databases for example? If you build this service we would be happy to integrate with Hex though, but the Hex team is not going to build or maintain it.

**Comment by tmbb** [comment]
> This could work but I am not a fan of introducing more dialogues to the
publishing process or adding more files to source control that is only used
to detect mistakes with package files.

Yes, I understand the tradeoff, and I'm not a big fan of that solution
either.

> How are we supposed to test packages such as ecto without providing
multiple variants and versions of databases for example?

I was thinking about tests that would be run in the owners's, not on your
servers. It would be just a question o running `mix test` in the
developper's own machine. Nothing more. But you're right and it probably
shouldn't belong to Hex core in any case.

**Comment by wojtekmach** [comment]
> It would be just a question o running `mix test` in the
developper's own machine.

if you want to build a service/script that automates it, one idea is to have `smoke_test.sh` that you run before publishing and/or on CI:

```
#!/bin/bash

# build package
mix hex.build

# extract package (fwiw, we could make it easier from Hex)
mkdir -p pkg pkg/contents && tar xf ex_doc-0.18.0.tar -C pkg && tar xzf pkg/contents.tar.gz -C pkg/contents

# compile app and run docs on it
cd pkg/contents && MIX_ENV=prod mix do deps.get, compile

# run the actual smoke test, for ex_doc it's generating it's docs. This would have caught the regression
mix docs
```

**Comment by wojtekmach** [comment]
if it's just a matter of making sure that all files are present, another solution is to have some kind of manifest file under version control: https://github.com/seattlerb/minitest/blob/master/Manifest.txt and before you release you check if manifest changed.

Probably not appropriate for Hex but could be a fit for tool like https://github.com/wojtekmach/shipit

**Comment by tmbb** [comment]
> Probably not appropriate for Hex but could be a fit for tool like https://github.com/wojtekmach/shipit

So THIS is the package I've been looking for all week! Thanks :)

**Comment by josevalim** [comment]
@wojtekmach beautiful, I have added your script to ex_doc but having something like that as part of Hex could really be helpful. :heart:

**Comment by Gazler** [comment]
This same issue tripped me up when publishing cowlib 2.0 as it added a new file in the `include` directory that was not present in `:files`. I picked it up doing a manual test afterwards. @wojtekmach that script would have definitely found it before pushing!

**Comment by ericmj** [comment]
@josevalim It's tricky to include in Hex because every package's smoke test is different. Exdoc is convenient because it's just `mix docs`, I have no idea what the smoke test would be for Ecto though.

The only thing we can do from is make it easier to extract a built package, maybe `mix hex.extract`? Although I don't want to add more tasks :).

@Gazler How would you run a smoke test for cowlib?

**Comment by Gazler** [comment]
@ericmj checking it compiles would have been sufficient in my case. I did a manual test with an existing application when I published it last time.

**Comment by ericmj** [comment]
Maybe we could add `mix hex.build --smoke "mix docs"`?

**Comment by josevalim** [comment]
@ericmj I think `mix hex.build --extract-to dir` that builds a package in memory and then extracts the contents to the given dir is enough, because then I just need to `cd` into it and run my smoke test.

Another idea is to do it in publish. `mix hex.publish smoke "mix compile"` or `mix hex.publish smoke directory`.

**Comment by wojtekmach** [comment]
yet another option is to have `hex.build --smoke ""` (which you can run on CI) and `hex.publish --smoke ""` (which will pass the option down to build). Nice thing about having this on publish is you could have an alias:

```elixir
  def aliases do
    [
      "hex.publish": [~S(hex.publish --smoke "mix docs")]
    ]
  end
```

That being said, `mix hex.build --extract-to dir` and having user write a custom script seems like a simple solution that might be useful elsewhere too

**Comment by ericmj** [comment]
See #436.
