### ISSUE TITLE
Add mix hex.build --smoke

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#436]
`mix hex.build --smoke` would run the equivalent of: (from @wojtekmach)

```sh
#!/bin/bash

# build package
mix hex.build

# extract package (fwiw, we could make it easier from Hex)
mkdir -p pkg pkg/contents && tar xf ex_doc-0.18.0.tar -C pkg && tar xzf pkg/contents.tar.gz -C pkg/contents

# compile app
cd pkg/contents && MIX_ENV=prod mix do deps.get, compile
```

`mix hex.build --smoke "mix docs"` would also run a command after compilation.

To use it on publish the `hex.publish` task has to be aliased.

**Comment by josevalim** [comment]
Does it still produce an artifact? It is weird that --smoke sets the --quiet flag though. Better if the user sets both.

**Comment by ericmj** [comment]
The smoke test should not produce an artifact. You're right, the user should set `--quiet`.
