### ISSUE TITLE
Allow dot files to be published

### ISSUE THREAD

**Issue by mobileoverlord** [hexpm/hex#439]
When hex assembles a list of files to publish based off the expanded paths it omits any files that begin with `.`. This is because the option `:match_dot` is not enabled on the wildcard search at
https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex.build.ex#L277

Changing it to 
`Path.wildcard(Path.join(path, "**"), match_dot: true)` fixes my issue, but I know that its going to break the behaviour for everyone else. Thoughts?

**Comment by ericmj** [comment]
I think we should include dot files by default. If anyone wants to exclude them they can still explicitly list the files they want to include or use `Path.wildcard` themselves.
