### ISSUE TITLE
Add hex.download task

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#453]
From: https://github.com/hexpm/hex/issues/261#issuecomment-341446177

```
mix hex.download ecto --o vendor/hex # creates vendor/hex/ecto-2.2.6.tar
mix hex.download ecto 2.2.6 --output vendor/hex # creates vendor/hex/ecto-2.2.6.tar
```

**Comment by josevalim** [comment]
I recommend to also support the `--unpack` flag proposed for hex.build on #452. Not sure if you want to have `-o` here though or add `--to` to `hex.build`.

**Comment by ericmj** [comment]
Using `-o` makes sense, I will update the issue.

**Comment by milmazz** [comment]
I'll work on this :)

**Comment by wojtekmach** [comment]
Closing in favor of PR
