### ISSUE TITLE
Add ability to use multiple API endpoints.

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex#46]
Currently, Hex only works with one API/CDN endpoint. This is fine for public users, but for organizations running Hex on their own infrastructure, this can be a pain to have to manually edit.

My proposal is to add a `~/.hex/endpoints.config` file in the format:
```elixir
[default: {"cdn_url", "api_url"}, work: {"cdn_url", "api_url"}]
```
This could be toggled using `mix hex.endpoint use work` or `mix hex.endpoint switch` for a prompt input.

Adding this would allow users to quickly switch between registries and CDNs, allowing them to install packages hosted on privately run Hex instances.

This could also be used for mirrors of the S3 bucket (eg. EU or AU).

Thoughts? :+1: or :-1:?

**Comment by lucacorti** [comment]
Is this supported now, or being considered for the future? No private repository support is an issue in corporate environments where you have lots of internal software releases.

**Comment by ericmj** [comment]
I am working on support for private packages in hex.pm. You can use private repositories right now, but you also have to mirror hex.pm also if you want to use packages from hex.pm as well as internal packages.

I am interested in supporting multiple repositories but it's not currently on the roadmap.

**Comment by colinrymer** [comment]
> That said, once we specify the :repo option for a dependency, all dependencies of that dependency must come from the same :repo.

Why must this be the case? If I'm building a private package that depends on Ecto, for example, this would mean I have to duplicate Ecto into my registry and ensure I update it as Ecto updates.

**Comment by ericmj** [comment]
> Why must this be the case? If I'm building a private package that depends on Ecto, for example, this would mean I have to duplicate Ecto into my registry and ensure I update it as Ecto updates.

That comment was from over two years ago :). The `:repo` option is not live yet but when it is you can use it to set where the dependency should be sourced from. The only restriction is for the hex.pm repository, for it you can only depend on other packages from hex.pm.

**Comment by mjonas87** [comment]
@ericmj Where can I track the status of the `:repo` option? Definitely would like to know when that goes live. Thanks!

**Comment by mjonas87** [comment]
Nvm...found it!
