### ISSUE TITLE
password vs passphrase

### ISSUE THREAD

**Issue by bitboxer** [hexpm/hex#460]
Short question:when I use `mix hex.user auth` I am asked for my "Password". When I am using `mix hex.organization auth XXX` it asks me for my "passphrase". Shouldn't this be password for both? This is a bit confusing right now.

**Comment by ericmj** [comment]
Passphrase is the local password used to encrypt your API key. Password is the server account password used to generate a new API key when you run `mix hex.user auth`. See: https://github.com/hexpm/hexpm/issues/588

**Comment by bitboxer** [comment]
Okay, thanks. Will follow that ticket.
