### ISSUE TITLE
Add html_url to /api/users/me owned_packages payload

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#465]
We need to return `html_url` to use it in `mix hex.owner packages` [1]

This is tricky as currently it's a map:

```
  "owned_packages" => %{
    "gardien" => "http://localhost:4001/api/repos/durga_transport/packages/gardien",
    "mtproto" => "http://localhost:4001/api/packages/mtproto"
  },
```

and so changing the shape will break clients. I think we could depreacate `owned_packages` in API payload and introduce `packages` which is a list of maps. Any other options?

[1] https://github.com/hexpm/hex/blob/v0.17.1/lib/mix/tasks/hex.owner.ex#L123

Edit: ugh, I was meaning to create this in hexpm/hexpm repo

**Comment by ericmj** [comment]
Maybe introduce `owned_packages_html_urls` as a separate field?
