### ISSUE TITLE
Dependencies are not fetched

### ISSUE THREAD

**Issue by pma** [hexpm/hex#468]
Hi,

There is an issue with the `amqp_client` lib published hex.pm, where all the dependencies are resolved but only the direct dependency is fetched. `amqp_client` depends on  `rabbit_common` and `recon` and these are not fetched.

I'm submitting here as well because it could be related to the fact that amqp_client uses erlang.mk as the build tool and it could be something affecting all similar hex packages.

To reproduce, just create a new project and add `{:amqp_client, "~> 3.6"}` to mix.exs.

```
~/p/amqp_client_test ❯❯❯ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
  amqp_client 3.6.14
  rabbit_common 3.6.14
  recon 2.3.2
* Getting amqp_client (Hex package)
  Checking package (https://repo.hex.pm/tarballs/amqp_client-3.6.14.tar)
  Fetched package
~/p/amqp_client_test ❯❯❯ ls deps
amqp_client
```

**Comment by ericmj** [comment]
Leaving this open to see if we can test this easier from the Hex side.
