### ISSUE TITLE
Augment or allow to set the timeout of hex http requests

### ISSUE THREAD

**Issue by Zenohate** [hexpm/hex#471]
I work over satellite broadband, and because my ping is extremely high, downloading packages through hex is considerably difficult.

A nice improvement would be either to allow for a longer timeout delay or to make it configurable at runtime or though environment variable.

-----
Thank you all for your hard work, Hex makes the ecosystem around Erlang VM a nice and happy place! You make my day everyday!

**Comment by ericmj** [comment]
In the next version you can configure this through `http_timeout` in the config or `HEX_HTTP_CONCURRENCY` as system environment variable.

**Comment by Zenohate** [comment]
Thank you a lot, sorry for the inconvenience!
