### ISSUE TITLE
`mix deps.get` is _incredibly_ slow for umbrella projects

### ISSUE THREAD

**Issue by binarylogic** [hexpm/hex#472]
We have an umbrella project with approximately 15 applications, executing `mix deps.get` at the root of the umbrella project takes over 20 minutes to complete. Is this a known issue for umbrella projects? How can I inspect further to determine exactly where the slow down is occurring? Is there anything I can provide to assist in debugging?

Thanks!

**Comment by binarylogic** [comment]
I've resolved the issue. It appears to be an issue with `0.15.X`. Upgrading to `0.17.X` resolved the issue for me.

**Comment by ericmj** [comment]
> I've resolved the issue. It appears to be an issue with 0.15.X. Upgrading to 0.17.X resolved the issue for me.

Great to hear that, there has performance improvements in the dependency resolver between 0.15 and 0.17.
