### ISSUE TITLE
Show if a package is retired in hex.info

### ISSUE THREAD

**Issue by supersimple** [hexpm/hex#480]
When using `mix.info packagename version` it would be useful to show an alert that the version has been retired (and possibly also the reason for retirement.)

When using `mix.info packagename` perhaps just color the retired versions in red.

**Comment by supersimple** [comment]
I am happy to submit a PR for this as soon as it is determined to be valuable.

**Comment by ericmj** [comment]
Yeah, that would be a great addition.

**Comment by supersimple** [comment]
@ericmj  I have opened a PR for the `hex.info packagename version`
For the `hex.info packagename` version, I think it would be best to change the response from the API.
```
 "releases" => [%{"url" => "https://hex.pm/api/packages/alphabetify/releases/1.0.2",
     "version" => "1.0.2"},
   %{"url" => "https://hex.pm/api/packages/alphabetify/releases/1.0.1",
     "version" => "1.0.1"},
   %{"url" => "https://hex.pm/api/packages/alphabetify/releases/1.0.0",
     "version" => "1.0.0"},
   %{"url" => "https://hex.pm/api/packages/alphabetify/releases/0.1.0",
     "version" => "0.1.0"}]
```
I would propose adding a retired flag to the map. The only other way to get retired info on a version would be to iterate over each version returned in this call and check it's info. That could mean a lot more network requests.

Please advise what you think the best course of action would be.

**Comment by wojtekmach** [comment]
we initially decided to keep retirement information out of `/api/packages/:name` payload to keep it smaller (a bit more context in https://github.com/hexpm/hexpm/pull/454#issuecomment-336582134), but I agree that in this particular case it would be useful. Yet another way would be to somewhat mimic the registry and have it under a separate key, so:

```json
# GET /api/packages/foo
{
  "releases": [
    {"version": "1.0.0", "url": "..."},
    {"version": "1.0.1", "url": "..."},
  ],
  "retirement": {
    "1.0.0": {"reason": "other", "message": "bad"}
  }
}
```

wdyt @ericmj?

**Comment by wojtekmach** [comment]
@supersimple let us know if you'd like to finishing up this issue by handling `mix hex.info pkg version` :) (requires https://github.com/hexpm/hexpm/issues/607)

**Comment by supersimple** [comment]
@wojtekmach I am not familiar with how/where to make those changes in teh API. If those are made (i assume in hexpm) I am happy to implement the use of them in hex.

**Comment by wojtekmach** [comment]
@supersimple here are some pointers for API:
- https://github.com/hexpm/hexpm/blob/master/lib/hexpm/web/controllers/api/package_controller.ex#L32
- https://github.com/hexpm/hexpm/blob/master/lib/hexpm/web/views/api/package_view.ex#L15
- https://github.com/hexpm/hexpm/blob/master/test/hexpm/web/controllers/api/package_controller_test.exs#L80

a PR would be appreciated, but I'm also happy to work on these later. Thanks for your help!

**Comment by supersimple** [comment]
Great. I'll look at it today.

**Comment by supersimple** [comment]
Great. I'll look at it today.

**Comment by wojtekmach** [comment]
Done in #487
