### ISSUE TITLE
mix hex.info showing retired version on Config line

### ISSUE THREAD

**Issue by CarpeNoctem** [hexpm/hex#499]
### Environment

- Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
- Elixir 1.5.2
- Ubuntu 16.04.3 LTS xenial, x86_64

### Current behavior

Run `mix hex.info postgrex`
Note that the Config line differs from what is shown on https://hex.pm/packages/postgrex 
as it shows a retired version `{:postgrex, "~> 1.0.0-rc.1"}` instead of `{:postgrex, "~> 0.13.4"}`

### Expected behavior
`mix hex.info` should 
a) show the same config string that appears on hex.pm, and 
b) not show retired or pre-release versions of packages.

**Comment by ericmj** [comment]
We can reimplement the behavior on hex.pm, which is show the latest version that is not retired and not a pre-release. Or we can add this information to the hex.pm API and the client will just use that information.

**Comment by michalmuskala** [comment]
I think adding this information to API will be a better solution - otherwise most tools integrating with the API would need to reimplement this logic.

**Comment by wojtekmach** [comment]
we've recently added `retirements` key to the server:

```json
{
  "url": "https://hex.pm/api/packages/postgrex",
  "updated_at": "2018-01-25T18:29:57.192744Z",
  "retirements": {
    "1.0.0-rc.1": {
      "reason": "invalid",
      "message": "Superseded by v0.13.0-rc.0"
    },
    "1.0.0-rc.0": {
      "reason": "invalid",
      "message": "Superseded by v0.13.0-rc.0"
    }
  },
  "repository": "hexpm",
  "releases": [
    {
      "version": "1.0.0-rc.1",
      "url": "https://hex.pm/api/packages/postgrex/releases/1.0.0-rc.1"
    },
    {
      "version": "1.0.0-rc.0",
      "url": "https://hex.pm/api/packages/postgrex/releases/1.0.0-rc.0"
    },
    {
      "version": "0.13.4",
      "url": "https://hex.pm/api/packages/postgrex/releases/0.13.4"
    },
```

so we have all the information we need on the client to calculate "latest non-retired" release.
