### ISSUE TITLE
Typo-squatting does not seem to be working

### ISSUE THREAD

**Issue by supersimple** [hexpm/hex#501]
<img width="368" alt="screen shot 2018-02-06 at 10 40 38 pm" src="https://user-images.githubusercontent.com/773380/35900372-dfe3dc68-0b8e-11e8-9824-8eea8d50a585.png">

As part of a project I am working on, I wanted to show how hex prevents typo squatting. I thought their was a typo check that prevents packge names with a levenstein distance of 2 or less. As you can see, this package I published has a distance of 1.

I reverted the package right away.

**Comment by ericmj** [comment]
The typo check runs once every 24h and requires review by an admin since not all names with a levenstein distance <2 are typo squats.

**Comment by supersimple** [comment]
TIL - I thought that was happening at publish time.
