### ISSUE TITLE
Improve mix hex.docs

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#502]
Today the offline flag is a bit hidden, even though it is the main use case for hex.docs. My suggestion:

  * `mix hex.docs fetch PKG VERSION` - no changes
  * `mix hex.docs online PKG VERSION` - same as `open` today
  * `mix hex.docs offline PKG VERSION` - same as `open --offline` today

It would also be nice if `mix hex.docs` was made "project" aware. `mix hex.docs fetch` with no name could download all docs for the current project. `mix hex.docs online PKG` would open the version of the current project unless a `--latest` flag is given. To avoid confusion though,  I would suggest improving the logging. Whenever a project or latest version are picked (i.e. a version is not explicitly given) we print why we took that decision.

**Comment by michalmuskala** [comment]
I started work on the second thing you mention - considering the version used in the current project, I never got to finishing it, though https://github.com/hexpm/hex/pull/348.

**Comment by supersimple** [comment]
This part:
mix hex.docs fetch PKG VERSION - no changes
mix hex.docs online PKG VERSION - same as open today
mix hex.docs offline PKG VERSION - same as open --offline today

is completed in https://github.com/hexpm/hex/pull/503

**Comment by supersimple** [comment]
I am starting to work on the second part. Here is the behaviour I am proposing:
`mix hex.docs fetch`
  - Check if we are in a project
      - if not, raise an error
      - if so, find all deps in project, with versions
         - then iterate through that list and fetch every dependency, with that version
  
  `mix hex.docs fetch PKG`
    - Check if we are in a project
      - if not, fetch the latest version
      - if so, get the version used in the project
 
  `mix hex.docs online|offline PKG`
    - check if we are in a project
    - if not, get the latest version
    - if so, get the version that matches the deps
 
  `mix hex.docs online|offline PKG --latest`
    - get the latest version

Although José described this behaviour only for online, I dont see why it wouldnt also apply for the offline task.

So far I am loading the dependency map using the `Mix.Dep` module. As soon as I get some confirmation that the behaviour I described above matches your expectations (@josevalim, @ericmj, @wojtekmach) I will finish my work and open a PR.

Thanks 🦄

**Comment by wojtekmach** [comment]
looks good to me!

**Comment by wojtekmach** [comment]
if there's gonna be a `mix hex.pkg open PACKAGE` (https://github.com/hexpm/hex/pull/466#issuecomment-364643500) perhaps we should still have `mix hex.docs open` to mirror it (under the hood it could either call `hex.docs online` or `hex.docs offline` or work slightly differently)

**Comment by supersimple** [comment]
Yes, I think Josés original comment was to keep the tasks similar. Perhaps since he also asked to change open to offline and online, maybe hex.pkg should drop open also, and use those commands as well.

**Comment by josevalim** [comment]
They don't need to mirror if they do different things :) For example, unless we are also opening a package in the browser, we don't need an online task.

**Comment by ericmj** [comment]
Done in https://github.com/hexpm/hex/pull/503.

**Comment by michalmuskala** [comment]
It didn't fully address the second part of using project's versions instead of always latest.

**Comment by supersimple** [comment]
I am still working on the second part - just need to add some tests and a little refactor.

**Comment by supersimple** [comment]
@ericmj @wojtekmach I put up a PR for the new features, but I need help configuring the tests still. If you have time and can take a look, maybe just an example would get me going. Thanks.

**Comment by supersimple** [comment]
@ericmj @wojtekmach I think this was completed in https://github.com/hexpm/hex/pull/508

**Comment by wojtekmach** [comment]
Yup, thanks again!
