### ISSUE TITLE
hex docs does not support multiple repos

### ISSUE THREAD

**Issue by supersimple** [hexpm/hex#504]
Currently hex docs fetches docs into a HEX_HOME/docs/package/release structure. This causes problems where a private repo contains a package with the same name as a public release. They would both download to the same place.

@wojtekmach proposed adding the repo to the path (HEX_HOME/docs/repo/package/release).

This solves the issue, but causes another one where any currently downloaded packages become unreachable.

Also, are there any other parts of Hex that expect the docs dir to follow that pattern?

**Comment by ericmj** [comment]
Fixed in https://github.com/hexpm/hex/pull/509
