### ISSUE TITLE
Change error message when failing to verify custom repo

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#521]
Currently it mentions Hex.pm:

> ** (Mix) Could not verify authenticity of fetched registry file. This may happen because a proxy or some entity is interfering with the download or because you don't have a public key to verify the registry.
> 
> You may try again later or check if a new public key has been released on our public keys page: https://hex.pm/docs/public_keys

it should mention particular repo we couldn't verify against instead.

**Comment by supersimple** [comment]
@wojtekmach I started looking into this, it seems like most of hex.install is hard-coded (or at least designed) only to work  from the public repo.
Just want to verify that there isnt something I am missing.
Do you have any ideas on how to determine which repo the user prefers to use?

**Comment by wojtekmach** [comment]
I believe I run into this message when running deps.get so its somewhere in Hex.SCM, I will add more details this weekend.

**Comment by wojtekmach** [comment]
Oh and to answer your question where the repo comes from: it should come from lock.

**Comment by wojtekmach** [comment]
Fixed in https://github.com/hexpm/hex/pull/529/commits/e4bd497e68633efde8861fbb0ad435a92bb67097
