### ISSUE TITLE
`hex.docs open` doesn't work on Windows

### ISSUE THREAD

**Issue by TroyLaurin** [hexpm/hex#523]
Basically it always fails with `** (Mix) Command not found: start`.

The problem is in the following code:
```
  defp browser_open(path) do
    start_command = start_command()

    if System.find_executable(start_command) do
      system_cmd(start_command, [path])
    else
      Mix.raise("Command not found: #{start_command}")
    end
  end

  defp start_command() do
    case :os.type() do
      {:win32, _} -> "start"
      {:unix, :darwin} -> "open"
      {:unix, _} -> "xdg-open"
    end
  end
```

`start` is a built-in command rathan than an executable on Windows, so `System.find_executable` will never succeed.  Why not just leave executable-testing to the OS?

**Comment by ericmj** [comment]
> Why not just leave executable-testing to the OS?

I agree, we should call `system_cmd` without checking if an executable exists before. A PR would be very appreciated.

**Comment by TroyLaurin** [comment]
PR in progress; it works, but the unit tests need to be updated... and I don't have the integration tests set up to run yet!
