### ISSUE TITLE
Is there something like `private: true` optionfor hex private organization packages?

### ISSUE THREAD

**Issue by stephenmoloney** [hexpm/hex#527]
### Description:

- If memory serves me correctly, npm has something like `"private": "true"` to block the publishing of a private package accidentally as public.

- Is there something similar to prevent such an accident for a private hex package?

### Potential Option:

- Add `private: true` option or similar in `mix.exs`. Unless I'm missing something where that accident is not possible in the first place.

Thanks.

**Comment by stephenmoloney** [comment]
or perhaps `organization: "acme"` has the same effect?

**Comment by wojtekmach** [comment]
> or perhaps adding organization: "acme" to def package ... has the same effect?

@stephenmoloney yes, exactly. Additionally, just before the final `Y/n` confirmation when publishing we're printing whether we're publishing to public hexpm or private repo.

**Comment by stephenmoloney** [comment]
thanks...
