### ISSUE TITLE
Corporate Proxy Reporting Cannot Establish SSH Tunnel

### ISSUE THREAD

**Issue by HangingClowns** [hexpm/hex#530]
Please excuse if I make some mistakes while typing but I cannot login to github at work. I keep getting a fobidden 403 reply along with :could_no_establish_ssh_tunnel while running mix deps.get. I had to manually install hex and rebar cause of the same issue. Is there a way I can add more verbosity to see where the problem is? I have set with windows environment variables and also using mix hex.config and trying different proxy including one setup with cntlm that lets me clone from github.

**Comment by ericmj** [comment]
Git and github related issues are not really related to Hex so setting `hex.config`. I would recommend asking on the forum, IRC, or Slack where your question will reach more people.

**Comment by HangingClowns** [comment]
Managed to figure it out. It seems system ENV variables override the hex config ones.
