### ISSUE TITLE
Password reset emails

### ISSUE THREAD

**Issue by pragdave** [hexpm/hex#533]
Sorry to post this here, because I'm not sure it is an issue. But I've been trying to get a password reset email for a couple of days now with no luck. I've tried both with my usr name (pragdave) and email (dave@pragdave.me)

Cheers

Dave

**Comment by wojtekmach** [comment]
@pragdave I just tested it and it seems there's a problem with resetting password via `mix hex.user`. You can also reset password here: https://hex.pm/password/reset which worked for me immediately, could you try that?

**Comment by pragdave** [comment]
I have been using the web interface with no luck...

**Comment by wojtekmach** [comment]
@pragdave I'm not sure what's wrong, can be our email delivery service. If you send an email to support@hex.pm from the email you used to register your email account I can reply with a reset link to unblock you in the meantime.

**Comment by ericmj** [comment]
> I just tested it and it seems there's a problem with resetting password via mix hex.user.

I tried both the hex.user and website reset and they both work for me. What issue did you have?

**Comment by wojtekmach** [comment]
No obvious issues, I just didn't get the email in my inbox. Looks good in development.

**Comment by ericmj** [comment]
Hum, that's strange because we have no error reports or reports of bounced mails.

**Comment by ericmj** [comment]
Fixed by support.
