### ISSUE TITLE
Resolver output should differentiate changed and unchanged dependencies

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#534]
It should clearly show what was updated, downgraded, and unchanged.

Today:

```
Resolving Hex dependencies...
Dependency resolution completed:
  connection 1.0.4
  decimal 1.3.1
  earmark 1.2.2
  ex_doc 0.16.1
  jason 1.0.0
All dependencies up to date
```

Proposal:

```
Resolving Hex dependencies...
Unchanged:
  connection 1.0.4
  jason 1.0.0
Updated:
  earmark 1.2.0 => 1.2.2
  ex_doc 0.16.0 => 0.16.1
Downgraded:
  decimal 1.4.0 => 1.3.1
All dependencies up to date
```

**Comment by wojtekmach** [comment]
Sounds good! I'd move "Unchanged" section to the bottom as it will often have the most items.

**Comment by josevalim** [comment]
@wojtekmach shouldn't we keep "Unchanged" at the top because we mostly don't care about them (since the terminal scrolls)? :)

**Comment by supersimple** [comment]
@ericmj @wojtekmach Working on this today, I'll try to have a PR up by EOD.

**Comment by supersimple** [comment]
Resolved in: https://github.com/hexpm/hex/pull/535
