### ISSUE TITLE
Generating organization keys fails with MatchError

### ISSUE THREAD

**Issue by Schultzer** [hexpm/hex#536]
So I'm trying to publish a new release of my package `ex_cldr_territories`
```
mix hex.publish
...
No authenticated user found. Do you want to authenticate now? [Yn] y
Username: Schultzer
Account password: 
Generating API key...
You have authenticated on Hex using your account password. However, Hex requires you to have a local password that applies only to this machine for security purposes. Please enter it.
Local password: 
Local password (confirm): 
Generating organization keys...
** (MatchError) no match of right hand side value: :error
    (hex) lib/hex/crypto/encryption.ex:30: Hex.Crypto.Encryption.decrypt/2
    (hex) lib/mix/tasks/hex.ex:161: Mix.Tasks.Hex.auth_info/0
    (hex) lib/mix/tasks/hex.publish.ex:149: Mix.Tasks.Hex.Publish.create/3
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
```

I'm generating a strong password in keychain

let just say the "length of the password" is between somewhere "0-50"

**Comment by kipcole9** [comment]
Reported earlier :-) https://github.com/hexpm/hex/issues/516 and a fix has been merged.

**Comment by Schultzer** [comment]
Well when I publish I just get prompt for the local password and it just tells me it's the wrong password.

**Comment by supersimple** [comment]
@Schultzer what happens when you try to authorize outside of the publish workflow? do you have the same issue?  try `mix hex.user whoami` or `mix hex.user auth`

**Comment by Schultzer** [comment]
I get prompt for the local password, and when I type in the one I created with I get wrong password.

**Comment by supersimple** [comment]
ok, what happens when you try `mix hex.user auth` ? that will require your account (remote) password first. Does that password work? if so, can you try resetting your local password (it will prompt for it straight-away)? Also, maybe try a simple password just for testing it out (it is only stored on your local machien and you can use this same process after to make a more secure password.

**Comment by supersimple** [comment]
Also, I am available on elixir slack (toddresudek) if you want to trouble shoot with me.

**Comment by Schultzer** [comment]
`mix hex.user auth` I get to do the whole process of username, password, local password
it seams to work. but when I try to publish it still the say wrong local password

**Comment by supersimple** [comment]
@Schultzer were you able to get it to work? if not, hit me up on slack.

**Comment by Schultzer** [comment]
@supersimple yeah it's working now just had to run `mix hex.user auth` five times.

**Comment by supersimple** [comment]
well, good to hear. My guess was something got corrupted in your hex.config file. `mix hex.user key --revoke-all` will clean that if it ever happens again.
