### ISSUE TITLE
Private docs url when publishing

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#545]
Currently it shows the incorrect public URL:

```
hexpm/priv_foo[master]% mix hex.publish docs
Docs successfully generated.
View them at "doc/index.html".
Local password:
[#########################] 100%
Docs published to https://hexdocs.pm/priv_foo/0.2.0
```

Currently, `POST /api/packages/:name/releases/:version/docs` returns 201 with location of the docs tarball, perhaps it should return JSON with docs_html_url and docs_tarball_url?

In the meantime, on the client we can grab docs_html_url by calling API.

**Comment by ericmj** [comment]
@supersimple We should fix it but it disable it in the client for now until it is supported.

**Comment by wojtekmach** [comment]
Yup, thanks!
