### ISSUE TITLE
Print error when package exceeds hex.pm limit

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#551]

**Comment by ericmj** [comment]
You are right of course.

Looking into this I think the limit should be configurable or possibly that the user of the library should be able to configure the limit. The limit is set by hex.pm and we are considering raising it for private packages and private hosting may have no limits. I also think the limit should be enforced on `mix hex.publish` not by `mix hex.build`.

What do you think is the best approach?

**Comment by wojtekmach** [comment]
Agreed with all points, but I'm on a fence which way we should go. If we enforce the limit on `hex.publish` is it still useful to have configurable limit in hex_erl? I'd say maybe as it's cheap validation but I'm not super convinced.

If we raise or drop the limits for other offerings one nice thing we'd lose is catching mistakes e.g. people accidentally publishing large files. (the downside of limit of course it limits real use cases.) Not sure there's anything about it, I suppose we could display tarball size (maybe in colors if it's above Xmb) but nobody's gonna see the warning anyway :)

**Comment by soteras** [comment]
To check: We need add a new key in *hex.config* possible *package_max_size* and verify if tarball is less than  *package_max_size* in *hex.publish* ??

**Comment by ericmj** [comment]
This should not be configurable by users. The question is if should be configurable in https://github.com/hexpm/hex_erl or hard coded, we should move the issue there.
