### ISSUE TITLE
Avoid making conditional HTTP request when package is older than one hour

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#561]

**Comment by ericmj** [comment]
Note that we still have to make conditional requests for private packages since they are mutable.

Since other repositories may not have the same immutability policies maybe we should skip this optimization all together?

**Comment by zacck** [comment]
@ericmj  would it be possible for you to elucidate what actions needed this to get done?

**Comment by ericmj** [comment]
Unfortunately we cannot implement this without making assumptions about the semantics of repositories. We cannot assume we are using the hex.pm repository because of mirrors and private repositories.
