### ISSUE TITLE
Check if we can avoid fetching registry for locked packages

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#562]
This should be possible but requires changes to the resolver due to the way we prefetch the registries and how locked dependencies are implemented.

It also means we will not got new retired messages for already locked dependencies.

**Comment by michalmuskala** [comment]
Maybe it would make sense to fetch the registry only once a day for example?

I also wonder if maybe it would be possible to optionally provide info about depreciation in an HTTP header for the tarball. I'm not sure if that's possible on current infrastructure, though.

**Comment by ericmj** [comment]
It is possible to set headers but it's tricky because we use S3. If we implement https://github.com/hexpm/hex/issues/561 as well it wouldn't be very useful anyway.

**Comment by ericmj** [comment]
Unfortunately I don't see a way to implement this without possibly ignoring retirement messages.
