### ISSUE TITLE
hex.outdated breaks CI builds

### ISSUE THREAD

**Issue by scrogson** [hexpm/hex#588]
Since the `v0.18.0` release we started seeing our CI builds fail due to the changes introduce in `mix hex.outdated`.

According to the proposal in https://github.com/hexpm/hex/issues/554 there was supposed to be some sort of flag to optionally exit with non-zero. But in #563 it doesn't appear to be configurable.

It seems that having some sort of `--strict` flag would be a more desirable than the change introduced.

Thoughts?

**Comment by supersimple** [comment]
@scrogson v0.18.0 had an issue. Are you updated to 0.18.1 yet? (just want to confirm the issue was not fixed in the latest patch release)

**Comment by supersimple** [comment]
Sorry @scrogson, i re-read your comment. Both hex.audit and hex.outdated return non-zero codes and are not configurable (strict mode.)
We did have some discussion on that idea (i'll try to find the thread) but i think it was decided a non-zero code was expected.
How are you using hex.outdated in your CI pipeline? I would be interested in hearing the case for hex.audit or hex.outdated to output an error, but still return a zero code.

**Comment by supersimple** [comment]
@ericmj @wojtekmach I put up a couple PRs to address this use-case.
Please push back if you think it is not a worthwhile addition to the code. The original request mentioned a strict mode, I thought since the current behavior is "strict", it would be better advised to make a "passive" mode which acts differently for the expectation.

**Comment by wojtekmach** [comment]
Sorry for inconvenience!

Instead of introducing a flag, an alternative is to put into script something like:

    mix hex.outdated || true

Would that work for you?

Personally I think non-zero status code is a good default, thats what Id expect from such cli tool.

**Comment by scrogson** [comment]
Yeah, I think I agree with what has been said. I'll relay the message back to my team. 👍
