### ISSUE TITLE
Publishing a Package to Private Repository Consistently Failing

### ISSUE THREAD

**Issue by coby-spotim** [hexpm/hex#597]
My company has an organisation on Hex.pm that contains some private packages that we use internally.

Yesterday, we fixed a bug in one of these private packages, but whenever we try to publish, we continuously get a Publishing Failed error, and the reason being given is a Heroku Application Error from the Hex.PM side.

It's been happening for about 18 hours consistently now, and we are unable to publish this bug fix to the package that will be used to fix other services that we have in production.

I've also noticed that when I'm on the Hex.pm website I am seeing a lot of these Heroku Application Errors.

Is there a performance issue with the Hex platform that we should know about?

I'm appending a sanitised version of the output below so you can see what the output looks like whenever we attempt to publish.

Please help, as this is a major issue that is holding up our production services.

```
$ mix hex.publish
Building package 0.4.10
  Dependencies:
    a >= 0.0.0 (app: a)
    b >= 0.0.0 (app: b)
    c >= 1.0.0 (app: c)
    d >= 1.0.0 (app: d)
    e >= 0.1.5 (app: e)
  Organization: {{Our Organization Name}}
  App: {{Name of our Package}}
  Name: {{Name of our Package}}
  Files:
    lib
    lib/a.ex
    lib/b.ex
    lib/c.ex
    mix.exs
    README.md
  Version: 0.4.10
  Build tools: mix
  Description: {{A description of our package}}
  Links:
    GitHub: {{Link to our GitHub}}
  Elixir: ~> 1.6
Missing metadata fields: licenses
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct

Publishing package to private repository {{Our Organization Name}}.
Proceed? [Yn] Y
Building docs...
Docs successfully generated.
View them at "doc/index.html".
Local password:
Publishing package...
[#########################] 100%
Publishing failed
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

**Comment by ericmj** [comment]
The issue has been resolved.
