### ISSUE TITLE
Temporally disable documentation on private hex

### ISSUE THREAD

**Issue by fbergero** [hexpm/hex#599]
Currently when publishing a package to a private hex `hex.publish` requires to have a `mix docs` task if not fails.
It would be great if the docs generation could be optional (otherwise it forces you to include `ex_doc`).
Additionally, the result of publishing states that the documentation was published to an URL of the public hex which (hopefully) does not work. Is not clear that nothing was published.

**Comment by ericmj** [comment]
> Currently when publishing a package to a private hex hex.publish requires to have a mix docs task if not fails.

If you want to publish only the package without documentation you can run `mix hex.publish package`.

> Additionally, the result of publishing states that the documentation was published to an URL of the public hex which (hopefully) does not work. Is not clear that nothing was published.

This has been fixed in master and will be included in the next release. Your documentation is published to `https://myorg.hexdocs.pm/mypackage`.
