### ISSUE TITLE
Hex should not publish packages with runtime: false in dependencies

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#601]
Instead they should drop the runtime flag, as it is not added to the registry, and use `:applications` instead of `:extra_applications`.

**Comment by michalmuskala** [comment]
I'm not sure, I understand the reasoning behind this. What is the issue with a package having `runtime: false` in dependencies? This will be properly reflected in the generated `.app` file.

**Comment by josevalim** [comment]
@michalmuskala `runtime: false` does not go to the registry. This means that once the dependencies come from Hex, we do not know they are `runtime: false`, so we end-up adding them to the `.app` file.

**Comment by josevalim** [comment]
@ericmj but now that I think about it... I guess we could fix this in Mix? The reason why this happens is because we ignore the deps in `mix.exs` in favor of Hex ones. But maybe we should read the `deps` from `mix.exs` instead of `Mix.Dep.cached` for getting the information if they are at runtime or not.

**Comment by josevalim** [comment]
Yeah, I got a fix. Thanks @michalmuskala. I will push to elixir master soon!

**Comment by michalmuskala** [comment]
Ah, I was confused by this because I assumed it did read from the project directly. Yes, I think this would be a better change.

The only issue might be if the dependency has some dynamic code, but I'm not sure that's a concern.

**Comment by josevalim** [comment]
Fixed in https://github.com/elixir-lang/elixir/pull/8109.
