### ISSUE TITLE
private docs

### ISSUE THREAD

**Issue by tim2CF** [hexpm/hex#606]
Are private hex.pm docs working?

```
Publishing package to private repository ******.
Proceed? [Yn] y
Building docs...
warning: index.html redirects to README.html, which does not exist
Docs successfully generated.
View them at "doc/index.html".
Local password:
Publishing package...
[#########################] 100%
Package published to https://hex.pm/packages/***/***/*.*.*
Publishing docs...
[#########################] 100%
Docs published to https://hexdocs.pm/***/*.*.*
mix hex.publish  17.47s user 6.20s system 54% cpu 43.043 total
```

First thing is that domain `https://hexdocs.pm` is public. Second thing is that web browser shows 404 in docs page of private package (even if I logged in and can see private package page).

**Comment by fertapric** [comment]
Might you be using an old Hex version?

**Comment by tim2CF** [comment]
Iljas-iMac:lab timcf$ mix hex.info
Hex:    0.18.1
Elixir: 1.7.2
OTP:    21.0.4

Built with: Elixir 1.6.6 and OTP 19.3

**Comment by fertapric** [comment]
It seems the subdomain is not being added to the final url.

**Comment by tim2CF** [comment]
yes, but if I will add it - still will be 404

```
https://organization.hexdocs.pm/package
```

but on the same time page

```
https://hex.pm/packages/organization/package
```

exists with all needed package versions inside

**Comment by fertapric** [comment]
Oh! `https://<organization>.hexdocs.pm/<package>` is working in my case.

**Comment by ericmj** [comment]
@fertapric is correct. The url should be `https://MYORG.hexdocs.pm/MYPACKAGE`.

**Comment by ericmj** [comment]
If you are getting a 404 for the documentation and do not wish to share the organization and package name here, then you can contact support@hex.pm with the information so we can investigate the issue.

**Comment by tim2CF** [comment]
thanks, sent email

**Comment by tim2CF** [comment]
Haha, solved it. Replaced 

```
docs:         [main: "README", extras: ["README.md"]],
```

with

```
docs:         [main: "readme", extras: ["README.md"]],
```
