### ISSUE TITLE
Provide `--dry-run` for `hex.publish` task

### ISSUE THREAD

**Issue by NobbZ** [hexpm/hex#607]
I'm using CI and want to make sure, that the next `hex.publish` will suceed with the current local data.

But currently there seems to be no way to do so. `mix hex.build` will happily suceed even when important package metadata is missing, also it does not care about documentation at all.

That I need to have `ex_docs` available, only occured to me after I got a failing run from CI, which should have been a release already.

Both would have been seen earlier if I had the possibility to run `mix hex.publish --dry-run`, which would check, metadata, build docs and package and then reports success or fails, without uploading the package. Perhaps without interacting with the server at all?

**Comment by ericmj** [comment]
This would be nice to have 👍. Keep in mind that there can still be validations on the server that can stop you from publishing.
