### ISSUE TITLE
Do not print "Unchanged" dependencies on mix deps.get in green

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#614]
Since they have been unchanged, we probably do not need to call attention to them. The plus side is that I no longer need to read the text to know that something changed. If there is nothing in green, nothing changed!

Thoughts?

**Comment by ericmj** [comment]
Sounds good. How about green for upgraded, red or yellow for downgraded and normal color for unchanged?

**Comment by hlhr** [comment]
I will send a PR for this :)

**Comment by wojtekmach** [comment]
Closing in favour of PR.
