### ISSUE TITLE
mix deps.get getting timeout error

### ISSUE THREAD

**Issue by rogervezaro** [hexpm/hex#628]
I just created a simple 1.4 phoenix application and tried to run  ``` mix deps.get```, however, I'm getting timeout error.
```
** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm", "phoenix"}, 60000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (hex) lib/hex/registry/server.ex:58: Hex.Registry.Server.versions/2
    (hex) lib/hex/remote_converger.ex:178: Hex.RemoteConverger.verify_package_req/4
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (hex) lib/hex/remote_converger.ex:168: Hex.RemoteConverger.verify_input/2
    (hex) lib/hex/remote_converger.ex:42: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:28: Mix.Tasks.Deps.Get.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```
mix hex.info

```
Hex:    0.18.2
Elixir: 1.7.3
OTP:    21.0

Built with: Elixir 1.7.3 and OTP 21.0
** (exit) exited in: GenServer.call(Hex.UpdateChecker, :check, 60000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (hex) lib/hex/update_checker.ex:24: Hex.UpdateChecker.check/0
    (hex) lib/mix/tasks/hex.info.ex:58: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

**Comment by supersimple** [comment]
@rogervezaro This is usually a temporary condition that has to do with network issues. By default, hex will timeout after 60 seconds. If your connection is slow, or if the package source is responding slowly sometimes that is not long enough.
One thing to try is to increase that timeout, `HEX_HTTP_TIMEOUT=120 mix deps.get` where 120 equals the timeout in seconds.

**Comment by rogervezaro** [comment]
I've already tried to increase the timeout to 120s, but I'm getting the same result.

**Comment by ericmj** [comment]
It is possible it is related to this issue https://github.com/elixir-lang/elixir/issues/8252 but then I don't see how `mix local.hex` would have succeeded.

**Comment by ericmj** [comment]
Closing this because we don't have enough information to investigate the issue.

**Comment by deepakdinesh1123** [comment]
I was trying to setup phoenix and I am running into the same issue, `mix local.hex` and `mix archive.install hex phx_new` succeeds but `mix deps.get` fails

**Comment by sujeshthekkepatt** [comment]
@deepakdinesh1123 did you get this resolved ? @ericmj seeing this on Mac OS M2 sequoia. `mix deps.get` fails and  showing timeout errors

```
Failed to fetch record for ecto_sql from registry (using cache instead)
:timeout
Failed to fetch record for phoenix_live_reload from registry (using cache instead)
:timeout
:timeout
Failed to fetch record for phoenix_html from registry (using cache instead)
Failed to fetch record for postgrex from registry (using cache instead)
:timeout
** (Mix) No package with name ecto_sql (from: mix.exs) in registry

```

**Comment by deepakdinesh1123** [comment]
@sujeshthekkepatt

https://elixirforum.com/t/mix-deps-get-not-working-on-macos-sonoma-14-6-1/65813/13?u=deepakdinesh1123

**Comment by sujeshthekkepatt** [comment]
Thanks @deepakdinesh1123 This is worked. For me this also worked `HEX_MIRROR=https://cdn.jsdelivr.net/hex mix deps.get`. However, I am not behind any proxy or anything.
