### ISSUE TITLE
Usage incomprehension

### ISSUE THREAD

**Issue by Gilbert-Wong** [hexpm/hex#629]
I follow the documentation in hex.pm. When I execute command `rebar3 hex user register` and fill all information it need. It show me error that `Registration of user gilbertwong failed (401)`.

![image](https://user-images.githubusercontent.com/20479699/48599674-b0cd8480-e9a3-11e8-8829-0e848c19083c.png)

And the policies and terms of service [url](https://hex.pm/policies) you provide is 404 not found. Can you tell me how to register user successfully through rebar3 hex plugin?

**Comment by wojtekmach** [comment]
Hi, if you are having problems with using Hex with Rebar, please open up issue on the plugin repo: https://github.com/tsloughter/rebar3_hex. Perhaps you are using old version of the plugin?

If you have Elixir installed you can also register using: `mix hex.user register`, if you have problems with that too then we can definitely help as we maintain this codebase.

**Comment by Gilbert-Wong** [comment]
Thanks for your help, I will take a look at it.

**Comment by wojtekmach** [comment]
Hi @Gilbert-Wong I took a quick look at rebar3_hex issue tracker and this looks similar: https://github.com/tsloughter/rebar3_hex/issues/77

**Comment by ericmj** [comment]
You can also sign up directly on the website: https://hex.pm/signup
