### ISSUE TITLE
Add `mix hex.package` task

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#632]
TODO:

* [x] `mix hex.package fetch [--unpack] PACKAGE VERSION`
* [x] `mix hex.package fetch --output PATH PACKAGE VERSION`. `PATH` can be `-` for stdout
* [ ] `mix hex.package diff PACKAGE VERSION`
* [x] `mix hex.package diff PACKAGE VERSION1..VERSION2`
* [ ] ~`mix hex.package diff PACKAGE VERSION|VERSION_RANGE GLOB`~
* [ ] ~`mix hex.package diff PACKAGE VERSION|VERSION_RANGE -- COMMAND`~

I'd like to propose to add a new `mix hex.package` task that allows to audit Hex packages.

## 1. Fetch package tarball

    mix hex.package fetch decimal 1.5.0
    # creates decimal-1.5.0.tar

Fetch and unpack:

    mix hex.package fetch decimal 1.5.0 --unpack
    # creates decimal-1.5.0/

## 2. Compare between current version in lock and a given version

Say I'm using decimal v1.5.0 and I want to check what changed in v1.6.0:

    mix hex.package diff decimal 1.6.0

Output:

    (...)
    diff -ru deps/decimal/mix.exs ../../other/decimal/mix.exs
    --- deps/decimal/mix.exs	2018-11-08 10:40:45.000000000 +0100
    +++ ../../other/decimal/mix.exs	2018-11-27 13:34:15.000000000 +0100
    @@ -1,7 +1,7 @@
     defmodule Decimal.Mixfile do
       use Mix.Project

    -  @version "1.5.0"
    +  @version "1.6.0"
    (...)

What's happening under the hood is we're running dependency resolution on the new version,
downloading and unpacking resolved packages to a temporary directory and comparing with `./deps`.

Note, if a package `foo-1.0.0` depends on `bar-1.0.0` and `foo-2.0.0` on `bar-2.0.0`,
when running diff we'll see changes both to `foo` and `bar`.

## 3. Comparing two versions:

    mix hex.package diff decimal 1.5.0..1.6.0

Note: when running `mix hex.package diff`, when we give it one version it needs to
be run in a Mix project, with two versions like here it can be run outside.

## 4. Comparing with latest (non-retired) version:

    mix hex.package diff decimal latest
    mix hex.package diff decimal 1.5.0..latest

**Comment by ericmj** [comment]
@devonestes Unfortunately we can't display commits because hex is not tied to any source control. This would be better to build directly on top of `git` or the source control you are using.

**Comment by Gazler** [comment]
I had the same though after reading about the event-stream JavaScript library.

One idea I would like to also throw into the mix is a way to diff multiple packages during an upgrade. Something like:

`mix deps.update --all --diff`

Or:

`mix deps.get --diff`

Ideally something like this would make it possible to prevent an upgrade unless a `diff` has been reviewed first?

**Comment by wojtekmach** [comment]
Should we deprecate `mix hex.info PACKAGE [VERSION]` in favour of `mix hex.package info PACKAGE [VERSION]`? That seems like a better place for this functionality. `mix hex.info` (with no args) is totally unrelated too.

Btw, I've updated the issue description with a list of tasks, if someone wants to pick up any of these, let us know!

**Comment by ericmj** [comment]
Deprecating `mix hex.info` in favor of this task is a possibility but let's leave it for later. Right now `mix hex.package` is about the package sources and `mix hex.info` is about package metadata, but that doesn't mean we can't combine them.

**Comment by wojtekmach** [comment]
Good call.

**Comment by josevalim** [comment]
Yeah. Combine them seems like a good call but probably something best done
later. Isn’t mix hex.info also used to get general hex information? Or can
we out that under mix hex —info?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fteem** [comment]
@wojtekmach @ericmj if it's free for taking, could I take a stab at `mix hex.package fetch [--unpack] PACKAGE VERSION`? 😊🙏

**Comment by fteem** [comment]
@wojtekmach I have a PR in the works, should be ready for review in the next day or two. Apologies for the delay.

**Comment by wojtekmach** [comment]
No worries and no rush, just checking in if you're actively working on it in. Thanks for looking into it!

**Comment by RyanSiu1995** [comment]
@fteem hi, can I get involved? As I have seen there is a pull request, I don't want to crash the code as you did. Please let me know what I can help proceed the pull request. :)

**Comment by wojtekmach** [comment]
@fteem ping :)

**Comment by fteem** [comment]
@wojtekmach apologies for the radio silence! @RyanSiu1995 please feel free to take over the PR 🙏

**Comment by RyanSiu1995** [comment]
Hi, @wojtekmach 
I am working on ```mix hex.package fetch --output PATH PACKAGE VERSION```. A simple question about the stdout as output. Does it mean I need to print out the binary content of the tarball?
For ```mix hex.package diff PACKAGE VERSION```, I will print out the error if there is no such package in lock file.

**Comment by RyanSiu1995** [comment]
For the stdout printing, I cannot use ```IO.puts```directly for the file iodata. Any idea on how to print it to stdout?

**Comment by wojtekmach** [comment]
Try IO.binwrite

**Comment by wojtekmach** [comment]
The remaining todo item is tackled in https://github.com/hexpm/hex/pull/705. Closing this then, thanks everyone who made this happen!
