### ISSUE TITLE
Show default and overridden values in `mix hex.config`

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#638]
There are 3 sources of config values for Hex in the following order of precedence:
- ENV variables, e.g. `HEX_API_URL`
- Config value, e.g.: `api_url` in `~/.hex/hex.config`
- Default value

Currently, `mix help hex.config` shows default values and how to override them by config key or ENV variable. `mix hex.config` shows config overrides.

I'd like to propose to adjust `mix hex.config` to show _all_ config options as well as value and whether we use the default value or if it's overridden (and how). This is useful when we've set an ENV variable and forget about it.

```
$ mix hex.config
(...)
api_url: "http://localhost:4000" (using `HEX_API_URL`)
offline: true (using `~/.hex/hex.config`)
unsafe_https: false (default)
(...)
```

The `api_key` is kinda tricky, because it's set by `mix hex.user auth` but can be overriden with `api_key` config and `HEX_API_KEY` var, perhaps we show as:

```
api_key: <secret>
# or
api_key: "abcd..." (using `~/.hex/hex.config`)
# or
api_key: "abcd..." (using `HEX_API_KEY`)
```

Perhaps instead of "using X" it should be "overridden with X".

One caveat: this makes the output pretty verbose, perhaps we should use colors to distinguish, yellow for overriden, and/or enable it on `mix hex.config --verbose`.

**Comment by supersimple** [comment]
I like it.
I think the "using X" verbiage makes the most sense. "overridden" would make more sense if we showed the default value along side of it.

**Comment by ericmj** [comment]
@wojtekmach I think we can move this from RFC to feature request.
