### ISSUE TITLE
[Feature Request] Accept repo public key from STDIN or URL

### ISSUE THREAD

**Issue by vassilevsky** [hexpm/hex#642]
Hello 👻

So right now the shortest way to add a custom repo to hex client is this:

    curl https://hex.acme.com/public.pem -so /tmp/public.pem
    mix hex.repo add acme https://hex.acme.com --public-key /tmp/public.pem

A very minor issue is that it's a bit long.

Would you be interested in a pull request that shortens this?

If so, what do you believe is the best way to shorten this? Several things come to mind:

* `mix hex.repo add acme https://hex.acme.com` can try to download the key by its own by default
* `curl https://hex.acme.com/public.pem | mix hex.repo add acme https://hex.acme.com`, where the `add` command reads the key from standard input by default

What do you think?

This is a very minor issue and I'm fine if nothing ever gets done :)

**Comment by wojtekmach** [comment]
A common convention is to make `-` read from stdin, so: `mix repo.add ... --public-key -`.

That being said, we can achieve the same thing with some bash magic:

```
mix hex.repo add acme https://hex.acme.com \
  --public-key <(curl https://hex.acme.com/public.pem)
```

Perhaps that's enough?

**Comment by ericmj** [comment]
Where are you using this? I am trying the use case for making it a two-liner instead of a one-liner.

I would guess this is mostly used on CI and when setting up a new machine. For those cases I don't think it's worth the development and maintenance for this feature.

**Comment by vassilevsky** [comment]
It’s currently used in a build script. The script runs in a docker container. You’re right: it’s not a big deal 🙂

Great Bash trick!
