### ISSUE TITLE
Add :repo option to :package in mix.exs

### ISSUE THREAD

**Issue by artemeff** [hexpm/hex#656]
Since v0.16.0 we can add custom repos with `mix hex.repo add` and fetch dependencies from our custom repo with `:repo` key in deps.

And when I want to publish package to custom repo — I have to use env variables (`HEX_API_URL` and `HEX_API_KEY`) and some creepy things may happen if I forget to put them  :)

I want to add `:repo` key to `:package` section in mix.exs specification and then we don't want to provide env variables every time and ensures that package published on our custom repo.

Do you accept it? :)

**Comment by wojtekmach** [comment]
Yes, we definitely should support this although its a bit tricky since publishing goes through HTTP API (e.g. hex.pm/api) and not Repo API. (e.g. repo.hex.pm). As far as the default repo, hexpm, is concerned Repo API is currently read-only. It does make sense of course for custom repos to support reading and publishing packages.

Perhaps we can assume that if package has :repo key, we should use repo url to publish? @ericmj?

@artemeff ket us know if you’d like to work on a PR after its a bit Clearex how to proceed.

**Comment by artemeff** [comment]
@ericmj https://github.com/artemeff/hex_mini
@wojtekmach I'm actually already implemented it and just make sure that there's no pitfalls :)

**Comment by ericmj** [comment]
In your case the repo and API share the same base URL, but this is not true for all implementations. I think it would be better to add an `:api_url` configuration to the package configuration instead.

**Comment by wojtekmach** [comment]
@ericmj what I meant was that behind repo url there'd a server that implements Repo API and a very small subset of HTTP API - just the release publishing endpoint. The idea would be not to have to set the HEX_API_URL env var, as @artemeff said, which would be less error prone I think.

**Comment by wojtekmach** [comment]
+1 for `:api_url` in mix.exs

**Comment by ericmj** [comment]
> what I meant was that behind repo url there'd a server that implements Repo API and a very small subset of HTTP API - just the release publishing endpoint 

I don't think that's a good idea because there is overlap in the repo and API urls so we would get conflicts depending on how the API is used. For example `myrepo.com/packages` and `myapi.com/api/packages`.

**Comment by wojtekmach** [comment]
For publishing we have the `/api/publish` endpoint (https://github.com/hexpm/hexpm/pull/674 ;-))

**Comment by ericmj** [comment]
Right, if it only will be used for publishing it would work. But shouldn't all `mix hex.*` tasks use the `api_url` from the project config? I think it would be confusing to add a configuration for the api url that is only used for publishing. But if that's what we want maybe it should be `publish_url` instead?

**Comment by wojtekmach** [comment]
Yes, I think a distinct `publish_url` sounds even better.

The only thing that I'm not sure about is it would be a bit different than setting the repo in mix.exs. For repo, we'd keep the repo name (and assume the user configured it with `mix hex.repo add`) but not the URL which feels better (I'm making this up, but maybe there's a scenario where an internal repo has a different URL when accessed from inside office network and from home). At the same time, I'm not sure what other choice do we have besides hardcoding api_url in mix.exs.

**Comment by wojtekmach** [comment]
I guess an alternative is to have: `mix hex.repo add NAME URL [PUBLISH_URL]`?

**Comment by wojtekmach** [comment]
OK, the problem with `mix hex.repo add NAME URL [PUBLISH_URL]` is besides publishing we also need to support reverting a release (for custom repos it might be bigger window than 1h on hex.pm) which can be the same URL (just different http method) but also retiring a release. I don't think we should keep adding potentially many different URLs then :(

**Comment by artemeff** [comment]
@wojtekmach so maybe just `mix hex.repo add NAME URL [REPO_URL]`?

**Comment by wojtekmach** [comment]
> so maybe just mix hex.repo add NAME URL [REPO_URL]?

the URL argument is the repo url :)

**Comment by wojtekmach** [comment]
I believe we even had it at one point that repo could have api url but decided against it as it conflates these two concepts (api and repo) under repo and repo is mostly about registry and serving packages, api is about things like package search, owners, package metadata etc. We also think that users of custom repos will rarely implement http api (again, search etc). I'm not sure what's the best way to solve this problem but it's likely not adding api url to repo (but hey, maybe it is, not sure)

**Comment by artemeff** [comment]
any thoughts? :)

**Comment by wojtekmach** [comment]
It's still not clear how to best solve it.

Going back to your initial message:

> And when I want to publish package to custom repo — I have to use env variables (`HEX_API_URL` and `HEX_API_KEY`) and some creepy things may happen if I forget to put them :)

> I want to add `:repo` key to `:package` section in mix.exs specification and then we don't want to provide env variables every time and ensures that package published on our custom repo.

To prevent the situation that we accidentally publish the package publicly, what if when we attempt to publish a package that has a `:repo` key, we at least ensure that `HEX_API_URL` (*) is set and fail with a decent error message otherwise?

(*) I think we'd check if `api_url` config is set to non-default value, so either the user set `HEX_API_URL` or did: `mix hex.config api_url https://priv/...`. There's an edge case that someone did `mix hex.config api_url https://hex.pm/api` we'd consider that as non-default too.

**Comment by wojtekmach** [comment]
Scratch that, I think adding `:api_url` option to `:package` in mix.exs is the way to go.
