### ISSUE TITLE
mix hex.outdated shows yanked versions as updatable.

### ISSUE THREAD

**Issue by jamesotron** [hexpm/hex#659]
Hi all.

Today I ran `mix hex.outdated` on a project and saw that `guardian` can be upgraded:

```
Dependency           Current  Latest  Update possible
guardian             1.1.1    1.2.0   Yes
```

But when I ran `mix hex.update guardian` I got the following error:

```
Upgraded:
  guardian 1.1.1 => 1.2.0 RETIRED!
    (invalid) Fails to compile
```

**Comment by ericmj** [comment]
`mix hex.outdated` returns what you can update to and you can indeed update to guarding 1.2.0 as shown in the output. In this case the dependency does not seem to compile which makes it pretty useless to update to but the retirement reason can be less severe than failing to compile so you may still want to use it.

In summary a retired version is not "yanked", you can still use them and update to them so they are not filtered from `mix hex.outdated`. It is recommended that authors not retire the latest version without publishing a new working one short after to avoid issues like this.

**Comment by jamesotron** [comment]
Okie dokie. Thanks!
