### ISSUE TITLE
Uploading large packages are not handled well.

### ISSUE THREAD

**Issue by novabyte** [hexpm/hex#66]
I have an Elixir project which bundles a Jar package. The Jar package is a "uber jar" it contains all of its dependencies. This makes it (unfortunately) about 6.8MB in size.

When using Hex to upload the package I get error output like:

```
Proceed? [Yn] y
[#########################] 100%
10:57:19.116 [error] [85, 110, 107, 110, 111, 119, 110, 32, 109, 101, 115, 115, 97, 103, 101, 32, 105, 110, 32, 104, 116, 116, 112, 99, 95, 109, 97, 110, 97, 103, 101, 114, 58, 104, 97, 110, 100, 108, 101, 95, 105, 110, 102, 111, 32, [123, ['#Ref<0.0.0.399>', 44, ...], 125], '\n']
[#######################  ] 93%
Published diver v0.1.1
```

I believe the release is uploaded to Hex successfully but the error message makes me unsure.

**Comment by ericmj** [comment]
I have reported the issue on the OTP bug mailing list but got no response. Nothing to do but close the issue :(
