### ISSUE TITLE
Setting `api_key` fails with "Invalid key"

### ISSUE THREAD

**Issue by pbober** [hexpm/hex#660]
With hex 0.19.0 it's impossible to set `api_key` by calling `mix hex.config`, although this option is documented:
```
$ mix hex.config api_key "123"
** (Mix) Invalid key api_key
```

It seems this was introduced by https://github.com/hexpm/hex/commit/9f1cfb05483afa5f4b2e947834354acb21980a20#diff-4394a731980d50a5ccbba9dcdda7bdbdL49
Is this behaviour intended?

**Comment by ericmj** [comment]
It's not intended this key should still be readable and writeable as `api_key`.
