### ISSUE TITLE
Error reverting package

### ISSUE THREAD

**Issue by kipcole9** [hexpm/hex#669]
### Environment
OTP 21
Elixir 1.8.1

### Issue
Attempting to revert a package results in an error returned from `mix hex.publish`.  `mix help hex.publish` describes the `--revert` option as defined.

### Example
```
Kips-iMac-Pro:cldr_collation kip$ mix --version
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Mix 1.8.1 (compiled with Erlang/OTP 20)
Kips-iMac-Pro:cldr_collation kip$ mix hex.publish cldr_collation --revert
** (Mix) Could not invoke task "hex.publish": 1 error found!
--revert : Missing argument of type string
Kips-iMac-Pro:cldr_collation kip$ mix hex.publish cldr_collation --revert "0.1.0"
** (Mix) Invalid arguments, expected one of:

mix hex.publish
mix hex.publish package
mix hex.publish docs

Kips-iMac-Pro:cldr_collation kip$ mix hex.publish cldr_collation --revert 0.1.0
** (Mix) Invalid arguments, expected one of:

mix hex.publish
mix hex.publish package
mix hex.publish docs
```

**Comment by wojtekmach** [comment]
`mix hex.publish` does not accept package name as argument, its read from mix.exs instead.

`mix hex.publish package` is a subtask (to publish just package without docs) and package is not meant to be a placeholder for package name.

**Comment by kipcole9** [comment]
Thanks @wojtekmach, makes sense in retrospect (unfortunately I'm outside the 1 hour limit now and can't revert a new package I published under the wrong name).  Perhaps the help message would be clearer if it said something like:
```
mix hex.publish [--revert]
mix hex.publish package [--organization | --yes | --dry-run]
mix hex.publish docs
```
If so I'll happily send a PR.

**Comment by wojtekmach** [comment]
Yes, I think we should clarify it, perhaps even:

`mix hex.publish [--revert VERSION]’

although Im not sure if we are showing args like that for other subtasks, if not perhaps we should.

A PR would definitely be appreciated.

And remember to retire the release if its invalid! :)

**Comment by ericmj** [comment]
New packages can be reverted within 24 hours so you should still be within the window.

We can add a section about reverting to `mix help hex.publish` but listing all possible flags in the error message would not viable, some tasks have many options. I think it's expected to check the docs if you get an error when using task.

**Comment by wojtekmach** [comment]
> but listing all possible flags in the error message would not viable, some tasks have many options

I agree that we shouldn't list all possible options.

I'd argue that `--revert VERSION` isn't the same as e.g. `--dry-run` option; it does completely different behaviour and I'd go as far as considering it a subtask even though it doesn't have the same shape as other subtasks.

The full error message could be:

```
** (Mix) Invalid arguments, expected one of:

mix hex.publish [--revert VERSION]
mix hex.publish package [--revert VERSION]
mix hex.publish docs [--revert VERSION]
```

I'm not sure if we should break the convention, about how subtasks look like, but I think it'd provide more information. WDYT?

**Comment by ericmj** [comment]
> I'd argue that `--revert VERSION` isn't the same as e.g. `--dry-run` option; it does completely different behaviour and I'd go as far as considering it a subtask even though it doesn't have the same shape as other subtasks.

I would also argue that it should be a subtask in that case.

**Comment by wojtekmach** [comment]
WDYT about the following?

```
mix hex.publish [--package|--docs]
mix hex.publish revert [--package|--docs] VERSION
```

**Comment by kipcole9** [comment]
I would feel that `mix hex.revert` would be better - its orthogonal to `mix hex.publish` in my mind.

Thanks for the tip that I had 24 hours to revert a new package.  I didn't know that.

**Comment by wojtekmach** [comment]
> I feel that `mix hex.revert` would be better - it's orthogonal to `mix hex.publish` in my mind.

That'd definitely be the most discoverable though we already have a lot of Mix tasks. With this, we'd have `mix hex.{publish, revert, retire}` all different of course but still somewhat related.

**Comment by josevalim** [comment]
One option is to merge revert and retire into one. They are both about marking a package as "bad". The `--remove` flag can be the one permanently removing it (or `--permanently` or similar).

**Comment by wojtekmach** [comment]
I think I like this idea to merge revert & retire into one, I think both operations are conceptually similar and so the usage should be too: they should take package name and version.

Are you thinking about introducing a new task or re-using an existing one?

Maybe `mix hex.retire foo 1.0.0 --remove`?

**Comment by josevalim** [comment]
I would reuse.

**Comment by ericmj** [comment]
We are currently not planning to add more tasks to avoid inflation of number tasks hex provides. We are interested in improving the error messages when passing invalid arguments to tasks but that should be tackled in a separate issue.
