### ISSUE TITLE
Cannot install new version of hex after fresh install of Elixir 1.0.2 (Windows)

### ISSUE THREAD

**Issue by outamaa** [hexpm/hex#67]
After installing Elixir 1.0.2 with the Windows installer, running mix commands results in the following print:

```
Mix requires hex >= 0.5.0 but you have 0.4.2
Shall I abort the current command and update hex? [Yn]
```

Answering Y results in the following error:

```
** (Mix.Error) Unable to overwrite open archives on Windows. Run the command aga
in
    (mix) lib/mix.ex:235: Mix.raise/1
    (mix) lib/mix/tasks/archive.install.ex:58: Mix.Tasks.Archive.Install.install
_archive/2
    (mix) lib/mix/tasks/local.hex.ex:55: Mix.Tasks.Local.Hex.ensure_updated?/0
    (mix) lib/mix/cli.ex:22: Mix.CLI.proceed/1
    (elixir) lib/code.ex:316: Code.require_file/2
```

The same error occurs when attempting to install hex with mix local.hex

**Comment by bgianfo** [comment]
@ericmj or @josevalim could we get this re-opened, as it appears this is still repro-ing? 

I'm running elixir 1.0.2 and I still see this behavior with the latest hex release:

    C:\src\> mix local.hex
    Are you sure you want to install archive https://hex.pm/installs/hex.ez?elixir=1.0.2? [Yn] Y
    ** (Mix) Unable to overwrite open archives on Windows. Run the command again

    C:\src\> mix local.hex
    Are you sure you want to install archive https://hex.pm/installs/hex.ez?elixir=1.0.2? [Yn] Y
    ** (Mix) Unable to overwrite open archives on Windows. Run the command again

    C:\src\> mix local.hex
    Are you sure you want to install archive https://hex.pm/installs/hex.ez?elixir=1.0.2? [Yn] Y
    ** (Mix) Unable to overwrite open archives on Windows. Run the command again

**Comment by ericmj** [comment]
@bgianfo There is no fix. We can only give instructions on how to fix it manually. It will be included in the next release.
