### ISSUE TITLE
follow XDG base dir specification

### ISSUE THREAD

**Issue by NobbZ** [hexpm/hex#675]
### Current behavior

Hex saves it configuration, downloaded data, caches, etc to `~/.hex`

### Expected behavior

It should follow the [XDG Base Dir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and use appropriate folders from the users configuration to save aforementioned stuff.

This makes it easier for a user to wipe caches, backup config or archives, etc.

**Comment by wojtekmach** [comment]
Could you send a proposal to which subdirectory each file (that Hex currently creates) should belong t o in order to follow XDG?

PS worth mentioning that where Hex stores files is configurable via `HEX_HOME` environment variable.

**Comment by NobbZ** [comment]
Currently I see those files:

* `cache.ets`, which obviously belongs into `$XDG_CACHE_HOME/hex`.
* `hex.config` which obviously belongs into `$XDG_CONFIG_HOME/hex` (or as a single file directly in `$XDG_CONFIG_HOME`)

Also this folder:

* `packages` which seems to contain cached tarballs as well as another folder `hexpm` which again contains tarballs. After a yesterdays discussion with @ericmj I learned that its safe to delete `~/.hex/packages` and its content. Therefore I suggest having it in `$XDG_CACHE_HOME` as well.

> PS worth mentioning that where Hex stores files is configurable via `HEX_HOME` environment variable.

Which I am aware of and thankful for, still I have configuration and cache interleaved in the same folder. I can not simply `cp -r $HEX_HOME $BACKUP_FOLDER`, but I have to selectively name each config file that lives there, and even worse, if upstream adds another config file, I'll probably miss to backup it. Of course I do not like to have cached data in my backup, as it unnecessarily bloats the backups disk usage.

**Comment by ericmj** [comment]
This has been tackled in mix [1][2], and we should do the same for hex. This issue is up for grabs. @NobbZ summarized well where we expect the files to be stored.

[1] https://github.com/elixir-lang/elixir/pull/8933
[2] https://github.com/elixir-lang/elixir/commit/6d58085d779f378ddfa5c550d0f276534a1a7267

**Comment by haseebeqx** [comment]
I will try to solve this. The trickiest part must be embedding this logic into state module.

**Comment by wojtekmach** [comment]
Fixed in #760.
