### ISSUE TITLE
Could not start Hex.

### ISSUE THREAD

**Issue by v6** [hexpm/hex#68]
This is somewhat similar to the following issue: 

https://github.com/hexpm/hex/issues/60

Could not start Hex. Try fetching a new version with `mix local.hex` or uninstalling it with `mix archive.uninstall hex.ez`
*\* (UndefinedFunctionError) undefined function: :ssl.start/0 (module :ssl is not available)
    :ssl.start()
    lib/hex.ex:17: Hex.start_api/0
    lib/hex.ex:9: Hex.start/0
    (mix) lib/mix/tasks/local.hex.ex:69: Mix.Tasks.Local.Hex.start/0
    (mix) lib/mix/dep/loader.ex:117: Mix.Dep.Loader.with_scm_and_app/1
    (mix) lib/mix/dep/loader.ex:86: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
    (mix) lib/mix/dep/loader.ex:234: Mix.Dep.Loader.mix_children/1

Steps to recreate: 

 # unset http_proxy
 # unset HTTP_PROXY

 # git clone https://github.com/phoenixframework/phoenix.git && cd phoenix && git checkout v0.5.0 && mix do deps.get, compile

**Comment by dreamingblackcat** [comment]
I had encountered the same error on my ubuntu 14.04 laptop. I solved it by installaing the erlang package.
erlang-base package did not include all erlang modules. I ran "sudo apt-get insall erlang" and it was solved. Hope this helped to anybody who encountered the same error.

**Comment by v6** [comment]
I'll try that, @dreamingblackcat. 

I thank you for reporting your findings. We're all in this self-modifying-code-that-no-one-seems-to-appreciate boat together. 

Can I pull-request the addition of a note about pre-requisites for this to the `README.md`?

**Comment by josevalim** [comment]
Maybe we could add to the FAQ on the website or is that too obscure? We just need a place people will find when googling this... :D

**Comment by v6** [comment]
This is why I need to make yet another shitty tech. blog.
