### ISSUE TITLE
no function clause matching in Hex.State.to_boolean/1

### ISSUE THREAD

**Issue by djthread** [hexpm/hex#683]
Hello! I just went to build my Distillery release (which has worked in this project before) and the build is failing with this error. I notice both `mix deps.get` and `mix hex.config` both cause it. In the same output, I can see that `mix local.hex --force` installed hex-0.19.0.

The Dockerfile and project in question can be found at https://github.com/djthread/lucidboard/blob/master/assets/ops/release/Dockerfile

Thank you!

```
...
Step 16/25 : RUN mix do deps.get, deps.compile, compile
 ---> Running in a52f630afef5

12:13:46.225 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Hex.State.to_boolean/1
            (hex) lib/hex/state.ex:203: Hex.State.to_boolean("")
            (hex) lib/hex/state.ex:179: Hex.State.load_config_value/2
            (hex) lib/hex/state.ex:102: anonymous fn/2 in Hex.State.init/1
            (elixir) lib/map.ex:210: Map.new_transform/3
            (hex) lib/hex/state.ex:101: Hex.State.init/1
            (elixir) lib/agent/server.ex:8: Agent.Server.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6

12:13:46.228 [info]  Application inets exited: :stopped

12:13:46.229 [info]  Application ssl exited: :stopped

12:13:46.229 [info]  Application public_key exited: :stopped

12:13:46.229 [info]  Application asn1 exited: :stopped

12:13:46.229 [info]  Application crypto exited: :stopped
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:function_clause, [{Hex.State, :to_boolean, [""], [file: 'lib/hex/state.ex', line: 203]}, {Hex.State, :load_config_value, 2, [file: 'lib/hex/state.ex', line: 179]}, {Hex.State, :"-init/1-fun-0-", 2, [file: 'lib/hex/state.ex', line: 102]}, {Map, :new_transform, 3, [file: 'lib/map.ex', line: 210]}, {Hex.State, :init, 1, [file: 'lib/hex/state.ex', line: 101]}, {Agent.Server, :init, 1, [file: 'lib/agent/server.ex', line: 8]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}]}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:7: Hex.start/0
    (mix) lib/mix/hex.ex:58: Mix.Hex.start/0
    (mix) lib/mix/dep/loader.ex:189: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/dep/loader.ex:348: Mix.Dep.Loader.mix_children/1
    (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix) lib/mix/dep/converger.ex:57: Mix.Dep.Converger.all/4
The command '/bin/sh -c mix do deps.get, deps.compile, compile' returned a non-zero code: 1
make: *** [build] Error 1
```

**Comment by ericmj** [comment]
Can you share your `~/.hex/hex.config` file? Make sure to redact any base16/base64 encoded strings.

**Comment by djthread** [comment]
Right. It's inside the fresh container... This was building in the past, so I'm not sure what the difference is here. I did try `rm -rf ~/.hex` in the pipeline leading up to the `mix deps.get` and it didn't seem to help.

**Comment by ericmj** [comment]
It would be very helpful if you could find a way to reproduce this outside of your docker container.

**Comment by RyanSiu1995** [comment]
Maybe you can add a command right before ```mix do deps.get, deps.compile, compile``` to print off the ```~/.hex/hex.config```.
So we can help you to troubleshoot the problem.

**Comment by djthread** [comment]
I had tried removing `~/.hex` as I mentioned, and got the same result. Dumping the file instead reveals that it never existed in the first place.

I'm not sure how I can go about trying to reproduce the issue in my host Mac... of course these command work fine there. So I'm the only person with this issue? Are you guys at least able to reproduce the issue with my project?

```
...
Step 16/26 : RUN echo "BEGIN"; cat ~/.hex/hex.config; echo "END"
 ---> Running in 6f31ad0933bc
BEGIN
cat: can't open '/root/.hex/hex.config': No such file or directory
END
Removing intermediate container 6f31ad0933bc
 ---> ef59b09ab39b
Step 17/26 : RUN mix do deps.get, deps.compile, compile
... [goes on to produce the same error] ...
```

**Comment by ericmj** [comment]
@djthread You need to add `--build-arg QL_MODE=1` to `docker build`.

**Comment by djthread** [comment]
Thank you so much for pointing this out, @ericmj! I'm still trying to figure out the best way to add my company's trusted certs, but this seems to have set me down the right path.

I guess the thing that made it especially challenging is how this had worked in the past, so I wasn't able to correlate the issue to my build arg.

At any rate, thank you very, very much for helping me resolve this one! <3

**Comment by ericmj** [comment]
Are you using a private repository or accessing the hexpm repository through an internal proxy? Could you please open a separate issue so that we can better support this.
