### ISSUE TITLE
Improve mix hex.outdated to specify which mix env to pull dependencies for.

### ISSUE THREAD

**Issue by sircinek** [hexpm/hex#692]
As discussed on elixir-lang slack with @ericmj I think this could be useful addition to mix hex.outdated task to be able to specify for which env the dependencies should be inspected, for eg. to exclude test env only dependencies.

**Comment by supersimple** [comment]
do you think `mix hex.outdated --only <envname>` would work?
or `mix hex.outdated --except [<envnames>]` instead?

My case for the --only flag would be for explicitness, but i am not sure if it is as useful.

WDYT?

**Comment by sircinek** [comment]
Personally I see more value in `--exclude` certain envs, like `test` but I understand the argument for `--only` option as well :)

**Comment by supersimple** [comment]
And would you expect the value to be a list or just a binary?

**Comment by sircinek** [comment]
I would be fine with option to exclude single env, so binary works for me, list gives more flexibility though and parsing shouldn't be hard :)

**Comment by ericmj** [comment]
I would prefer `--only` to match the `only: ...` option in `mix.exs`.

**Comment by sircinek** [comment]
How would `--only` work for dependencies without the `only: ...` option in `mix.exs` ? They would get pulled to any profile, while the `only: env` would be used only when `--only env` is specified ?

**Comment by ericmj** [comment]
It would work like `mix deps.get --only`, so if you have:

```elixir
[
  {:mint, "~> 0.1.0"},
  {:ex_doc, ">= 0.0.0", only: :dev},
  {:mox, "~> 0.5.0", only: :test}
]
```

Then `mix hex.outdated --only prod` would return `[:mint]` and `mix hex.outdated --only dev` would return `[:mint, :ex_doc]`.

We probably don't have to implement this in Hex, we can piggyback on Mix's existing functionality for this.

**Comment by sircinek** [comment]
Ok, that's what I was after, so `prod` is implicit if `only` is not defined. Then I am totally fine with adding `--only`. It seems easy, maybe I will look into contributing :)

**Comment by ericmj** [comment]
Yeah, but just to clarify: `prod` is not specially handled. Anything that doesn't have an explicit `:only` will match anything. You could do `mix hex.outdated --only foobar` and it would match the same as `:prod`.

**Comment by supersimple** [comment]
@sircinek I know it has been a while since this discussion was active. Currently, none of the functionality we need from Mix to incorporate this feature is public. That changes the cost/benefit ratio and we have decided to hold off on this for now. If we discover other uses for the env functionality we may re-open this.
Thanks for taking the time to suggest this feature. :taco: :taco: :taco:
