### ISSUE TITLE
Print warnings and dependencies when publishing package at the end

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#70]
Today, a lot of people miss the warning where we say git packages will not be included. I propose for us to move the dependencies at the end (dependencies are more important than the package files in my opinion) and in case of warnings like this one or in case of missing fields, maybe have a [WARNING] or something in red prefixing it.

**Comment by JamesS237** [comment]
I'll take this one. I was thinking about it recently.

**Comment by JamesS237** [comment]
@josevalim Have a look at #77 and let me know what you think! :boom:
