### ISSUE TITLE
Allow mix hex.outdated to exit 0 on pinned deps

### ISSUE THREAD

**Issue by rajones-hntb** [hexpm/hex#706]
I would be nice to have mix hex.outdated exit with a code 0 when a version is pinned (no ~> and n.n.n expressed) so that we can fail builds on out of date deps, but still pin to versions we need to use.

**Comment by supersimple** [comment]
@rajones-hntb Thank you for filing an issue.
Can you please explain this idea a little more? I am not sure I understand.

For instance, if you have `{:some_dep,  "0.1.0"}` in your mix.exs file, and there is a newer version available. You run `mix hex.outdated` and you _do_ want it to exit with a 0 code (indicating no error)?

**Comment by supersimple** [comment]
@rajones-hntb I am going to close this for now since I haven't heard back. If you missed the notification and want to discuss this as a feature request, please continue to reply on this issue.
