### ISSUE TITLE
Hex overrides IO.ANSI.enabled? setting in Hex.Shell

### ISSUE THREAD

**Issue by halfbyte** [hexpm/hex#710]
See:

https://github.com/hexpm/hex/blob/b6012aa3e14b640feff1d0f5ffe2038f28c4cb1f/lib/hex/shell.ex#L122-L126

The problem is that this piece of code overrides Elixir's internal terminal detection and sets emit? always to true for non test environments, which I believe is a mistake.

Happy to provide a PR if it is agreed on that this is a bug.

Reason I found this is because I am programatically using Mix to update mix.lock files and I was wondering why dependency conflicts were always output with ANSI control sequences when I was quite sure that the environment was not a terminal.

I am very new to Elixir and have no idea what the best ideomatic solution for this would be but I think it should be at least:

```elixir
if Mix.env() == :test do
  def ansi_enabled?(), do: false
else
  def ansi_enabled?(), do
    IO.ANSI.enabled?
  end
end
```

**Comment by ericmj** [comment]
Thank you for the report! This is indeed wrong, please send a PR with your suggested fix.
