### ISSUE TITLE
Request failed (:timeout)

### ISSUE THREAD

**Issue by MarkHoo** [hexpm/hex#717]
Request failed (:timeout)
If this happens consistently, adjust your concurrency and timeout settings:

    HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/tzdata-1.0.0.tar)

**Comment by ericmj** [comment]
If you get timeouts it is likely a network issue since we haven't received any reports of users getting timeouts on good connections. In any case we need more information to help you since this error doesn't give us enough to investigate.

**Comment by MarkHoo** [comment]
Thank you！
After the mirror is replaced, it returns to normal.

https://hex.pm/docs/mirrors

**Comment by ericmj** [comment]
I would guess it's an issue with the mirror in that case. Which mirror are you using and how are you configuring to use it?

**Comment by MarkHoo** [comment]
> mix hex.config mirror_url https://repo.hex.pm


![image](https://user-images.githubusercontent.com/30554560/67414903-885bfa80-f5f6-11e9-9fd1-81d012f65b2a.png)

**Comment by ericmj** [comment]
You shouldn't set up https://repo.hex.pm as mirror as that is the default, although that shouldn't cause any timeout issues.

**Comment by kasvith** [comment]
Im having the same problem. I can access the package via HTTP

**Comment by DamianArado** [comment]
I had this error while installing `ex_doc`: 

```
New:
  earmark_parser 1.4.32
  ex_doc 0.29.4
  makeup 1.1.0
  makeup_elixir 0.16.1
  makeup_erlang 0.1.1
  nimble_parsec 1.3.1
* Getting ex_doc (Hex package)
Request failed (:timeout)
If this happens consistently, adjust your concurrency and timeout settings:

    HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/ex_doc-0.29.4.tar)
```

I can access the package via http but not via `mix deps.get`, installing an earlier version did the trick but I don't know why the latest one is inaccessible?  :/

**Comment by mrcodings** [comment]
same error here

#0 36.15   ssl_verify_fun 1.1.6
#0 36.15   statistex 1.0.0
#0 36.15   telemetry 0.4.3
#0 36.15   tesla 1.6.0
#0 36.15   timex 3.7.11
#0 36.15   tzdata 1.1.1
#0 36.15   ueberauth 0.10.5
#0 36.15   ueberauth_auth0 2.1.0
#0 36.15   unicode_util_compat 0.7.0
#0 36.15   wallaby 0.30.3
#0 36.15   web_driver_client 0.2.0
#0 36.17 * Getting tesla (Hex package)
#0 59.13 * Getting ex_doc (Hex package)
#0 60.92 Request failed (:timeout)
#0 60.92 If this happens consistently, adjust your concurrency and timeout settings:
#0 60.92
#0 60.92     HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
#0 60.96 ** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/ex_doc-0.29.4.tar)
------
failed to solve: executor failed running [/bin/sh -c mix do deps.get, local.rebar --force, deps.compile]: exit code: 1

**Comment by bighunter513** [comment]
> same error here
> 
> ```
> #0 36.15   ssl_verify_fun 1.1.6
> #0 36.15   statistex 1.0.0
> #0 36.15   telemetry 0.4.3
> #0 36.15   tesla 1.6.0
> #0 36.15   timex 3.7.11
> #0 36.15   tzdata 1.1.1
> #0 36.15   ueberauth 0.10.5
> #0 36.15   ueberauth_auth0 2.1.0
> #0 36.15   unicode_util_compat 0.7.0
> #0 36.15   wallaby 0.30.3
> #0 36.15   web_driver_client 0.2.0
> #0 36.17 * Getting tesla (Hex package)
> #0 59.13 * Getting ex_doc (Hex package)
> #0 60.92 Request failed (:timeout)
> #0 60.92 If this happens consistently, adjust your concurrency and timeout settings:
> #0 60.92
> #0 60.92     HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
> #0 60.96 ** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/ex_doc-0.29.4.tar)
> ------
> failed to solve: executor failed running [/bin/sh -c mix do deps.get, local.rebar --force, deps.compile]: exit code: 1
> ```

try delete mix.lock and reproduce it by mix deps.get

**Comment by MarkHoo** [comment]
> > same error here
> > ```
> > #0 36.15   ssl_verify_fun 1.1.6
> > #0 36.15   statistex 1.0.0
> > #0 36.15   telemetry 0.4.3
> > #0 36.15   tesla 1.6.0
> > #0 36.15   timex 3.7.11
> > #0 36.15   tzdata 1.1.1
> > #0 36.15   ueberauth 0.10.5
> > #0 36.15   ueberauth_auth0 2.1.0
> > #0 36.15   unicode_util_compat 0.7.0
> > #0 36.15   wallaby 0.30.3
> > #0 36.15   web_driver_client 0.2.0
> > #0 36.17 * Getting tesla (Hex package)
> > #0 59.13 * Getting ex_doc (Hex package)
> > #0 60.92 Request failed (:timeout)
> > #0 60.92 If this happens consistently, adjust your concurrency and timeout settings:
> > #0 60.92
> > #0 60.92     HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
> > #0 60.96 ** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/ex_doc-0.29.4.tar)
> > ------
> > failed to solve: executor failed running [/bin/sh -c mix do deps.get, local.rebar --force, deps.compile]: exit code: 1
> > ```
> 
> try delete mix.lock and reproduce it by mix deps.get

- It seems to be caused by timeout. You can try to solve it by setting the mirror.

```sh
$ mix hex.config mirror_url https://hexpm.upyun.com/
```

- Reference:
https://hex.pm/docs/mirrors
