### ISSUE TITLE
Provide more helpful error message when a package version is not found for hex.retire

### ISSUE THREAD

**Issue by lpil** [hexpm/hex#719]
```
louis ~/src/lpil/mix-test.watch (master) ✘ $ mix hex.retire mix_test_watch v1.0.0 invalid --message "Package missing zombie script, fails to run on OSX + Linux"
Local password:
Retiring package failed
Bad request
```

In this instance it should have been `1.0.0` rather than `v1.0.0`. An error message that said that the version `v1.0.0` could not be found would be helpful! :)

**Comment by ericmj** [comment]
Thanks for the report. I changed the error message from "Bad request" to "invalid version: v1.0.0".

**Comment by lpil** [comment]
Thank you :)
