### ISSUE TITLE
hexdocs should give preferences to the doc directory

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#72]
Today, the hex.docs task checks for the docs directory. We should instead check for the doc directory (singular) and, if not available, check for the docs directory. The reason is that OTP uses doc and we should use it too. Basically, the steps are:

1. Check doc exists, if so, use it
2. Check docs exists, if so, print a warning "Your documentation was generated in the docs directory. If you are using ex_doc, please update to the latest which will generate the documentation correctly at the doc directory"
3. If none is available, fail with docs not available

I will work on a fix for ExDoc and we can push new versions around the same time. :heart:

/cc @JamesS237 @ericmj

**Comment by JamesS237** [comment]
@josevalim sure thing :smile:

**Comment by JamesS237** [comment]
@josevalim, All done, opened a pull request (#75). Let me know what you think! :+1:
