### ISSUE TITLE
When publishing to a private repo it still says publishing to hexpm

### ISSUE THREAD

**Issue by anthonator** [hexpm/hex#721]
I believe this is a duplicate of closed issue #490 but I'm still seeing this as of 10/31/2019.

When attempting to publish to a private `mini_repo` hex displays the following message.

```
Publishing package to public repository hexpm.
not found
```

After proceeding with the publish it does successfully publish to the private repo.

The message above should indicate that you are publishing to a private repo.

**Comment by anthonator** [comment]
My `mix hex.info`

Hex:    0.20.1
Elixir: 1.9.2
OTP:    22.0.7

Built with: Elixir 1.8.2 and OTP 20.3

**Comment by anthonator** [comment]
Image of what I'm seeing.

<img width="542" alt="Screen Shot 2019-10-31 at 8 04 21 AM" src="https://user-images.githubusercontent.com/420061/67946395-b40f4f80-fbb7-11e9-879c-6628a244aafb.png">

**Comment by wojtekmach** [comment]
@ericmj how about w display what we have today only if the api_url is the default (`"https://hex.pm/api"`), otherwise we say:

`Publishing package to repository using #{api_url}.`

This means however that when someone has:

```
hex: [
  api_url: "http://localhost:4000/api"
],
organisation: "test_repo"
```

we wouldn't tell them which repo we publish to so that would be a regression in that particular scenario, but I feel like it would be an improvement for most users, and we could handle that edge case later.

**Comment by wojtekmach** [comment]
In mini_repo we tell people to do this:

```elixir
hex: [
  api_url: "http://localhost:4000/api/repos/test_repo",
]
```

and at the time I thought it's easier that way than talking about organisations, and I still kind of feel that way. Maybe mini_repo should be smart enough to route `/api` to `/api/repos/<default_repo>`
and tell people to:

```elixir
hex: [
  api_url: "http://localhost:4000/api",
]
```

And then on the Hex client when api url is non-default we'd say:

- `Publishing package to default repository using http://localhost/api` on blank organisation
- `Publishing package to repository acme using http://localhost/api` on organisation acme

I'm not sure if to handle organisations in mini_repo we'd need to implement organisations endpoint ( to tell whether they're public or not) and I'd rather avoid that initially.

**Comment by ericmj** [comment]
Not sure what mini_repo should do, does it support the organization APIs?

On the client we can say: `Publishing package using #{api_url}` or `Publishing package to repository #{organization} using #{api_url}`.

**Comment by wojtekmach** [comment]
There's no support for `/orgs` endpoints in mini_repo.

> On the client we can say: Publishing package using #{api_url} or Publishing package to repository #{organization} using #{api_url}.

:+1:

**Comment by anthonator** [comment]
Personally, I prefer

> Publishing package using #{api_url} or Publishing package to repository #{organization} using #{api_url}

You could also introduce an optional `:name` property that would allow

```
Publishing package to repository #{name}
```
