### ISSUE TITLE
Using a github dependency to a forked hex package fails 

### ISSUE THREAD

**Issue by roivinir** [hexpm/hex#722]
Using a forked dependency of **cowboy**

```
{:cowboy, git: "git@github.com:ni-kismet/cowboy.git", branch: "master", override: true},      
```

I get this error when doing mix deps.get: 
 
* Updating cowboy (git@github.com:ni-kismet/cowboy.git)
* Updating cowlib (https://github.com/ninenines/cowlib)
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  bypass 1.0.0
  cachex 3.2.0
  certifi 2.5.1
  connection 1.0.4
  db_connection 2.1.1
  decimal 1.8.0
  dialyxir 0.5.1
  ecto 3.2.3
  eternal 1.2.1
  file_system 0.2.7
  gen_leader 0.1.0
  gen_state_machine 2.0.5
  gettext 0.17.1
  hackney 1.15.2
  hammer 6.0.0
  httpoison 1.6.1
  idna 6.0.0
  jason 1.1.2
  jumper 1.0.1
  libcluster 3.1.1
  libring 1.4.0
  metrics 1.0.1
  mime 1.3.1
  mimerl 1.2.0
  ord_map 0.1.0
  params 2.1.1
  parse_trans 3.3.0
  phoenix 1.4.10
  phoenix_ecto 4.0.0
  phoenix_html 2.13.3
  phoenix_live_reload 1.1.7
  phoenix_pubsub 1.1.2
  plug 1.8.3
  plug_cowboy 2.1.0
  plug_crypto 1.0.0
  poolboy 1.5.2
  ranch 1.7.1
  sleeplocks 1.1.1
  ssl_verify_fun 1.1.5
  statistics 0.6.1
  telemetry 0.4.0
  trie 1.7.5
  unicode_util_compat 0.4.1
  unsafe 1.0.1
  uuid 1.1.8
* Updating cowboy (Hex package)
** (Mix) The lock is missing for package cowboy. This could be because another package has configured the application name for the dependency incorrectly. Verify with the maintainer of the parent application

Tried removing the lock file altogether. Tried doing **mix deps.update cowboy** 

No workaround found.

**Comment by ericmj** [comment]
Please include your `mix.exs` and `mix.lock` files so that we can attempt to reproduce.

**Comment by roivinir** [comment]
Resolved the issue by moving the cowboy override into the main mixexs file, and not in another mix.exs in an umbrella app. It was basically a conflict in between the main mix file and one of the others. 

This makes sense and it seems more like an umbrella app error messaging issue than anything else.
