### ISSUE TITLE
Validate symlinks in package

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#725]
They should only allowed to be relative and point to existing files inside the package.

**Comment by starbelly** [comment]
@ericmj Do we want to restrict symlinks to "safe" symlinks via [filename:safe_relative_path_1](http://erlang.org/doc/man/filename.html#safe_relative_path-1) ?

**Comment by ericmj** [comment]
This has been patched in hex_core and should be vendored in this project and rebar3 by now. We are contributing patches upstream to OTP for `erl_tar`.

What is left to tackle is to validate when creating the package tarballs but that should be handled in hex_core.
