### ISSUE TITLE
`mix hex.docs offline` but with EPUB output instead of HTML 

### ISSUE THREAD

**Issue by RickCarlino** [hexpm/hex#731]
I keep offline copies of the documentation for packages via `mix hex.docs offline PACKAGE_NAME`.

I would like to do the same thing, but with the output as EPUB instead of HTML, and ideally, in one step.

Does Hex support this?

Thanks for all the great work on this project!

**Comment by ericmj** [comment]
Packages do not publish their documentation in EPUB format by default so you have to download the package sources and build the documentation manually with ex_doc.

**Comment by RickCarlino** [comment]
Thanks, Eric. This answers my question.

**Comment by supersimple** [comment]
@RickCarlino Thanks for the suggestion. There is a bit of work involved in this so we are documenting that in #732.
I think it's a great idea! 🎉
