### ISSUE TITLE
Document how checksums work

### ISSUE THREAD

**Issue by anthonator** [hexpm/hex#733]
It would be nice if checksum usage was documented somewhere. I need to troubleshoot some checksum issues with a MiniRepo install and I can't find any documentation so I'm not sure how to move forward.

**Comment by wojtekmach** [comment]
There's some docs around checksum itself here: https://github.com/hexpm/specifications/blob/master/package_tarball.md. Is this what you had in mind or other types of docs?

**Comment by anthonator** [comment]
Yes, that does help. Thank you!
