### ISSUE TITLE
`mix hex.docs fetch PACKAGE` should fetch *latest* version

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#741]
Currently we have:

```
~% mix hex.docs fetch postgrex
Docs fetched: /Users/wojtek/.hex/docs/hexpm/postgrex/1.0.0-rc.1
```

However, if we do `mix hex.docs online postgrex` we'd go to v0.15.3. The definition of *latest* is here: https://github.com/hexpm/hexdocs/blob/51f306d5ca779146e9b810ec74d74a4810d4b460/lib/hexdocs/bucket.ex#L92:L121, basically it's the highest _stable_ version number (and if there are none, highest unstable version number)

wdyt @ericmj @supersimple?

**Comment by wojtekmach** [comment]
Btw, it's out of scope of this issue, but I wonder if *latest* should mean highest stable non-retired version?

**Comment by supersimple** [comment]
yes, i would expect the behavior to be consistent across those mix tasks.
