### ISSUE TITLE
Support global exclude patterns option

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#747]
Today we can exclude files per project but some files, like .DS_Store, will show up in every project. So having a global exclude pattern would be helpful. Please see this issue: https://github.com/elixir-ecto/ecto/pull/3221

Thank you! :heart:

**Comment by chulkilee** [comment]
What if a project *needs* such commonly ignored files? e.g. a project to scan a directory to find such files :wink:

I think it would be better to "warn" if such files are found before publishing.

BTW... would't the hidden file also listed in the file list when publishing?

**Comment by josevalim** [comment]
> BTW... would't the hidden file also listed in the file list when publishing?

It is but apparently I am not reading it. :P I am willing to accept it is my fault. :D

**Comment by adrianomitre** [comment]
> What if a project _needs_ such commonly ignored files? e.g. a project to scan a directory to find such files 
> 
> I think it would be better to "warn" if such files are found before publishing.
> 
> BTW... would't the hidden file also listed in the file list when publishing?

In the hypothetical example described, I can see `*.DS_Store` files being used in tests, but I do not see neither them nor the corresponding tests making their way into the published Hex package.

**Comment by ericmj** [comment]
We have an added an automatic exclude on `.DS_Store`. If other files should be excluded we can discuss them separately, but right now there doesn't seem to be a need for a global exclude.
