### ISSUE TITLE
`mix deps.get` hangs and starts eating all available memory, starting hex v0.20.2

### ISSUE THREAD

**Issue by juulSme** [hexpm/hex#752]
Since the release of hex v0.20.2, we have a problem with one - but not all - of our projects. It's an umbrella with 5 apps. When we try to execute `mix.deps.get`, the terminal hangs at `Resolving Hex dependencies...`. The process then starts to eat all available memory and swap, until (apparently) the kernel has had enough and kills it. I've tried this on a machine with 32GB of ram and it happily eats all of it. This issue occurs in- and out of Docker containers with multiple Elixir versions, both alpine- and debian based. The issue does not occur with hex v0.20.1 or lower.

When the process is killed, there's some additional output (screenshot from GitLab build):
![Screenshot from 2020-02-06 10-54-26](https://user-images.githubusercontent.com/16883019/73926148-79603600-48cf-11ea-849e-c8462e2cdf0c.png)
... which is weird, because it sure as hell uses a lot more than 24MB.

To demonstrate the bug, I've put together a repo with our mix files: https://github.com/juulSme/hex-0.20.2-to-5-bug. Cloning and running `docker build .` will cause the issue. Adapting the Dockerfile to use hex v0.20.1 solves it. Maybe the problem is in our mix files somewhere, because we don't experience it with all of our projects.

**Comment by juulSme** [comment]
Update: I've narrowed down the issue a bit further. I've removed some dependencies and some umbrella apps. There's 2 apps left down from 5, `my_app` and `my_app_endpoint` that apparently cause the issue together. They don't share any dependencies except for gettext ~> 0.14.

**Comment by juulSme** [comment]
...except it now also occurs with older hex versions 0.20.1 :boom: 
So in the sample repo https://github.com/juulSme/hex-0.20.2-to-5-bug/commit/ec21870287e06ee2808bd013cdaf27307fe9bc36 the issue occurs with all hex versions.

In the previous commit https://github.com/juulSme/hex-0.20.2-to-5-bug/commit/a2a4ecf5c1b4447695200704eea4acdc0cd114ef the bug does not occur with hex 0.20.1 and earlier.

Mind blown.

**Comment by juulSme** [comment]
Somehow, it seems a dependency conflict between Ecto and Guardian seems to be the culprit: https://elixirforum.com/t/hex-v0-20-2-5-eats-all-memory-and-dies-but-maybe-it-is-us/28904/4?u=jsm

Still, such a conflict should not completely crash hex.

**Comment by ericmj** [comment]
This is a known issue that is fundamental to the way our resolver algorithm works. We've have started exploring alternative implementations but it will take a while until we have something that can replace what we have now. In the mean time I will check if there is a quick workaround for this particular issue.

As a workaround you can do yourself you can remove packages from your dependency definitions until the resolver completes and then start adding them back. The less unlocked packages the resolver has to work with the less likely this issue will occur.

**Comment by ericmj** [comment]
@juulSme Can you double check that the resolution works on hex v0.20.1?

**Comment by ericmj** [comment]
The current plan is to replace the resolver with an algorithm that can more aggressively trim the possible solution space when backtracking. When that is done we can revisit these issues to see if they have been resolved.
