### ISSUE TITLE
Error In Hex when using Minirepo repos

### ISSUE THREAD

**Issue by asummers** [hexpm/hex#753]
I am working on getting Mini Repo set up for my organization. 

When updating to the newest Hex version  (`0.20.5`), and specifying an alternate `repo` in my `mix.exs` via

```
{:my_dep, "~> 1.2.3", repo: "my_repo"},
```

and adding this repo to my config via 

```
mix hex.repo add my_repo $url --public-key $key_path
```

we get the following error when performing `mix deps.get`.

```
14:23:26.976 [error] GenServer Hex.Registry.Server terminating
** (stop) exited in: GenServer.call(Hex.Server, :should_warn_registry_version?, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Hex.Server.handle_call/3
            (hex) lib/hex/server.ex:29: Hex.Server.handle_call(:should_warn_registry_version?, {#PID<0.142.0>, #Reference<0.3697169478.3913023492.231445>}, %{warned_lock_version: false, warned_registry_version: false})
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:1010: GenServer.call/3
    (hex) lib/hex/repo.ex:299: Hex.Repo.decode_package/3
    (hex) lib/hex/registry/server.ex:341: Hex.Registry.Server.write_result/4
    (hex) lib/hex/registry/server.ex:206: Hex.Registry.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

This error did not exist on the the previous hex version installed and I am unsure how to reinstall that version locally. 

Looking at the code in question in  https://github.com/hexpm/hex/blob/master/lib/hex/server.ex#L41 it looks like maybe the maps should be matching on `:warned_registry_version` instead of `:warned_registry_size` but I am not positive the intention behind the previous change in this file.

**Comment by wojtekmach** [comment]
Thank you for the report, I can reproduce this locally by running mini_repo tests using Hex 0.20.5.

**Comment by ericmj** [comment]
@wojtekmach Does mini_repo have a mechanism to rebuild the registry to fix this error (future warning)?

**Comment by wojtekmach** [comment]
I started updating mini_repo to emit the new checksum [1] but a) I need more time to finish this up properly and test against old Hex clients and b) you're totally right, we should have a manual/automatic migration path for this, good call.

[1] https://github.com/wojtekmach/mini_repo/compare/wm-outer-checksum
