### ISSUE TITLE
Add a flag to `mix hex.outdated -all` to only exit on non-major updates

### ISSUE THREAD

**Issue by edisonywh** [hexpm/hex#758]
Currently in our CI we run a step to check for outdated dependencies, like this:

> `mix deps.updated --all`

and then we do this:

> `git diff --exit-code`

This tells git to exit with exit-code 1 if there is a diff, which is kinda nice as it can make sure our dependencies are up to date (on the minors and bug fixes at least).

We are aware of `mix hex.outdated --all`, which is mostly what we want, with one key difference being that `hex.outdated` will exit on major bumps too, which is what we want to avoid, because we don't want to stop devs from merging when there is a new major version out for a dependency, as it could potentially be a lot of work to migrate.

> https://github.com/hexpm/hex/blob/v0.20.5/lib/mix/tasks/hex.outdated.ex#L171

Thus I propose to add a flag to allow us to exit on non-major updates, something like:

```
mix hex.outdated --all --except-major
```

What do you think?

**Comment by hauleth** [comment]
I would prefer to have something like `--at-most={major|minor|patch|pre}` which would allow picking which part can be assumed as an upgrade, so `--except-major` would be the same as `--at-most=minor`.

**Comment by ericmj** [comment]
Instead of `--except-major`, how about `--within-requirements` where we only show updates that are within the current requirements?

Most dependency requirements are specified as `>~ X.Y` which means it would be similar to `--except-major`. But since it only checks possible updates it would work like `mix deps.updated --all && git diff --exit-code`.

**Comment by edisonywh** [comment]
I like the idea @ericmj, that's much more versatile and also sticks to the existing version requirements convention!

I'd be happy to work on this if this gets approved :)

**Comment by wojtekmach** [comment]
`--within-requirements` sounds good to me!

Currently we output e.g.:

```
Dependency           Current  Latest  Update possible
bamboo               1.3.0    1.4.0   Yes
```

I believe that when using `--within-requirements` we shouldn't show the last column as the answer should always be "Yes"?

I'd argue it should even be the default behaviour and instead you'd opt-in to see updates beyond your requirements but I can see it both ways so maybe let's not change that.

Thanks for the suggestion, PR is very welcome!

**Comment by edisonywh** [comment]
Awesome! I took a look at it and it looks rather straightforward so far, I'll come up with a PR within this week hopefully and will ping if I have any questions, thanks!
