### ISSUE TITLE
Hex failed to build - Hex.State.default_api_url/0 is undefined or private

### ISSUE THREAD

**Issue by bukatlib** [hexpm/hex#759]
Hi folks,

I tried to build hex 0.20.5 with Elixir 1.10.2 on Solaris but it fails with the following error:
> == Compilation error in file lib/mix/tasks/hex.config.ex ==
> ** (UndefinedFunctionError) function Hex.State.default_api_url/0 is undefined or private. Did you mean one of:
> 
>       * default/2
> 
>     Hex.State.default_api_url()
>     lib/mix/tasks/hex.config.ex:25: (module)
>     (stdlib 3.11) erl_eval.erl:680: :erl_eval.do_apply/6

If I revert the following part of the change, hex builds fine.
git log -p -1 f8efe9bd143bd592cc70c166b320d70c147a873d lib/mix/tasks/hex.config.ex

I guess that it could be a missing import (Hex.State?) or access policy.

Thanks,
Libor

**Comment by ericmj** [comment]
Looks like you are missing some files or have old files. Make sure you are on a clean checkout of v0.20.5.

**Comment by bukatlib** [comment]
I cloned the hex repository to a new directory and made a checkout of v0.20.5. The error still persists. 
The same situation is for official tarball. Maybe it is related to the latest version of Elixir.

**Comment by bukatlib** [comment]
It is not related to Elixir, I downgraded Elixir to version 1.7.3 and the error still occurs.

**Comment by ericmj** [comment]
If you look at `lib/hex/state.ex` can you see the line `def default_api_url(), do: @api_url`?

**Comment by bukatlib** [comment]
I confirm that I see the line with default_api_url definition.

**Comment by ericmj** [comment]
Does it happen on other machines?

**Comment by bukatlib** [comment]
I tested it also on other Solaris machine, the result is the same.
However, the build is fine on Fedora and I noticed that there are warning during the build process compared to the Solaris.

The warnings are about the redefinition of modules:
warning: redefining module Mix.Tasks.Hex.Config (current version loaded from /usr/lib/elixir/bin/../lib/hex/ebin/Elixir.Mix.Tasks.Hex.Config.beam)

Maybe it could be the root cause of the failure.

**Comment by ericmj** [comment]
It looks like Solaris are installing Hex themselves (which they shouldn't) which is conflicting with your build of Hex. If there is a Solaris Hex package uninstall it or if it is bundled with Elixir then uninstall the Elixir package and build Elixir yourself.

**Comment by bukatlib** [comment]
You are right, Solaris provides elixir and hex packages. If hex is uninstalled, the build finishes without errors. Is there a way to unload installed hex modules before the installation is started instead of removing the system package? Thank you for your help.

**Comment by ericmj** [comment]
Yes, it's possible but we are not going to add custom code for it so you would have to modify Hex.

Here we unload Hex if it is installed as an archive: https://github.com/hexpm/hex/blob/master/mix.exs#L81. You can adapt this code to unload it for the Solaris install path.

**Comment by bukatlib** [comment]
Thank you for the help, I consider it solved.
