### ISSUE TITLE
Custom cacerts_path not being honored in some cases 

### ISSUE THREAD

**Issue by asummers** [hexpm/hex#767]
SHA: `d5c40ef`

```
$ mix hex.config
...
cacerts_path: "/Users/asummers/Code/certs/cert.pem" (using `/Users/asummers/.hex/hex.config`)
...
$ mix hex.search my_private_package

17:57:22.784 [info]  TLS client: In state certify at ssl_handshake.erl:1666 generated CLIENT ALERT: Fatal - Unknown CA

** (FunctionClauseError) no function clause matching in Mix.Tasks.Hex.Search.lookup_packages/1

    The following arguments were given to Mix.Tasks.Hex.Search.lookup_packages/1:

        # 1
        {:error, {:failed_connect, [{:to_address, {'hex.pm', 443}}, {:inet, [:inet], {:tls_alert, {:unknown_ca, 'TLS client: In state certify at ssl_handshake.erl:1666 generated CLIENT ALERT: Fatal - Unknown CA\n'}}}]}}

    (hex) lib/mix/tasks/hex.search.ex:54: Mix.Tasks.Hex.Search.lookup_packages/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

Running `mix deps.get` and `mix hex.outdated` and `mix hex.publish` which were previously giving me similar SSL errors until I put in the proper cert chain resolve correctly with no error. The cert chain contains a self signed cert and the `hex.pm` cert used in hex itself. 

Digging through the code, I did not see any obvious reason for this to not be working. `my_private_package` is hosted on a `mini_repo` instance. Searching for normal `hex.pm` packages fails in the same way. 

Please let me know if I can provide further details.

**Comment by ericmj** [comment]
I cannot reproduce this, is your PEM file correct?

```
> HEX_CACERTS_PATH=~/code/castore/priv/cacerts.pem mix hex.search mint
Package     Description                                  Version  URL
mint        Small and composable HTTP client.            1.0.0    https://hex.pm/packages/mint
mojito      Fast, easy to use HTTP client based on Mint  0.6.1    https://hex.pm/packages/mojito
ex_cogmint  Client for Cogmint Project                   0.0.2    https://hex.pm/packages/ex_cogmint
cogmint     Client for Cogmint Project                   0.0.1    https://hex.pm/packages/cogmint
> mix hex.config cacerts_path ~/code/castore/priv/cacerts.pem
> mix hex.config
api_key: nil (default)
api_url: "https://hex.pm/api" (default)
cacerts_path: "/Users/ericmj/code/castore/priv/cacerts.pem" (using `/Users/ericmj/.hex/hex.config`)
diff_command: "git diff --no-index __PATH1__ __PATH2__" (default)
home: "/Users/ericmj/.hex" (default)
http_concurrency: 8 (default)
http_proxy: nil (default)
http_timeout: nil (default)
https_proxy: nil (default)
mirror_url: nil (default)
no_verify_repo_origin: false (default)
offline: false (default)
repos_key: nil (default)
resolve_verbose: false (default)
unsafe_https: false (default)
unsafe_registry: false (default)
> mix hex.search mint
Package     Description                                  Version  URL
mint        Small and composable HTTP client.            1.0.0    https://hex.pm/packages/mint
mojito      Fast, easy to use HTTP client based on Mint  0.6.1    https://hex.pm/packages/mojito
ex_cogmint  Client for Cogmint Project                   0.0.2    https://hex.pm/packages/ex_cogmint
cogmint     Client for Cogmint Project                   0.0.1    https://hex.pm/packages/cogmint
```

**Comment by asummers** [comment]
It's right enough to satisfy `mix deps.get`, `mix hex.outdated` and `mix hex.publish` which were previously erroring on SSL errors so I believe so. All those calls all seem to funnel as `:get`s through the `Hex.HTTP.request` function, so I'm very unclear where the difference may exist.

**Comment by ericmj** [comment]
Are you saying mix deps.get, mix hex.outdated and mix hex.publish work but mix hex.search doesn't work?

**Comment by asummers** [comment]
Correct.

**Comment by ericmj** [comment]
Can you provide a PEM file that reproduces the issue?

**Comment by asummers** [comment]
I don't believe I can do so, for organizational security reasons. In your local setup are you pointing to a second repo in your `mix hex.repo list` other than `hex.pm` (I feel like organizations wouldn't trip this bug)?

**Comment by ericmj** [comment]
> I don't believe I can do so, for organizational security reasons. 

Maybe you can generate a new certificate that isn't used for your organization that will reproduce the issue?

> In your local setup are you pointing to a second repo in your mix hex.repo list other than hex.pm (I feel like organizations wouldn't trip this bug)?

`mix hex.search` doesn't use organizations unless you pass the `--organization` flag.

**Comment by asummers** [comment]
> mix hex.search doesn't use organizations unless you pass the --organization flag.

I was just trying to see how our local envs might differ and qualifying the "second repo" question. 

I will see what I can do about getting a new cert.

**Comment by asummers** [comment]
Introspecting further it seems like the source of the bug is that `mix hex.search` is using the `api_url` which would not work in a multi-repo world since the user may have repos in many different `mini_repo` instances set up, ignorant of each other so unable to provide a consistent package listing. The behavior for `hex.search` is seemingly undocumented in the hex spec so I am unclear what the expected behavior around this all is supposed to be.

**Comment by ericmj** [comment]
Configuring repositories does just that: configure the "repository". `mix hex.search` uses the API to search for packages which is a separate independent endpoint. If the software you are using for the hex repository also has an API endpoint that supports searching then you can search that by setting `HEX_API_URL=... mix hex.search`.

Since a repository may not have an API and the API URL is not defined relative to the repository URL we cannot search your configured repositories with `mix hex.search`. Additionally, if you have multiple repositories configured it is not clear how to query all and how to display the results from multiple sources.
