### ISSUE TITLE
always timeout in China

### ISSUE THREAD

**Issue by Raymond0331** [hexpm/hex#771]
use mix deps.get or mix local.hex (Official hex repo) command always occur timeout error . Although set HEX_HTTP_TIMEOUT=600, timeout error still happened.  
I was wondering  what CDN service are you using ?  Can update CDN to improve  the situation？

**Comment by supersimple** [comment]
Hello @Raymond0331. We use fast.ly for our CDN. Which part of China are you making the request from?

**Comment by supersimple** [comment]
Hi @Raymond0331 . I am going to close this ticket for now since I have not heard back from you and have not received any error reports from other users I assume it has resolved.

**Comment by Raymond0331** [comment]
> Hello @Raymond0331. We use fast.ly for our CDN. Which part of China are you making the request from?

Beijing city and Guangdong that my request from

**Comment by Raymond0331** [comment]
> Hello @Raymond0331. We use fast.ly for our CDN. Which part of China are you making the request from?

I am wondering if I can use aliyun CDN accelerate  for https://repo.hex.pm in China, but I think I had to get the certificate of hex.pm

**Comment by Raymond0331** [comment]
> Hi @Raymond0331 . I am going to close this ticket for now since I have not heard back from you and have not received any error reports from other users I assume it has resolved.

Sorry too late feedback to you, I hope you still cat get my message

**Comment by ericmj** [comment]
You can put any CDN in front repo.hex.pm and you don't need any certificates from hex to do it.

Can you paste the text block from visiting https://www.fastly-debug.com/.

**Comment by Raymond0331** [comment]
> You can put any CDN in front repo.hex.pm and you don't need any certificates from hex to do it.
> 
> Can you paste the text block from visiting https://www.fastly-debug.com/.

actually, my build server is running on one of the docker containers of cloud service Aliyun , I don't its real IP address, I only know that must from Beijing city .
https://www.fastly-debug.com/   this url can run on command line like curl  tool?  I can start up a container try to get the result and than paste here

**Comment by Raymond0331** [comment]
> You can put any CDN in front repo.hex.pm and you don't need any certificates from hex to do it.
> 
> Can you paste the text block from visiting https://www.fastly-debug.com/.

I've been try to put CDN in front repo.hex.pm, but CDN complaining certificates error

**Comment by Raymond0331** [comment]
> You can put any CDN in front repo.hex.pm and you don't need any certificates from hex to do it.
> 
> Can you paste the text block from visiting https://www.fastly-debug.com/.

I try to rebuild a new cdn it seems work good.
