### ISSUE TITLE
Failed to retrieve package information

### ISSUE THREAD

**Issue by kasperite** [hexpm/hex#777]
I am getting same error when running hex commands eg running `mix hex.info httpoison`.

```javascript
Failed to retrieve package information
{:failed_connect, [{:to_address, {'hex.pm', 443}}, {:inet, [:inet], :eprototype}]}
```
Any suggestion on what is causing this?

`mix hex.config` output:

```javascript
api_key: nil (default)
api_url: "https://hex.pm/api" (default)
cacerts_path: nil (default)
diff_command: "git diff --no-index __PATH1__ __PATH2__" (default)
home: "/Users/lukasn/.hex" (default)
http_concurrency: 8 (default)
http_proxy: nil (default)
http_timeout: nil (default)
https_proxy: nil (default)
mirror_url: nil (default)
no_verify_repo_origin: false (default)
offline: false (default)
repos_key: nil (default)
resolve_verbose: false (default)
unsafe_https: false (default)
unsafe_registry: false (default)
``` 

I'm using latest version of elixir(1.10.2)

**Comment by kipcole9** [comment]
This is saying it can't get a connection to `https://hex.pm`.  Can you try `https://hex.pm/api` in your browser?  If it connects you should see something like the following as a return:
```json
{"documentation_url":"http://docs.hexpm.apiary.io","key_url":"https://hex.pm/api/keys/{name}","keys_url":"https://hex.pm/api/keys","package_owners_url":"https://hex.pm/api/packages/{name}/owners","package_release_url":"https://hex.pm/api/packages/{name}/releases/{version}","package_url":"https://hex.pm/api/packages/{name}","packages_url":"https://hex.pm/api/packages"}
```

**Comment by kasperite** [comment]
hi @kipcole9 , yes I can connect to hex fine from the browser

**Comment by kasperite** [comment]
fyi, I tried to reinstall hex by running `mix local.hex --force` and got:

```javascript
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :eprototype}]}

Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.
```

**Comment by ericmj** [comment]
I have not seen the `eprototype` error before. It means the remote socket is UDP when we expect TCP [1]. Maybe you are on a badly configured corporate or home network?

Please run `mix hex.info` and paste the output here. What operating system are you using?

[1] http://man7.org/linux/man-pages/man7/unix.7.html

**Comment by kasperite** [comment]
@ericmj the issue was indeed to do with bad configured vpn
