### ISSUE TITLE
Allow to generate outdate list from project and upload it to hexdiff

### ISSUE THREAD

**Issue by sezaru** [hexpm/hex#778]
Hey, I just saw Johanna presentation about hexdiff, amazing job with that!

I was wondering if it could be improved a little bit.

The use case would be this one: You have your project, and you run mix hex.outdated, now you have a list of packages that are outdated and needs an update. To be safe, you use hexdiff to verify what changed from each package. But doing so is tiresome as you need to get package by package and select the correct version in hexdiff interface manually.

My suggestion would be to add an option to mix hex.outdated that will generate a file with all the outdated packages, its current version, and the updated version.

And also an option in hexdiff website so we can upload that file, so hexdiff can automatically show the diff for all the packages in order, that way the user can save time.

Would something like that be possible/desirable?

Best regards,
Eduardo

**Comment by supersimple** [comment]
@ericmj @joladev and I spoke about this recently at CodeBEAM.
Having an additional column will make the output very wide, so I think there are other solutions.

one idea is to put all the links at the bottom, each on its own line.
another idea is to generate one link that represents all of the changes (base64 encode the frmo/to) which requires support on the diff.hex site to recognize those links and render a page with the indivudual diffs listed or linked to.

**Comment by joladev** [comment]
Yeah, one question was whether obfuscated links were bad from a security point of view. We could make sure they redirect to the proper URL instead of rendering on the base 64 encoded one.

I think the usability improvement is worth it
