### ISSUE TITLE
hex.outdated displays different "Up-to-date" for the same package

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#784]
When displaying all packages it says "No"

<img width="816" alt="image" src="https://user-images.githubusercontent.com/76071/81692939-72f9d100-945f-11ea-9d09-72548d6760a4.png">

But when displaying a single package it says "Yes"

<img width="821" alt="image" src="https://user-images.githubusercontent.com/76071/81692616-f5ce5c00-945e-11ea-9d61-e3c6356ff54f.png">

---

While at it, we should merge "Up-to-date" and "Update possible" columns into one with the possible values: "Up-to-date", "Update possible", "Update not possible", here's how it could look like:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/76071/81692825-42199c00-945f-11ea-92f1-44b182bf73a0.png">

Maybe instead of green "Up-to-date" we should have green "Yes" though.

wdyt @ericmj @supersimple?

**Comment by ericmj** [comment]
The copy explains the weird behavior: "Up-to-date indicates if the requirement matches the latest version." "Up-to-date" should be "Update possible".

Your suggestion of changing to "Up-to-date", "Update possible", "Update not possible" sounds like a good change we should make for both `mix hex.outdated` and `mix hex.outdated APP`.
