### ISSUE TITLE
Log when http(s)_proxy options are used

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#79]

**Comment by JamesS237** [comment]
@josevalim I'm presuming this would be logged whenever a task that makes http(s) requests is run? If not, when do you think it would be most appropriate to log it?

**Comment by ericmj** [comment]
We should print it like this `Using HTTP_PROXY=...` in `Hex.start` when we set up the options.

**Comment by jw2013** [comment]
:+1:

**Comment by josevalim** [comment]
Wouldn't that print the option even when we don't do any HTTP request?

**Comment by JamesS237** [comment]
@josevalim No, this is only called if a non-standard setting is applied (config/environment variable).

**Comment by josevalim** [comment]
Right, but that would still happen every time we start hex, even if not for issuing requests. I am asking because running your app starts hex, doesn't it?

**Comment by JamesS237** [comment]
I'd assume Hex would only be started alongside another application in the event of grabbing dependencies before starting it. This would be utilizing http(s) proxy environment variables/config values, so I'd assume it would be appropriate to log it.

**Comment by josevalim** [comment]
Ok, I just confirmed in the source, if you specify any hex dependency, we will ensure hex is started, even if not fetching anything, so we definitely cannot log this on Hex.start. Maybe we should move the setting up of httpc profile and of those variables to another function that is invoked only before doing http requests? Unsure...

**Comment by ericmj** [comment]
@josevalim Why are we starting Hex so early. Can we move it to start just before we run the remote converger? Would that help?

**Comment by josevalim** [comment]
It wouldn't help right now as tons of people are already using the released version. :( I don't care though when we start it, anywhere is fine. :)
