### ISSUE TITLE
hex.outdated — Column with link to source/changelog

### ISSUE THREAD

**Issue by tmjoen** [hexpm/hex#793]
I find this a very useful feature with `yarn` for instance:

![image](https://user-images.githubusercontent.com/10501945/86234671-960b4c00-bb97-11ea-9ac0-5191fd746a7c.png)

So when upgrading packages I can just click the URL and find the changelog to read up on the changes instead of searching for each package.

Not sure if this is possible with the available package information?

**Comment by ericmj** [comment]
Unfortunately we don't have reliable links to the source code or changelogs. We can link to the package page on hex.pm.

**Comment by tmjoen** [comment]
That would be great too!

**Comment by wojtekmach** [comment]
On Hex master we're showing a link to the diff:

```
% mix hex.outdated --all
Dependency           Current  Latest  Status
certifi              2.5.1    2.5.2   Update not possible
earmark              1.4.3    1.4.8   Update possible
excoveralls          0.11.1   0.13.0  Update possible
hackney              1.15.1   1.16.0  Update possible
idna                 6.0.0    6.0.1   Update not possible
jason                1.2.0    1.2.1   Update possible
makeup               1.0.0    1.0.3   Update possible
makeup_elixir        0.14.0   0.14.1  Update possible
metrics              1.0.1    2.5.0   Update not possible
mimerl               1.2.0    1.2.0   Up-to-date
nimble_parsec        0.5.0    0.6.0   Update not possible
parse_trans          3.3.0    3.3.0   Up-to-date
ssl_verify_fun       1.1.4    1.1.6   Update not possible
unicode_util_compat  0.4.1    0.5.0   Update not possible

Run `mix hex.outdated APP` to see requirements for a specific dependency.

To view the diffs in each available update, visit:
https://hex.pm/l/1ZBue
```

And following the link https://hex.pm/l/1ZBue, you could see the diff in CHANGELOG (if a package happens to have it)
