### ISSUE TITLE
Warn of retired packages due to security issues in mix hex.outdated

### ISSUE THREAD

**Issue by tanguilp** [hexpm/hex#796]
Not sure if it's just me but I usually use `mix hex.outdated` rather often on my projects but not `mix hex.audit` (actually I've just discovered it).

Now, I think this would be a good idea to output that there's a security issue when running `mix hex.outdated` with one of the package (which is retired), possibly recursively (i.e. even when the retired lib is not directly in `mix.exs`, but is imported deeper in the library tree).

Also, such a warning message could be displayed in `mix deps.tree` (such as "The current installed version has been marked as retired because of security issues"), which does not show the current version but still, the more messages the better when dealing with security.

**Comment by ericmj** [comment]
The purpose of `mix hex.outdated` is to show if there are new versions and if you can update to them so I think showing this warning would be confusing. Is it the new version or the current version that is retired?

**Comment by tanguilp** [comment]
It would indeed go beyond the purpose of `mix hex.outdated` strictly speaking. But I suspect it could be useful if people do indeed use this command way more often than `mix hex.audit`.

The idea is to maximize display of warnings related to security - packages retired for other reasons would not be handled by `mix hex.outdated`. Such a warning could be displayed in orange, on the right of the line with a message like "WARNING: the currently used version is retired for security-related issue" and warn about deprecation of the current installed version.

This is just an idea. I've got the feeling that `mix hex.audit` is very rarely used, but I might be wrong.

**Comment by ericmj** [comment]
You get retired warnings when running `mix deps.get` or `mix deps.update` which I think are used more often `mix hex.outdated`.

`mix hex.audit` primary use case is inside a CI. It returns a non-zero exit code if any package you are using is retired which should fail the CI action.

**Comment by tanguilp** [comment]
Ah ok, didn't know it. Thanks for the answer, closing this issue.
