### ISSUE TITLE
Failed hostname check validation on hosts with wildcard certificates

### ISSUE THREAD

**Issue by imsoulfly** [hexpm/hex#797]
Hey everyone,

for our company we are using an internally hosted hex repo to manage private libraries in combination with using also the public libraries via hex.pm. Up until now we had no issues but we were observing issues as some people updated to a local dev environment using Erlang OTP 23.

What we saw from here on out were ssl handshake failures when running `mix deps.get` similar to the following log lines (prettifed)

```
Request failed (
  {:failed_connect, [
    {:to_address, {'hex.our-domain.io', 443}},
    {:inet, [:inet],
      {:tls_alert, {:handshake_failure, 'TLS client: In state certify at ssl_handshake.erl:1840 
      generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}
    }
  ]}
)
** (Mix) Package fetch failed and no cached copy available (https://hex.our-domain.io/tarballs/rest_api-0.3.5.tar)
```

So our investigations brought up the following that there have been or are issues around hosts / hostnames that are secured via wildcard certificates. (https://bugs.erlang.org/browse/ERL-1260)
The ticket mentions missing hostname validation and buy adding it to httpc ssl handling breaks the wildcard certificates with some reasoning by the developer that is being better being read in the ticket itself.

This lead me to looking into `mint` and specifically the PR where they fix the broken wildcard certificate checks against hostnames. (https://github.com/elixir-mint/mint/pull/261). With this fix `mint` itself works fine again also against our repo server.

So my thought was now to add a similar custom hostname check to the `hex` repo and did a **quick and dirty copy solution of the `mint` PR** not knowing all the internals of this repository. So you might want to give an advice to create a better fix and possibly hint me to how to tests this properly.

But here is my solution for this code location without tests for now: (https://github.com/hexpm/hex/blob/main/lib/hex/http/ssl.ex#L64)

```
def ssl_opts(url) do
    hostname = Hex.string_to_charlist(URI.parse(url).host)
    ciphers = filter_ciphers(@default_ciphers)

    if secure_ssl?() do
      verify_fun = {&VerifyHostname.verify_fun/3, check_hostname: hostname}
      partial_chain = &partial_chain(Certs.cacerts(), &1)

      [
        verify: :verify_peer,
        depth: 4,
        partial_chain: partial_chain,
        cacerts: get_ca_certs(),
        verify_fun: verify_fun,
        server_name_indication: hostname,
        secure_renegotiate: true,
        customize_hostname_check: [match_fun: &match_fun/2],
        reuse_sessions: true,
        versions: @default_versions,
        ciphers: ciphers
      ]
    else
      [
        verify: :verify_none,
        server_name_indication: hostname,
        secure_renegotiate: true,
        reuse_sessions: true,
        versions: @default_versions,
        ciphers: ciphers
      ]
    end
  end

  defp match_fun({:dns_id, reference}, {:dNSName, [?*, ?. | presented]}) do
    case domain_without_host(reference) do
      '' ->
        :default

      domain ->
        # TODO: replace with `:string.casefold/1` eventually
        :string.to_lower(domain) == :string.to_lower(presented)
    end
  end

  defp match_fun(_reference, _presented), do: :default

  defp domain_without_host([]), do: []
  defp domain_without_host([?. | domain]), do: domain
  defp domain_without_host([_ | more]), do: domain_without_host(more)
``` 

By adding the `:customize_hostname_check` it does a check of the wildcard certificates similar to the `mint` lib.

Please have a look! Also I hope you are interested in fixing this and maybe you can give further advice on how to proceed so maybe I can provide a PR.

And also... Have a nice day!

**Comment by ericmj** [comment]
Thanks for the issue and for looking into it. I believe you have found the correct fix from the mint PR. Please send a PR! 💜

**Comment by imsoulfly** [comment]
Hi @ericmj,

if I am on right track as you say then I'll try to provide a PR of course. Let's see if can provide something in the next days.
I keep you posted
