### ISSUE TITLE
Add `--fetch-public-key FINGERPRINT` to `mix hex.repo add`

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#801]
We've recently documented the `/public_key` endpoint [1], which means we can further automate the process of adding custom repositories. Instead of:

```
$ curl https://acme.corp/public_key > public_key.pem
$ mix hex.repo add acme https://acme.corp --public-key public_key.pem
```

we could simply do:

```
$ mix hex.repo add acme https://acme.corp --fetch-public-key
```

One possible concern is the current process requires fetching the key out of band which also serves as verification, removing it has security implications.

Thoughts?

[1] https://github.com/hexpm/specifications/pull/28

**Comment by ericmj** [comment]
Should we table this until we have a coherent solution for API and repo configuration (possibly `mix hex.server`) so we don't do any unnecessary work we may have to deprecate soon and instead focus on implementing `mix hex.server` (or whatever we end up with)?

**Comment by wojtekmach** [comment]
Good call, let's wait for `mix hex.server`.
