### ISSUE TITLE
(Mix) Could not install Hex because Mix could not verify authenticity of metadata file

### ISSUE THREAD

**Issue by Aman-Osman-Bose** [hexpm/hex#811]
**Environment**
**iex**

- Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
- Interactive Elixir (1.10.4) 

**Issue**
This happens not 100% but close to it.  Occasionally it was working after manual retry but now it's not working at all.  I have read this could be related to proxy but I am not sure as I am new to hex and mix.  I did read about HTTP proxy but wasn't sure.

12:09:24 Step 7/24 : RUN mix local.hex --force
12:09:24  ---> Running in 03b1326a8bfd
12:09:25 [91m** (Mix) Could not install Hex because Mix could not verify authenticity of metadata file at "https://repo.hex.pm/installs/hex-1.x.csv". This may happen because a proxy or some entity is interfering with the download or because you don't have a public key to verify the download.
12:09:25 
12:09:25 You may try again later or check if a new public key has been released in our public keys page: https://repo.hex.pm/installs/public_keys.html
12:09:25 [0mThe command '/bin/sh -c mix local.hex --force' returned a non-zero code: 1

I don't feel comfortable using unsafe_https so

**Comment by ericmj** [comment]
This is an Elixir issue since the `mix local.hex` task is provided by the standard library so please reopen the issue there. `:unsafe_https` is a Hex configuration so it won't do anything for this command unfortunately. Can you check if it works consistently when you don't use a proxy?
