### ISSUE TITLE
Authing to multiple orgs in a single `mix do` can fail?

### ISSUE THREAD

**Issue by novaugust** [hexpm/hex#824]
We auth with multiple orgs for pulling in private packages.
Our scripts were initiallly 
```sh
mix do \
  hex.auth ..., \
  hex.auth ...
```

However, this would fail to auth the second organization in our CI builds. After some twiddling, we found that making two `mix hex.auth ..` calls fixed the issue.
```sh
mix hex.auth ...
mix hex.auth ...
```

We were content to leave it at that and blame the CI environment, but a developer just had the exact same problem while developing on their local machine, so I thought it might be a bigger problem and that I should surface it. Not sure if it's a hex thing or a mix thing, but thought I'd start here.

Sorry I don't immediately have more to give you!

**Comment by ericmj** [comment]
> We auth with multiple orgs for pulling in private packages?

Is this for CI systems? For "normal" users that are authenticating using a username and password we will provision keys that give access to all organizations you are members of.

> However, this would fail to auth the second organization in our CI builds.

Do you get an error when running `mix hex.auth` or do the subsequent `mix deps.get` calls simply fail with auth errors?

If you call `cat ~/.hex/hex.config` after authenticating do you see all repos you have authenticated to under the `$repos` key?

Are you using hex.pm organizations or are you running your own servers?

**Comment by novaugust** [comment]
> Is this for CI systems? 

Both in CI and on a dev's machine.

> Do you get an error when running `mix hex.auth` or do the subsequent `mix deps.get` calls simply fail with auth errors?

the latter. there's no error from hex.auth, but `deps.get` fails as though we are not authed

> Are you using hex.pm organizations

hex.pm orgs, yup.

catting hex config gives the expected repos, but we don't currently have a machine that's failing with this bug :(

**Comment by ericmj** [comment]
I can not reproduce this issue. If this is still an issue please reopen and include the error message you are getting.
