### ISSUE TITLE
rebar3 Hex installation instructions don't work on Windows

### ISSUE THREAD

**Issue by lpil** [hexpm/hex#828]
Hello!

I'm following the instructions on this page: https://hex.pm/docs/rebar3_usage

After adding the plugin to my `~/.config/rebar3/rebar.config` file (`C:\Users\louis.pilfold\.config\rebar3\rebar3.config`) rebar3 does not install the Hex plugin, so I am unable to publish a package using it.

```
❯ rebar3 hex publish
===> Command hex not found
```

**Comment by ericmj** [comment]
Hi! Please raise this issue with the rebar3 team or create an issue on https://github.com/tsloughter/rebar3_hex.

**Comment by lpil** [comment]
Oops, it's a typo! My bad
