### ISSUE TITLE
mix hex.install VERSION fails

### ISSUE THREAD

**Issue by cw789** [hexpm/hex#838]
I think `Mix.Utils.read_path` was changed to at least need `:sha512` or `:unsafe_uri` as additional option...
I dare not to tackle this, as I'm unsure how backwards compatibility needs to be maintained with this.

```
** (CaseClauseError) no case clause matching: {:checksum, "fetching from URIs require a checksum to be given"}
    lib/mix/tasks/hex.install.ex:85: Mix.Tasks.Hex.Install.read_path!/2
    lib/mix/tasks/hex.install.ex:62: Mix.Tasks.Hex.Install.find_matching_versions_from_signed_csv!/3
    lib/mix/tasks/hex.install.ex:45: Mix.Tasks.Hex.Install.install/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

`mix hex.info`
```
Hex:    0.20.6
Elixir: 1.11.2
OTP:    23.1

Built with: Elixir 1.11.1 and OTP 21.3
```

**Comment by ericmj** [comment]
> I'm unsure how backwards compatibility needs to be maintained with this.

There are no backwards compatibility requirements for this task since it's internal and undocumented.
