### ISSUE TITLE
:ssl.cypher/1 is removed from OTP 24

### ISSUE THREAD

**Issue by DianaOlympos** [hexpm/hex#839]
On OTP 24, this function, deprecated since OTP 21, is removed.

https://github.com/erlang/otp/commit/708b01f8f32cdc579a38d5bcec4e7e98e75a2525

It is in particular used in https://github.com/hexpm/hex/blob/main/lib/hex/http/ssl.ex#L123

**Comment by wojtekmach** [comment]
This seems to fix it, but I'm not sure which protocol version we should use:

```diff
- available = Hex.Set.new(:ssl.cipher_suites(:openssl))
+ available = Hex.Set.new(:ssl.cipher_suites(:all, :"tlsv1.3", :openssl))
```

**Comment by ericmj** [comment]
I think that's the arguments we should use, according to the documentation it will include ciphers for older versions as well.

**Comment by IvanIvanoff** [comment]
[:ssl.cipher_suites/1](https://github.com/hexpm/hex/blob/2f5fcc43efbaa90e6fb9e1c20c7a70a339fd6db8/lib/hex/http/ssl.ex#L123) was also deprecated in OTP 21 and is removed in OTP 24. `:ssl.cipher_suites/2` should be used instead.

**Comment by ericmj** [comment]
Closing this in favor of https://github.com/hexpm/hex/pull/847.
