### ISSUE TITLE
Use :crypto.mac/4 instead of :crypto.hmac/3

### ISSUE THREAD

**Issue by IvanIvanoff** [hexpm/hex#844]
:crypto.hmac/{3,4} is deprecated and will be removed in Erlang/OTP 24.
:crypto.mac/4 should be instead, but it is available only since Erlang/OTP 22.1.

Both functions yield the same result:
```elixir
iex(6)> :crypto.mac(:hmac, :sha256, "key", "data") == :crypto.hmac(:sha256, "key", "data")
true
iex(7)> :crypto.mac(:hmac, :sha384, "key", "data") == :crypto.hmac(:sha384, "key", "data")
true
```

:crypto.hmac/3 is used in two different modules: [PBES2_HMAC_SHA2](https://github.com/hexpm/hex/blob/main/lib/hex/crypto/pbes2_hmac_sha2.ex) and [PKCS5](https://github.com/hexpm/hex/blob/main/lib/hex/crypto/pkcs5.ex), so it makes sense to define a new function `hmac/3` in the [Hex.Crypto module](https://github.com/hexpm/hex/blob/main/lib/hex/crypto.ex) and reuse it everywhere. 

An example implementation could look like this:
```elixir
defmodule Hex.Crypto do
  // ...
  # :crypto.mac/4 is introduced in Erlang/OTP 22.1 and :crypto.hmac/{3,4} are removed
  # in Erlang/OTP 24. The check is needed for backwards compatibility.
  Code.ensure_loaded?(:crypto) || IO.warn(":crypto module failed to load")

  case function_exported?(:crypto, :mac, 4) do
    true ->
      def hmac(type, key, data), do: :crypto.mac(:hmac, type, key, data)

    false ->
      def hmac(type, key, data), do: :crypto.hmac(type, key, data)
  end	
end
```

The calls to `:crypto.hmac/3` will be replaced by calls to `Hex.Crypto.hmac/3`:
```diff
  def pbkdf2(password, salt, iterations, derived_key_length, hash)
      when is_binary(password) and is_binary(salt) and is_integer(iterations) and iterations >= 1 and
             is_integer(derived_key_length) and derived_key_length >= 0 do
-    hash_length = byte_size(:crypto.hmac(hash, <<>>, <<>>))
+    hash_length = byte_size(Hex.Crypto.hmac(hash, <<>>, <<>>))

    if derived_key_length > 0xFFFFFFFF * hash_length do
```

**Comment by ericmj** [comment]
Thank you. Could you send a PR for this change?
