### ISSUE TITLE
Questions about new way to create custom hex repos

### ISSUE THREAD

**Issue by collegeimprovements** [hexpm/hex#846]
Thanks a lot for your awesome work hex-team.

We have 2 questions about the future of  custom hex_repos:

1. Will [the new way](https://github.com/hexpm/hex/blob/90aa44fa8a1e59f2ae65f490edb984e4d6c853d1/lib/mix/tasks/hex.registry.ex ) of creating custom hex_repos support hex_docs ?

2. Will it allow some kind of `store` like feature to save those repos in `S3` and `local` ? Or it will be just `local` ?

**Comment by wojtekmach** [comment]
1. No plans for docs hosting
2. No plans for storage abstraction, we just support writing to local fs

Check out https://github.com/kobil-systems/urepo for 1. in particular.
