### ISSUE TITLE
Replacing default repo

### ISSUE THREAD

**Issue by LostKobrakai** [hexpm/hex#852]
If I understood `mix help hex.repo` correctly than one cannot select a "default" repo by name, but does need to replace the settings of `hexpm`.

Now the latter doesn't seem to work with `--fetch-public-key`:
```
❯❯❯❯ mix hex.repo set hexpm --fetch-public-key=SHA256:y9/0H839AcrPvPwVhwytMGNetWNNuU5/kWFK/2ztnGM
❯❯❯❯ mix hex.repo show hexpm                                                            ~/Work/madeit/Projekte/pour master
URL                                 Public key                                          Auth key
http://localhost:4000/repo/default  SHA256:O1LOYhHFW4kcrblKAxROaDEzLD8bn1seWbe5tq8TRsk  <redacted>
```

**Comment by wojtekmach** [comment]
`--fetch-public-key` is an option to `mix hex.repo add` and not other tasks, could you try running that?

**Comment by LostKobrakai** [comment]
That one works as expected, but hexpm is already existing and cannot be deleted it seems.

Also it's documented for `set` as well:

```
## Set config for repo

    mix hex.repo set NAME --url URL
    mix hex.repo set NAME --public-key PATH
    mix hex.repo set NAME --fetch-public-key FINGERPRINT
    mix hex.repo set NAME --auth-key KEY
```

**Comment by wojtekmach** [comment]
The docs are wrong, good catch.

I'm not sure if replacing hexpm repo with your own was is a good idea, I think there are assumptions in the codebase that hexpm is, well, hexpm. I think you may not be able to overwrite the public key for that repo, for example, as it ships as part of Hex. If your repo is mirroring hex.pm, set `mirror_url` configuration instead. If it's a completely different repo, give it another name. I haven't really tried replacing hexpm repo with others so I might be totally wrong here so I'll let others chime in.

**Comment by LostKobrakai** [comment]
Ok, I'll go with the mirroring + custom repo then.

**Comment by ericmj** [comment]
You can replace the `hexpm` repo but it has a few caveats. There's a few reasons why you may want a custom repo and a few different ways to add repos to the hex client, but it is hard to give good recommendations without knowing your use case.

Do you need to mirror all of hexpm, or only a subset of packages, and why do you need to mirror, or do you not need to mirror at all? Do you need to replace packages in hexpm with your own? Does your repo need packages in addition to those in hexpm?

Does the repo config need to be global or do you only need it for some projects, for example a few applications for your organization?

**Comment by LostKobrakai** [comment]
The project is meant to become something akin to nexus repository manager for hex. So custom repo, but also mirror/proxy for hexpm. I initially tried to make that work with one repository doing both, but maybe that's not even the clever way in the first place. Separating both will make e.g. forking to the custom repo (e.g. for hotfixes) much more clear.

**Comment by ericmj** [comment]
Then I would recommend using `mirror_url` and adding a separate repo with `mix hex.repo add`. I would also suggest to set the `mirror_url` config in the project config for those projects that require the mirror and not setting it globally so that developers will not use the mirror when it's not necessary.
