### ISSUE TITLE
hex.sponsor fails, unable to find metadata

### ISSUE THREAD

**Issue by starbelly** [hexpm/hex#854]
```
* (CaseClauseError) no case clause matching: {:error, :enoent}
    (hex 0.21.1) lib/mix/tasks/hex.sponsor.ex:54: anonymous fn/2 in Mix.Tasks.Hex.Sponsor.sponsor_links/2
    (elixir 1.11.2) lib/enum.ex:3421: Enum.flat_map_list/2
    (elixir 1.11.2) lib/enum.ex:3422: Enum.flat_map_list/2
    (hex 0.21.1) lib/mix/tasks/hex.sponsor.ex:40: Mix.Tasks.Hex.Sponsor.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

I was about to open up a simple PR to handle this case, but I figured this should not be happening at all, and that there should be no dep that has a missing `hex_metadata.config` file. Indeed, the file is not missing, I assume the path is wrong.

This only ensues if I install hex via `mix local.hex`, if I build the ez archive myself from `main` and install that all is well 🤔

**Comment by wojtekmach** [comment]
I couldn't reproduce this locally, a list of steps how to do that or a fix would be appreciated.

**Comment by starbelly** [comment]
@wojtekmach Ahh, I found the problem. My lock file contained deps that aren't part of my project anymore. Re-generating my lock file solved the issue. Perhaps a PR to strip non-existent deps out of the list in `Hex.Sponsor` would make sense?

**Comment by starbelly** [comment]
#855 closes this issue.
