### ISSUE TITLE
Problem accessing s3.hex.pm via mix installing hex

### ISSUE THREAD

**Issue by davebryson** [hexpm/hex#86]
I've also filed this issue with Elixir.

I'm unable to get mix to work behind a proxy:
```
$ mix deps.get
Could not find hex, which is needed to build dependency :cowboy
Shall I install hex? [Yn] y
** (Mix) Could not access url
https://s3.amazonaws.com/s3.hex.pm/installs/list.csv, error:
{:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet,
[:inet], :econnrefused}]}
```
I have the http_proxy(s) variables set in my environment. As a test:
```
curl https://s3.amazonaws.com/s3.hex.pm/installs/list.csv
```
works just fine. 

Is there a non-ssl version of s3.hex.pm? Any idea what may be causing this?

**Comment by ericmj** [comment]
You can install Hex manually but you will hit the same issue as soon as Hex fetches the repository. I'm going to track my progress on this on the elixir issue https://github.com/elixir-lang/elixir/issues/3075.

The only workaround until we've fixed this is to unset the HTTP proxy env vars.
