### ISSUE TITLE
command line option --repo not recognised

### ISSUE THREAD

**Issue by geib** [hexpm/hex#867]
I am unable to specify the repo to use for "package" command.

$ mix hex.package fetch deciaml 2.0.0 --repo=acme
** (Mix) Could not invoke task "hex.package": 1 error found!
--repo : Unknown option

Mark.

**Comment by wojtekmach** [comment]
what's your Hex version? You can check it with `mix hex.info`. I think this option was added in a somewhat recent release, so maybe sure you're up-to-date: `mix local.hex --force`.

**Comment by geib** [comment]
That was it.

$ mix hex.info
Hex:    0.20.5
Elixir: 1.10.3
OTP:    21.3

Thanks for the quick reply.
Mark.
