### ISSUE TITLE
mix hex.registry build fails with more than one new tarball

### ISSUE THREAD

**Issue by geib** [hexpm/hex#869]
If I copy one new tarball into the public/tarballs directory the mix hex.registry build works fine.

If I copy two or more new tarballs into the public/tarballs directory then:
```
$ mix hex.registry build public --name=acme --private-key=private_key.pem
* updating public/packages/cowboy
* updating public/packages/decimal
* updating public/packages/logit
** (MatchError) no match of right hand side value: %{"app" => "mpeg_utils", "optional" => false, "requirement" => "1.2.5"}
    lib/mix/tasks/hex.registry.ex:148: anonymous fn/3 in Mix.Tasks.Hex.Registry.build_release/2
    (stdlib 3.8) maps.erl:257: :maps.fold_1/3
    lib/mix/tasks/hex.registry.ex:142: Mix.Tasks.Hex.Registry.build_release/2
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/hex.registry.ex:109: anonymous fn/4 in Mix.Tasks.Hex.Registry.build/3
    (elixir 1.10.3) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
    (stdlib 3.8) maps.erl:257: :maps.fold_1/3
    (elixir 1.10.3) lib/enum.ex:2127: Enum.map/2
```

Mark.

**Comment by wojtekmach** [comment]
I cannot reproduce it, I tried the following:

```
~/acme% rm -rf public
~/acme% mix hex.registry build public --name=acme --private-key=private_key.pem
* creating public/public_key
* creating public/tarballs
* creating public/names
* creating public/versions
~/acme% (cd public/tarballs && mix hex.package fetch cowboy && mix hex.package fetch decimal)
cowboy v2.8.0 downloaded to /Users/wojtek/acme/public/tarballs/cowboy-2.8.0.tar
decimal v2.0.0 downloaded to /Users/wojtek/acme/public/tarballs/decimal-2.0.0.tar
~/acme% mix hex.registry build public --name=acme --private-key=private_key.pem
* creating public/packages/cowboy
* creating public/packages/decimal
* updating public/names
* updating public/versions
```

**Comment by geib** [comment]
Could I be on the wrong branch.?? I am using the branch “main”. Simple things seems to work for you but not me.

 I am not able to do a fetch without the version.

$ mix hex.package fetch cowboy
** (Mix)   Invalid arguments, expected one of:

  mix hex.package fetch PACKAGE VERSION [--unpack]
  mix hex.package diff APP VERSION
  mix hex.package diff PACKAGE VERSION1 VERSION2
  mix hex.package diff PACKAGE VERSION1..VERSION2


But this works:

$ mix hex.package fetch cowboy 2.8.0
cowboy v2.8.0 downloaded to /Users/name/work/os_git/hex/cowboy-2.8.0.tar

**Comment by wojtekmach** [comment]
What's the output of `mix hex.info`? Make sure it says `Hex:    0.21.2-dev`. You can install development version by doing `cd /path/to/hex && mix install`.

**Comment by wojtekmach** [comment]
Well, you shouldn't need to be on development version for `mix hex.package fetch` but you should for the recent fixes :)

**Comment by wojtekmach** [comment]
Ah, never mind, `mix hex.package fetch NAME` (no version) hasn't been released yet, it's only on the main branch so far, so please disregard my last comment.

**Comment by geib** [comment]
Sorry, no I was not using dev version.

$ mix hex.info
Hex:    0.21.1
Elixir: 1.10.3
OTP:    21.3

Built with: Elixir 1.10.4 and OTP 21.3

I did the mix install and now I am on dev.

My apologies, I am not an elixir developer, just erlang.

I will start from zero and let you know how things work now.

Mark.

**Comment by wojtekmach** [comment]
No worries, thank you for trying this out and reporting feedback, this is really appreciated!

**Comment by geib** [comment]
The build now works with many tarballs. Thanks. I am showing a session where I removed all tarballs, copied in a list of tarballs, built the registery, then tried a fetch, but I am getting an error related to not being authorized, which I never got before so I assume this is new…

geibs-MacBook-Pro:hex geib$ rm public/tarballs/*
geibs-MacBook-Pro:hex geib$ cp /tmp/tarballs/* public/tarballs/.
geibs-MacBook-Pro:hex geib$ ls public/tarballs/
decimal-2.0.0.tar		logit-1.0.8.tar			mpeg_utils-2.0.2.tar		packet_generator-1.0.0.tar	rebar3_cse_cuttlefish-1.2.0.tar	rebar3_cse_utils-0.8.0.tar	rebar3_hex-6.10.3.tar		si_grpc-0.1.0.tar
geibs-MacBook-Pro:hex geib$ mix hex.registry build public --name=acme --private-key=private_key.pem
* updating public/packages/decimal
* updating public/packages/logit
* updating public/packages/mpeg_utils
* updating public/packages/packet_generator
* updating public/packages/rebar3_cse_cuttlefish
* updating public/packages/rebar3_cse_utils
* updating public/packages/rebar3_hex
* updating public/packages/si_grpc
* updating public/names
* updating public/versions
geibs-MacBook-Pro:hex geib$ mix hex.package fetch decimal --repo=acme
Failed to retrieve package information
account not authorized for this action
** (MatchError) no match of right hand side value: nil
    (hex 0.21.2-dev) lib/mix/tasks/hex.package.ex:342: Mix.Tasks.Hex.Package.find_package_latest_version/2
    (hex 0.21.2-dev) lib/mix/tasks/hex.package.ex:137: Mix.Tasks.Hex.Package.fetch/5
    (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.3) lib/mix/cli.ex:82: Mix.CLI.run_task/2
    (elixir 1.10.3) lib/code.ex:926: Code.require_file/2


Mark.

**Comment by wojtekmach** [comment]
Great, we'll have a release with these registry fixes soon.
