### ISSUE TITLE
Question on next release timeline

### ISSUE THREAD

**Issue by ninjanicely** [hexpm/hex#872]
Hi there! 

I greatly appreciate the work that's been done for self-hosting repos, and I want to take advantage of the commits on the main branch. Is there a timeline for the next release? I saw in [issue 869](https://github.com/hexpm/hex/issues/869#issuecomment-786935545) that a release will come soon. 

Right now I'm manually installing from the Main branch, so it's not a show stopper. An official release would be awesome though!

Thanks again.

**Comment by ericmj** [comment]
We currently don't have any release timelines for Hex. The release is done when there are enough fixes and features implemented which is of course weighted by their importance. Doing a release is a bit of work and takes some time so we don't want too many releases to take time from actual development.
