### ISSUE TITLE
mix hex.outdated returning stale results

### ISSUE THREAD

**Issue by dmarkow** [hexpm/hex#876]
I set up a super basic elixir project using `mix new sample`. The only dependency I added was `{:ecto, "~> 3.6.0"}`.

On my local machine, running macOS, Elixir 1.11.4, and Erlang 23.3.1, `mix hex.outdated` gives me:

```
Dependency  Current  Latest  Status
ecto        3.6.0    3.6.1   Update possible
```

Great! Now I run this same thing on my production server running Ubuntu 20.04, Elixir 1.11.4, and Erlang 23.2, `mix hex.outdated` shows:

```
Dependency  Current  Latest  Status
ecto        3.6.0    3.6.0   Up-to-date
```

I've tried completely clearing my `~/.hex` and `~/.cache` folders and it still won't find the 3.6.1 version.

If I specify a different mirror, it works fine:

```
> HEX_MIRROR=https://cdn.jsdelivr.net/hex mix hex.outdated
Dependency  Current  Latest  Status
ecto        3.6.0    3.6.1   Update possible
```

But the default `https://repo.hex.pm` source isn't working. I confirmed that `mix hex.config` has identical settings on both machines. It does seem to be only happening with `ecto` in my actual production project. Both machines show several available updates for other packages, but only the development machine shows the available `ecto` update.

Is this a bug in hex, or is there some other cache/setting I should be checking?

**Comment by ericmj** [comment]
Do you have a way for us to reproduce the issue. For example a dockerfile?

**Comment by dmarkow** [comment]
I went to create a reproduction this morning, and now it's suddenly showing 3.6.1 after 3 days of not working, with no changes on my end...

It still seems to me there was some issue with hex caching an old HTTP response or something along those lines, since the mirrors worked fine but `repo.hex.pm` kept showing an old version.

One thing I forgot to mention -- even when it wasn't showing 3.6.1 in `hex.outdated`, it *was* showing it in `hex.info` which was confusing:

```
> mix hex.info ecto
A toolkit for data mapping and language integrated query for Elixir

Config: {:ecto, "~> 3.6"}
Locked version: 3.6.0
Releases: 3.6.1, 3.6.0, 3.5.8, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3, ...

> mix hex.outdated
Dependency  Current  Latest  Status
ecto        3.6.0    3.6.0   Up-to-date
```

But at this point it seems like an isolated issue that is possibly related to my server environment, so this can probably be closed for now.

**Comment by ericmj** [comment]
If `hex.info` and `hex.outdated` returns different results it would suggest an issue with the registry cache on some level.

Please let us know if something similar happens again.
