### ISSUE TITLE
Allow the user to turn off short URL generation

### ISSUE THREAD

**Issue by maxnordlund** [hexpm/hex#880]
Hi, first let me say thanks for such an amazing tool. It really makes it easy to get things done. ❤️ 

I noticed a link when running `mix hex.outdated` today and was redirected to a diff page, which is very cool and useful. But I wondered how it could fit so much info in just 5 letters. Turns out it doesn't. It shortens the URL using hex.pm. Elegant and convenient. But I would like to be able to turn this off.

Why you might ask? Because I rather have a long URL, then leak what packages, and their versions, I happen to have in one of my projects. I might have internal dependencies, stuff not on hex.pm, or I might be running something awfully old. Either way I'm sure someone clever will be able to use this to their advantage. It probably won't be a problem, but the less data the better, right? I was thinking about a [npm/pip attack](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610) I read recently.

The shortening is done here:

https://github.com/hexpm/hex/blob/57a7c94f7aba7769b48dd5d0e305a8b95a0fcbfd/lib/mix/tasks/hex.outdated.ex#L298-L305

Which calls the API here:

https://github.com/hexpm/hex/blob/57a7c94f7aba7769b48dd5d0e305a8b95a0fcbfd/lib/hex/api/short_url.ex#L6-L11

My suggestion is a new config value and check that in `Hex.API.ShortURL.create/1` . Then return `:error` (or something better) to make the CLI output the long URL instead.

What do you think?

**Comment by ericmj** [comment]
Thanks for opening the issue, I agree that we should have a way to disable this.

How about a config `:no_short_urls` and environment variable `HEX_NO_SHORT_URLS`?

**Comment by wojtekmach** [comment]
> How about a config :no_short_urls and environment variable HEX_NO_SHORT_URLS?

+1 from me.

**Comment by maxnordlund** [comment]
That sounds like a great idea

**Comment by supersimple** [comment]
Thanks for the feedback @maxnordlund !!
PR opened - supports the new config `no_short_urls` as well as ENV VAR called HEX_NO_SHORT_URLS

IIRC our motivation for the short URL was a) the column width of the CLI is low, and the links are long. and b) the URLs are a bit ugly looking. There is no identifiable information in the URL (if someone were to guess 5 characters they wouldn't be able to trace it back to a project for instance.) But I am curious what other attack vectors this potentially opens up. 🤔 

Anyway - thanks again 🌮 🌯 🍺 🎉
