### ISSUE TITLE
Add HEX_TRUSTED_MIRROR_URL configuration

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#882]
The new `HEX_TRUSTED_MIRROR_URL` should work like the current `HEX_MIRROR_URL`.

`HEX_MIRROR_URL` should no longer send the `authorization` header.

With these changes we can make a distinction between trusted mirrors that can be used to fetch private packages and untrusted mirrors that you shouldn't share access keys with.

**Comment by supersimple** [comment]
HEX_MIRROR_URL seems to have been shortened to HEX_MIRROR at some point. SHould we make this HEX_TRUSTED_MIRROR instead?

**Comment by ericmj** [comment]
> HEX_MIRROR_URL seems to have been shortened to HEX_MIRROR at some point. SHould we make this HEX_TRUSTED_MIRROR instead?

👍

**Comment by Benjamin-Philip** [comment]
Would `HEX_TRUSTED_MIRROR` take precedence over `HEX_MIRROR`?

**Comment by ericmj** [comment]
I think we should warn if both are set and let `HEX_MIRROR` have precedence since it was first.
