### ISSUE TITLE
If HEX_API_KEY is set, but incorrect, mix hex.publish exits without an exit code

### ISSUE THREAD

**Issue by iautom8things** [hexpm/hex#885]
<img width="669" alt="Screen Shot 2021-05-20 at 9 23 34 PM" src="https://user-images.githubusercontent.com/522040/119072794-bd3a5a00-b9b1-11eb-8efa-c644d9226a32.png">

I stumbled upon this by accidentally forgetting to set a secret for a CD action that silently failed.  I would have expected that the `hex.publish` task would have returned a non-zero code to indicate a failure.

Thank you!

**Comment by wojtekmach** [comment]
Good catch, thanks!
