### ISSUE TITLE
Improve hex.docs error message when ex_docs is missing

### ISSUE THREAD

**Issue by williamgueiros** [hexpm/hex#89]
If i don't have the "ex_doc" dependence, on my project 
and run the command mix hex.docs

return to me, the error:

** (Mix) The task docs could not be found

but that message is very difficult , to understand that the problem.

tks

**Comment by williamgueiros** [comment]
other point..

if I put 
  defp deps do
    [{:earmark, "~> 0.1", only: :docs},
   {:ex_doc, "~> 0.7", only: :docs}]
  end

instead of: 

  defp deps do
    [{:earmark, "~> 0.1", only: :dev},
   {:ex_doc, "~> 0.7", only: :dev}]
  end

received the same error, i saw this parameter on ecto source.

**Comment by ericmj** [comment]
If you have `only: :docs` you need to run the task in the docs environment with `MIX_ENV=docs mix ...`. Unfortunately we wont be able to warn about every possible invocation that will cause the task to fail.

**Comment by williamgueiros** [comment]
I am wanting try to solve this problem, this weekend, if not working in the same.
are you working on that ??

**Comment by ericmj** [comment]
Go ahead, I am not working on it.

**Comment by ericmj** [comment]
Ping?

**Comment by williamgueiros** [comment]
i tried, but could not solve

**Comment by ericmj** [comment]
Okay, thanks for looking into it.
