### ISSUE TITLE
Retiring package failed > account not authorized for this action

### ISSUE THREAD

**Issue by pacoguzman** [hexpm/hex#892]
Hi there,

I'm getting the following error when trying to retire a private package from our organization.

It was published from the same user that wants to retiere it and that user is declared as admin

Could you help me with this?

**Comment by ericmj** [comment]
What is the user, package, and organization you are attempting this with?

If this private information please email support@hex.pm.

**Comment by pacoguzman** [comment]
We missed the organization flag. All done now
