### ISSUE TITLE
Allow organizations to own and manage public packages

### ISSUE THREAD

**Issue by gamache** [hexpm/hex#898]
I am a developer on a medium-sized team that maintains a number of public and private Hex packages. Managing private packages is no problem; any member of the Hex organization can do it. But if someone on the team wants to manage one of the public packages, they must first be added as an owner.

We would like to be able to assign ownership/management rights of public packages to our Hex organization, so that each member of the org has the same rights as they would for a private package. This would reduce the user management burden when growing our team and reduce friction for our new team members.

Thanks for considering this feature!

**Comment by wojtekmach** [comment]
This is already possible! See for example packages owned by [dashbit](https://hex.pm/orgs/dashbit)

If you already have a package, you can transfer the ownership to the org using this command: https://hexdocs.pm/hex/Mix.Tasks.Hex.Owner.html#module-transfer-ownership.

Remember, don't declare your packages as `organisation: <org>`, that would make them private. 

I'm gonna close this, however if you run into any issues, let us know!

**Comment by soriyath** [comment]
i think it could be useful to have organization owned packages that can be public.
i fixed `redbird` and pushed the changes on my repo.
since there is a namespace collision, i can't transfer the `redbird` package to my organization (it's not maintained by someone else, AFAIK).
on NPMJS i have a few packages that are open source and namespaced with my organization.

**Comment by soriyath** [comment]
can you remove this package then: https://hex.pm/packages/leading_works/redbird ?
i'll try to find a new name to avoid the collision.

**Comment by ericmj** [comment]
If you want to take over an unmaintained package see https://hex.pm/policies/dispute#if-you-wish-to-acquire-an-existing-user-and-organization-name.

https://hex.pm/packages/leading_works/redbird is a private package so you can remove it yourself.

**Comment by soriyath** [comment]
I couldn't find how to delete a private package in the documentation. `mix hex.publish -- revert 0.8.1` failed when I tried. 
Can you point me to the right documentation ?
