### ISSUE TITLE
Typo in a return tuple

### ISSUE THREAD

**Issue by brawnski** [hexpm/hex#903]
Hi. 

I was troubleshooting a problem and looking at the source code when I found `{:valud, state}` in one of your return types.
https://github.com/hexpm/hex/blob/ba819ef4e0b29cb22ad029aa96301ce4b60b86af/lib/hex/http/verify_hostname.ex#L62
I believe this should be `{:valid, state}`

I've jumped down another rabbit hole, but I thought I would bring it to everyone's attention.

**Comment by wojtekmach** [comment]
Great catch, thank you. feel free to submit a PR, otherwise we'd do the honours :)
