### ISSUE TITLE
hex.package calls on a list of packages only retrieves first

### ISSUE THREAD

**Issue by fnchooft** [hexpm/hex#906]
Hi, i am following along https://hex.pm/docs/self_hosting.

In wanted to script the generation of the self-hosted content and tried something simple as this:

``` 
defmodule HexLocalRepo.Mixfile do
  use Mix.Project

def project do
  [
    aliases: [
      "download.packages": [
        "hex.package fetch bear 0.9.0",
        "hex.package fetch cf 0.3.1",
        "hex.package fetch zipper 1.0.1"
      ] 
    ]
  ]
end

end
```

However after calling "mix download.packages" - mix only downloads the first package.
Is there anything simple that I am missing?

Kind regards,

Fabian

mix hex.info:
```
Hex:    0.21.2
Elixir: 1.13.0-dev
OTP:    24.0.6

Built with: Elixir 1.11.4 and OTP 21.3
```

**Comment by ericmj** [comment]
Mix tasks will only be run once unless called with `Mix.Task.rerun` or reenabled with `Mix.Task.reenable`.
