### ISSUE TITLE
Unexpected error message for version.

### ISSUE THREAD

**Issue by hey-jude** [hexpm/hex#91]
"Hex was built against against Elixir v1.1.0-dev and you are running v1.0.4, please run `mix local.hex` to update to a matching version"

```
$ mix deps.get
Could not find hex, which is needed to build dependency :timex
Shall I install hex? [Yn]
2015-04-13 14:58:54 URL:https://s3.amazonaws.com/s3.hex.pm/installs/1.0.0/hex.ez [259426/259426] -> "/Users/scarlett/.mix/archives/hex.ez" [1]
* creating /Users/scarlett/.mix/archives/hex.ez
Hex was built against against Elixir v1.1.0-dev and you are running v1.0.4, please run `mix local.hex` to update to a matching version
Running dependency resolution
Dependency resolution completed successfully
All dependencies up to date
```

**Comment by seantan** [comment]
There was a version update earlier which this warning has slipped. It's fixed within the hour.

Run `mix local.hex` to update your hex again for the fix.

**Comment by hey-jude** [comment]
Thx for fast updating!

**Comment by seantan** [comment]
Yup, thanks to @ericmj for the fast fix!

**Comment by BraveKenny** [comment]
I have the same problem now:

```
$ mix deps.get
Hex was built against against Elixir 1.0.5 and you are running 1.1.0-dev, please run `mix local.hex` to update to a matching version
Running dependency resolution
All dependencies up to date
$ mix local.hex
Found existing archive(s): hex.ez.
Are you sure you want to replace them? [Yn] 
* creating /home/kenny/.mix/archives/hex.ez
$ mix deps.get
Hex was built against against Elixir 1.0.5 and you are running 1.1.0-dev, please run `mix local.hex` to update to a matching version
Running dependency resolution
All dependencies up to date
```

**Comment by josevalim** [comment]
@BraveKenny you are using a release Elixir version. Please update to 1.1.0 proper, otherwise I don't believe you will find a matching Hex version for a development release.

**Comment by BraveKenny** [comment]
Yep, I had issues installing a proper version of Elixir on Ubuntu 15.10. Uninstalling all of erlang and reinstalling it using [this method](http://international.github.io/20-20-elixir_in_ubuntu_15.10/) did the trick.

**Comment by josevalim** [comment]
Glad to hear!

On Wednesday, February 3, 2016, BraveKenny <notifications@github.com> wrote:

> Yep, I had issues installing a proper version of Elixir on Ubuntu 15.10.
> Uninstalling all of erlang and reinstalling it using this method
> <http://international.github.io/20-20-elixir_in_ubuntu_15.10/> did the
> trick.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex/issues/91#issuecomment-179148015>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
The version match is still incorrect.

**Comment by ericmj** [comment]
Actually should be a new issue since this one was resurrected.
