### ISSUE TITLE
Add version requirement info for `hex.outdated`

### ISSUE THREAD

**Issue by seantan** [hexpm/hex#92]
Thanks for adding `hex.outdated`.

May I suggest adding version requirement info for top level outdated packages when latest version does not meet constrain defined in mix.exs.

For example, having the following in `mix.exs` deps
```
{:phoenix_ecto, "~> 0.2.0"}
```
will output
```
Outdated packages:
 * phoenix_ecto (0.3.1 > 0.2.1) mix.exs specifies "~> 0.2.0"
```

This is similar to what `bundle outdated` will output in ruby.

If we're agreeable on this feature, may I submit a pull request for this?

**Comment by josevalim** [comment]
I think this is a great addition. It may be a very complex to add though because the requirement does not only come mix.exs but from the whole dependency tree and sometimes it requires the conflict resolution.

Unless we limit our match only to the requirements in the mix.exs file. Then we are fine.

**Comment by josevalim** [comment]
I also wonder if we could make the output a b it clearer. `mix.exs specifies "~> 0.2.0"` is not very good because it tells me just what is wrong instead of telling me what to do.

**Comment by seantan** [comment]
Probably due to the complexity involved in calculating the actual dependency tree, ruby's `bundle outdated` displays the version requirement only for gems defined in Gemfile.

With just checking the top level packages in mix.exs, it informs the developer that he can update the outdated package by updating the version constrain in `mix.exs` that he has direct control.  

If we do similarly, it will be a simple code addition.

**Comment by josevalim** [comment]
:+1: but let's wait for @ericmj's blessing.

**Comment by seantan** [comment]
Will do, thank you :)

**Comment by ericmj** [comment]
I think if we do it and do not include all requirements it will be even more confusing than it is today. We can list all requirements but like @josevalim says it would require a special pass in the resolver.

**Comment by jcspencer** [comment]
:+1: I agree with José that this is a great addition, but I also agree with Eric that we should be searching the whole dependency tree, instead of just the `mix.exs` file.

Thanks @seantan

**Comment by josevalim** [comment]
I don't think we should search the whole tree because Mix already does a very good job of formatting the results in case something goes wrong and we would end-up duplicating all of it here. For example, imagine that the new version introduces a new dependency that triggers and override conflict. How would we format that in mix hex.outdated?

If the answer is to not do the full resolution process, then we will be always missing something, so why not just be straight-forward?

**Comment by ericmj** [comment]
Closing because it's not worth the effort to implement a special pass through the resolver and the mix apis that end up calling the resolver.

**Comment by seantan** [comment]
Thanks everyone for looking into this, and I agree it is not worth the effort to do full resolution. 

Just for the record, I would like to state the use case of having this feature without full dependency resolution.

As a developer who prefers to keep the packages that I use up-to-date as and when possible, it is nice having the additional notification about version being held back by what's specified in `mix.exs`. The version requirement in my project mix.exs is something I can change to keep up.

Though the picture won't be complete without full resolution, the missing pieces are about dependency constraints being imposed by the packages used. Since majority of the time I have no direct interest in authoring the packages and their dependencies, these aren't information that I can act upon. It is not a necessity to know them.

Therefore, just having notification about package version being held back by what's specified in `mix.exs` is good enough for my use case.
