### ISSUE TITLE
Do not allow to publish a package if it has uncommitted changes

### ISSUE THREAD

**Issue by ayrat555** [hexpm/hex#921]
Some package managers (rust's cargo, for example) fail to publish a library if the repo has uncommited changes.

I think it's a useful feature so people wouldn’t accidentally publish  unwanted changes

**Comment by ericmj** [comment]
To implement this Hex would need to be aware of and call different source control binaries. We do not do this currently and are not planning to due to the additional complexity of supporting multiple source controls.

Thanks for the suggestion.

**Comment by ayrat555** [comment]
it can be done only for git if it's used for version control
