### ISSUE TITLE
mix hex.package fetch: Add support for .netrc files

### ISSUE THREAD

**Issue by frerich** [hexpm/hex#924]
There are currently two ways to fetch packages from repositories which use HTTP Basic Auth authentication:

1. Encode the login credentials right in the URL, e.g. `mix hex.repo add myrepo https://user:pass@host`
2. Manually compute the Base64 encoding of `user:pass` and then use that for defining an appropriate authentication key, e.g. `mix hex.repo add myrepo https://host --auth-key "Basic $BASE64_ENCODED_DATA"`.

In both cases, you end up with potentially sensitive information ending up in the Hex configuration file.

Many computer systems (most notably Unix-derived systems, like macOS or Linux) support a file called `.netrc` in the user's home directory for storing login credentials. This file typically has very restrictive file permissions (e.g. not group-readable) and is used by different utilities. For instance, [cURL supports netrc](https://everything.curl.dev/usingcurl/netrc) and [so does wget](https://man7.org/linux/man-pages/man1/wget.1.html).

It would be nice if Hex would also consider the `.netrc` files, if present.

**Comment by ericmj** [comment]
This is a great idea. Appreciate you offering to submit PR, let us know if you need any help or guidance on the implementation.

**Comment by frerich** [comment]
@ericmj Awesome, thanks for the thumbs up!

I browsed the source code a bit and noticed that there are at least two modules which concern themselves with submitting requests to a Hex repository:

* The `Hex.API` module -- my impression is that this module (and its submodules) is responsible for interacting with the HTTP API endpoint which is used for all administrative tasks and to browse packages. The [Hex.API.auth/1](https://github.com/hexpm/hex/blob/main/lib/hex/api.ex#L56) function is used for creating HTTP Authorization headers. In fact, it already has a notion of building a Basic Auth header given some user name and password!
* The `Hex.Repo` module. I believe this is for accessing the read-only endpoint of the repository which provides access to the registry files and package tarballs. The [Hex.Repo.auth_headers/1](https://github.com/hexpm/hex/blob/main/lib/hex/repo.ex#L216) function is used to compute HTTP Authorization headers. This one, unlike its cousin in `Hex.API`, has no idea about usernames or passwords.

Both of those modules are defined in terms of `Hex.HTTP` and _none_ of the three has any notion of looking up credentials in a `.netrc` file.

I believe a simple approach which would address all use cases might be to augment `Hex.HTTP` such that when performing requests, it checks the headers for an optional `authorization` key. If there is none, it checks a `.netrc` file to see if the URL to which the request is sent has login credentials defined. If so, an `authorization` header is constructed on the fly.

I.e. the `.netrc` logic would act as a _fallback_ to all existing authorization schemes, and it would be effective for both `Hex.API` as well as `Hex.Repo` calls.

Two further questions came up:

* Should the usage of credentials stored in `.netrc` be optional?
* In case `.netrc` is optional -- is it opt-in (i.e. it's not used by default) or opt-out? I'd personally prefer the latter.
* In case `.netrc` is optional -- how could this be configured? An environment variable? A new configuration key in `hex.config`? Something else?

I'd love to hear what you think. :-)

**Comment by ericmj** [comment]
> I believe a simple approach which would address all use cases might be to augment Hex.HTTP such that when performing requests, it checks the headers for an optional authorization key. If there is none, it checks a .netrc file to see if the URL to which the request is sent has login credentials defined. If so, an authorization header is constructed on the fly.

I agree.

> Should the usage of credentials stored in .netrc be optional?

Yes, it should be optional, having a `.netrc` file in your home directory should not be required. Maybe I misunderstood your question?

> In case .netrc is optional -- is it opt-in (i.e. it's not used by default) or opt-out? I'd personally prefer the latter.

I don't think opt-in or opt-out is necessary, it should be used by default and if someone wants an opt-out we can add it when it's requested.

> In case .netrc is optional -- how could this be configured? An environment variable? A new configuration key in hex.config? Something else?

Other tools seems to honor the `NETRC` environment variable for specifying a path other than the home directory.

**Comment by frerich** [comment]
> > Should the usage of credentials stored in .netrc be optional?
> 
> Yes, it should be optional, having a `.netrc` file in your home directory should not be required. Maybe I misunderstood your question?
> [..]
> I don't think opt-in or opt-out is necessary, it should be used by default and if someone wants an opt-out we can add it when it's requested.

Sorry for the imprecision -- of course, the `.netrc` file should be optional. What I meant was whether _using_ it (if it is present) should be made optional.

For example, the cURL documentation explains that by default, the `.netrc` file is not considered at all -- it's just ignored. A dedicated command line argument has to be given to have cURL respect the `.netrc` file. I.e. it's opt-in.

For Wget, it's the other way round: the [Download Options section of the Wget man page](https://www.gnu.org/software/wget/manual/wget.html#Download-Options) documents a `--no-netrc` switch which instructs Wget to _not_ attempt to obtain credentials from `.netrc`. I.e. it's opt-out.

I very much agree with your view here: it should be considered _by default_ and we don't even need to make it configurable at this point. I just wanted to bring this up for completeness. :-)

> > In case .netrc is optional -- how could this be configured? An environment variable? A new configuration key in hex.config? Something else?
> 
> Other tools seems to honor the `NETRC` environment variable for specifying a path other than the home directory.

Ah, interesting -- I never knew this. Thanks for pointing this out! Indeed, a `NETRC` environment variable is mentioned in the [GNU Inetutils manual](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html).

Alright then, I think I have a pretty good idea for how to approach this. I'll give it a shot. :-)

**Comment by wojtekmach** [comment]
Closing in favour of a PR!
