### ISSUE TITLE
Failing 1.0.0 with Elixir 1.11.4 / OTP 24.1.7

### ISSUE THREAD

**Issue by cw789** [hexpm/hex#932]
On using `erlef/setup-beam` combinations of Elixir <= 1.11 and OTP 24 are failing with the new 1.0.0 release.

```
Error: 5.042 [error] Task #PID<0.162.0> started from :hex_fetcher terminating
Warning: ** (UndefinedFunctionError) function :ssl.cipher_suites/1 is undefined or private
    (ssl 10.5.3) :ssl.cipher_suites(:openssl)
    (hex 1.0.0) lib/hex/http/ssl.ex:123: Hex.HTTP.SSL.filter_ciphers/1
```

**Comment by ericmj** [comment]
What exact versions of Elixir and OTP are you using when you get the error?

**Comment by cw789** [comment]
- OTP-24.1.7 / Elixir 1.11.4
- OTP-24.1.7 / Elixir 1.10.4

**Comment by ericmj** [comment]
How are you invoking Hex to produce the error?

**Comment by ericmj** [comment]
Note that OTP 24 support was first added in Elixir 1.11.4. If you are using an older Elixir version with OTP 24 things are not guaranteed to work. You can find that compatibility table here: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp.

**Comment by cw789** [comment]
> How are you invoking Hex to produce the error?

`mix deps.get --only test`

Deprecation and compatibility policy is known.

**Comment by cw789** [comment]
It's concerning this actions: https://github.com/cw789/exqlite/actions/runs/1577031909

**Comment by cw789** [comment]
Probably as a second thought this issue is so minor (old Elixir, possibly not really combination with OTP 24 in the real world) and could be closed from my side.

**Comment by dominicletz** [comment]
This affects my builds as well, anything stopping this from being packaged in a v1.0.1 soon? Thanks!

**Comment by ericmj** [comment]
Nothing stopping it. We will put out a new release today.
