### ISSUE TITLE
Docs: invalid default `:files` value on `hex.publish` page

### ISSUE THREAD

**Issue by bblaszkow06** [hexpm/hex#941]
The docs for task `hex.publish` contain an old default value for `:files` key in package configuration, i.e. `.formatter.exs` is missing. https://hexdocs.pm/hex/Mix.Tasks.Hex.Publish.html#module-package-configuration

The PR to fix that would be trivial, however, I'm thinking about a more "permanent" solution for keeping them in sync - WDYT about:
1. Moving the `@default_files` attribute inside the `hex.build` task before `moduledoc`
2. Referencing that attribute inside the `moduledoc`
3. Exposing it via a public function
4. Call that function inside a `moduledoc` of `hex.publish`

EDIT: I think it could be further extended to expose the whole paragraph on package configuration, as it is duplicated in both places

**Comment by ericmj** [comment]
Great suggestion, a PR with those changes would be very appreciated.
