### ISSUE TITLE
Improve error message when a package already exists

### ISSUE THREAD

**Issue by bortzmeyer** [hexpm/hex#949]
Trying to ` hex publish` a package when there is already one with this same name prints:

```
Publishing failed
account not authorized for this action
```

The error message is misleading, it has nothing to do with the account you use. Something like "package with the name foobar already exists" would be more sensible, IMHO.

**Comment by Coreastreet** [comment]
Hi bortzmeyer,

I wrote a basic fix.
Hope it may be useful to future users.

Regards,
Coreastreet

**Comment by Coreastreet** [comment]
<img width="600" alt="Screenshot 2023-07-27 at 10 35 00 am" src="https://github.com/hexpm/hex/assets/38857013/f3918556-72b1-452e-a6ab-ed2be852fe05">

**Comment by Coreastreet** [comment]
The picture illustrates the new error response.
