### ISSUE TITLE
Validation failed

### ISSUE THREAD

**Issue by michaelnisi** [hexpm/hex#95]
When I try to publish an Erlang module, I get `Validation failed` (422).

https://github.com/michaelnisi/feeder

MIX_EXS=package.exs mix hex.publish
Publishing feeder v1.4.6
  Dependencies:
  Included files:
    src/feeder.app.src
    src/feeder.erl
    erlang.mk
    Makefile
    README.md
    LICENSE
Proceed? [Yn]
[#########################] 100%Pushing feeder v1.4.6 failed (422)
Validation failed
  tar:
    version: not_supported

[{release,"Erlang/OTP","17","6.4",
          [{kernel,"3.2","/usr/local/Cellar/erlang/17.5/lib/erlang/lib/kernel-3.2"},
           {stdlib,"2.4","/usr/local/Cellar/erlang/17.5/lib/erlang/lib/stdlib-2.4"},
           {sasl,"2.4.1","/usr/local/Cellar/erlang/17.5/lib/erlang/lib/sasl-2.4.1"}],
          permanent}].

Elixir (1.0.4)

**Comment by ericmj** [comment]
What hex version are you using? Run `mix hex.info` to check.

**Comment by michaelnisi** [comment]
Duh! It was Hex v0.6.0. Didn't realize that I have to update it separately—I just assumed it comes with Elixir, like npm with Node. It worked fine with Hex v0.7.5 https://hex.pm/packages/feeder. Thank you very much.

**Comment by ericmj** [comment]
Okay. Did you get warnings that Hex was outdated, like this: `A new Hex version is available (v0.7.5), please update with mix local.hex`?

I wonder if the update warning is broken on older hex versions.

**Comment by michaelnisi** [comment]
No warnings with `MIX_EXS=package.exs mix hex.publish`, only `mix hex.info` warned.

**Comment by ericmj** [comment]
Ah, that's because we don't fetch a new registry when publishing so if your registry is old as well you won't get a warning. Thanks for letting me know.
