### ISSUE TITLE
`mix hex.publish` raise error.

### ISSUE THREAD

**Issue by Horx** [hexpm/hex#96]
Hello, when I did `mix hex.publish`, It always raise an error:

```
** (ArgumentError) argument error: nil
    lib/hex/util.ex:170: Hex.Util.print_error_result/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2
```

my hex version:
Hex v0.7.5

**Comment by ericmj** [comment]
The error printing bug is fixed in master. We just migrated the database, can you try publishing again?

**Comment by Horx** [comment]
still has the same error. but the package was created on hex web, [mpinyin](https://hex.pm/packages/mpinyin), and It has no version info.

**Comment by ericmj** [comment]
A fix is deployed. Can you try again?

**Comment by Horx** [comment]
Yes, published successfully. Thank you.
