### ISSUE TITLE
Only remove current hex.ez if download is successful

### ISSUE THREAD

**Issue by jeregrine** [hexpm/hex#97]
I have the cannot verify issuer issue. And sometimes I think "maybe thats working now" and hit yes when it asks if I want to install. And it fails everytime, which is fine I'm used to it.

But the issue is that it removes the existing hex before it fails and I have to manually install it everytime.

**Comment by ericmj** [comment]
Please open this issue on elixir-lang/elixir since hex installation is implemented there.

**Comment by jeregrine** [comment]
Can do
