### ISSUE TITLE
`hex.info`: `--repo` is an unknown option

### ISSUE THREAD

**Issue by NobbZ** [hexpm/hex#970]
In the company I am working for, we are currently still using a mini repo and can't easily change that and will have to carry that forward for while.

But as it reports weird version info on `hex.outdated` I wanted to inspect that using `hex.info`, though that command doesn't seem to understand the `--repo` option, so it wouldn't be usable with `hex.registry` either.

Is this an oversight or technical limitation?

**Comment by wojtekmach** [comment]
It is missing functionality in minirepo. `mix hex.info` fetches data from the [HTTP API](https://github.com/hexpm/specifications/blob/main/endpoints.md), https://hex.pm/api. minirepo implements a very small subset of the API and it doesn't implement the `/packages/:name` endpoint which the task would use. If you implement the endpoint yourself, it should just work. Although you'd need to make sure the proper API url is being used, e.g.: `HEX_API_URL=https://acme/hex/api mix hex.info`. Check `mix help hex.config` for more information on configuration.

A `mix hex.info --repo` flag would probably be better UX but it would require rethinking HTTP API/Repo API distinction and there's no plans for that at the moment.

Let me know if you run into any issues!
