### ISSUE TITLE
Unknown package version in lockfile

### ISSUE THREAD

**Issue by anmlnath** [hexpm/hex#973]
A number of people who upgraded Oban Pro from 0.12.0 to 0.13.0 are having an issue where Hex isn't always finding the package. Oban Pro requires an authentication step, but the failure is happening when running `mix deps.get`.

```
** (Mix) Unknown package version oban_pro 0.13.0 in lockfile
```

I'm seeing this regularly in GitHub Actions runs, but re-running will often solve it. The failure is intermittent, and only started with the 0.13.0 upgrade.

@sorentwo has a theory that it may be related to optional dependencies and is doing some experimentation. 

Any insights?

**Comment by sorentwo** [comment]
This was due to a version cache inconsistency between servers. Nothing to see here!

**Comment by ericmj** [comment]
@sorentwo Thanks for letting us know what issue was and solving it.
