### ISSUE TITLE
ERROR! Missing metadata fields: build_tools

### ISSUE THREAD

**Issue by AntonFagerberg** [hexpm/hex#98]
I'm trying to publish my project [Rackla](https://github.com/AntonFagerberg/rackla) to Hex but I'm getting the following errors:

```
Publishing rackla v0.1.0
  Dependencies:
    cowboy ~> 1.0 (optional)
    hackney ~> 1.1
    plug ~> 0.12
    poison ~> 1.4
  Files:
    lib/rackla/rackla.ex
    lib/rackla/request.ex
    lib/rackla/response.ex
    README.md
    LICENSE
  App: rackla
  Name: rackla
  Version: 0.1.0
  Description: Rackla is library used for building API-gateways.
  Licenses: Apache 2
  Contributors: Anton Fagerberg
  Links:
    GitHub: https://github.com/AntonFagerberg/rackla
  Elixir: ~> 1.0
  ERROR! Missing metadata fields: build_tools
  WARNING! Excluded dependencies (not part of the Hex package):
    earmark
    ex_doc
Proceed? [Yn]
[#########################] 100%Pushing rackla v0.1.0 failed
Validation failed
  meta:
    build_tools: missing
```

Heres the mix.exs file: https://github.com/AntonFagerberg/rackla/blob/master/mix.exs

**Comment by ericmj** [comment]
build_tools is missing because your project will actually not build. You don't have `mix.exs` in the list of files to include in your package, if you remove the `:files` option it will work.

**Comment by josevalim** [comment]
The error message could be better here then. We need to say we could not figure out how to build the project because it doesn't have a Makefile, mix.exs or rebar.config. No?

**Comment by ericmj** [comment]
We allow pushing packages that we do not know how to build but then you have to supply the build_tool information yourself.

**Comment by AntonFagerberg** [comment]
Ah, I had miss-spelled it "mix.ex" without the s in the end.
Now it works, thanks!

**Comment by AntonFagerberg** [comment]
Perhaps it would be good to do a warning here, so in my "files" list in "package", I declared "mix.ex" which didn't exist (spelled wrong). It might be a good idea to warn about the missing files as well?
