### ISSUE TITLE
Suggesstion: Show readme file content on package page

### ISSUE THREAD

**Issue by bluzky** [hexpm/hex#987]
Hi, I noticed that most of the time when I search a package on hex.pm, next action I do is clicking on the project't github link to view the README for how to use the library. Then if I want to explore more, I go to library's hexdocs.
So I suggest that we could show content of Readme file on the library page, it will save lots of time navigating to other site.

How do you think about that?

I really like crates.io for how they show it.
<img width="1280" alt="Screen Shot 2023-03-21 at 7 55 50 AM" src="https://user-images.githubusercontent.com/6194779/226496566-afdbc107-5dd7-4457-b8a1-8d4484c9bb40.png">

Thanks.

**Comment by ericmj** [comment]
Thanks for the suggestion, we are planning to do this for the website redesign.
